(() => {
'use strict';

const ENDPOINT='https://script.google.com/macros/s/AKfycbxPSc2Ep3IkZ7lDV1tkm3dnBWgMV0QVrRfx50WJJJXN-q1xELZSWrfdJt3lTxaAXG2miA/exec';
const RAW_FETCH=window.fetch.bind(window);
const CACHE_PREFIX='ofaro_api_v3:';
const MAX_CONCURRENT=2;
const STALE_MAX=10*60*1000;
const WRITE_DEDUPE_MS=20000;
const READ_TTL={appPing:15000,appBootstrap:15000,terminalPing:8000,reservationList:8000,qrList:45000,templateList:45000,historyList:20000,webSections:45000,webSectionRows:12000,printQueueStatus:7000,printQueueList:4000,promotionList:12000,prizeList:30000,promotionPrizeList:30000,promotionStats:20000,wheelSegmentsList:15000,promotionPrizeLinksList:15000,promotionHistory:12000,promotionValidate:5000,promoPublicGet:5000};
const READ_ACTIONS=new Set(Object.keys(READ_TTL));
const inFlight=new Map();
const writeInFlight=new Map();
const recentWrites=new Map();
let active=0;
const queue=[];
let forceUntil=0;
const forceActions=new Set();
const safeJson=s=>{try{return JSON.parse(s);}catch(_){return null;}};
const now=()=>Date.now();
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(36);}
function cacheKey(action,body){const b={...body};delete b.key;delete b.terminal;delete b.appVersion;return CACHE_PREFIX+action+':'+hash(JSON.stringify(b));}
function readCache(action,body){try{const x=safeJson(localStorage.getItem(cacheKey(action,body))||'');return x&&x.data?x:null;}catch(_){return null;}}
function writeCache(action,body,data){if(!READ_ACTIONS.has(action)||!data||data.ok===false)return;try{localStorage.setItem(cacheKey(action,body),JSON.stringify({at:now(),data}));}catch(_){}}
function clearCache(actionPrefix=''){try{Object.keys(localStorage).filter(k=>k.startsWith(CACHE_PREFIX+(actionPrefix||''))).forEach(k=>localStorage.removeItem(k));}catch(_){}}
function jsonResponse(obj,status=200){return new Response(JSON.stringify(obj),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});}
function enqueue(fn){return new Promise((resolve,reject)=>{queue.push({fn,resolve,reject});pump();});}
function pump(){while(active<MAX_CONCURRENT&&queue.length){const j=queue.shift();active++;Promise.resolve().then(j.fn).then(j.resolve,j.reject).finally(()=>{active--;pump();});}}
function isAppsScript(input,opts){const url=typeof input==='string'?input:(input&&input.url)||'';return /script\.google\.com\/macros\/s\//.test(url)&&String(opts?.method||'GET').toUpperCase()==='POST';}
function campaignCompat(p){if(!p||typeof p!=='object'||!('ID_PROMOCION'in p))return p;return {id:p.ID_PROMOCION||'',name:p.NOMBRE||'',description:p.DESCRIPCION||'',type:p.TIPO_PROMOCION||'Ruleta',state:p.ESTADO||'Pausada',active:p.ACTIVA||'No',startDate:p.FECHA_INICIO||'',endDate:p.FECHA_FIN||'',startTime:p.HORA_INICIO||'00:00',endTime:p.HORA_FIN||'23:59',activeDays:p.DIAS_ACTIVOS||'',winProbability:p.PROB_GANAR??0,winMessage:p.MENSAJE_GANA||'',loseMessage:p.MENSAJE_NO_GANA||'',ticketTemplate:p.PLANTILLA_TICKET||'',imageUrl:p.IMAGEN_URL||'',qrUrl:p.QR_URL||'',totalLimit:p.LIMITE_TOTAL_USOS??'',clientLimit:p.LIMITE_POR_CLIENTE??'',dailyLimit:p.LIMITE_POR_DIA??'',requiresCode:p.REQUIERE_CODIGO||'No',allowedTerminals:p.TERMINALES_PERMITIDOS||'',order:p.ORDEN??999};}
function normalizeWeights(items){const src=items.map((x,i)=>({prizeId:x.prizeId||x.ID_PREMIO||'',weight:Math.max(0,Number(x.weight??x.PESO??0)),percentage:Number(x.percentage??x.PORCENTAJE??0),active:x.active!==false,order:x.order||x.ORDEN||i+1,stockAssigned:x.stockAssigned??x.STOCK_ASIGNADO??''}));let totalPct=src.reduce((n,x)=>n+(Number(x.percentage)||0),0);if(totalPct>0)return src;let total=src.reduce((n,x)=>n+x.weight,0);if(total<=0){src.forEach(x=>x.weight=1);total=src.length||1;}let used=0;src.forEach((x,i)=>{if(i===src.length-1)x.percentage=Math.max(0,100-used);else{x.percentage=Math.round(x.weight/total*1000000)/10000;used+=x.percentage;}});return src;}
function rewriteRequest(body){const original=body.action||'';const b={...body};switch(original){case'prizeList':b.action='promotionPrizeList';break;case'promotionToggle':b.action='promotionSetState';b.state=body.active?'Activa':'Pausada';delete b.active;break;case'wheelSegmentsList':b.action='promotionGet';b.id=body.promotionId||body.id||'';break;case'wheelSegmentsSave':b.action='promotionReplaceSegments';b.id=body.promotionId||body.id||'';b.segments=(body.items||[]).map((x,i)=>({id:x.id||'',label:x.label||x.ETIQUETA||'',prizeId:x.prizeId||x.ID_PREMIO||'',percentage:Number(x.percent??x.percentage??x.PORCENTAJE??0),active:x.active!==false,resultType:x.resultType||x.TIPO_RESULTADO||((x.prizeId||x.ID_PREMIO)==='P000'?'SIN_PREMIO':'PREMIO'),style:x.style||'premium',message:x.message||'',order:x.order||i+1}));delete b.items;break;case'promotionPrizeLinksList':b.action='promotionGet';b.id=body.promotionId||body.id||'';break;case'promotionPrizeLinksSave':b.action='promotionReplacePrizes';b.id=body.promotionId||body.id||'';b.prizes=normalizeWeights(body.items||[]);delete b.items;break;case'prizeSave':b.action='promotionPrizeSave';if(b.prize){b.prize={...b.prize,ticketText:b.prize.ticketText??b.prize.ticketDescription??''};delete b.prize.ticketDescription;}break;case'promotionSave':b.promotion=campaignCompat(body.promotion);break;}return{original,body:b};}
function renameTemplate(v){return String(v||'').replace(/Participación Premium/gi,'Promoción Premium').replace(/Participación Clásica/gi,'Promoción Clásica');}
function rewriteResponse(original,j){if(!j||typeof j!=='object'||j.ok===false)return j;if(original==='promotionList')return{...j,items:(j.items||[]).map(x=>({...x,ticketTemplate:renameTemplate(x.ticketTemplate)}))};if(original==='prizeList')return{...j,items:(j.items||[]).map(p=>({...p,ticketDescription:p.ticketText||'',stockRemaining:p.remaining,remaining:p.remaining}))};if(original==='promotionStats'){const s=j.stats||{};return{...j,...s,total:s.plays||0,winners:s.winners||0,redeemed:s.redeemed||0,winRate:s.winRate||0};}if(original==='wheelSegmentsList')return{ok:true,items:(j.segments||[]).map(s=>({...s,ETIQUETA:s.label,ID_PREMIO:s.prizeId,PORCENTAJE:s.percentage,ACTIVO:s.active?'Sí':'No',TIPO_RESULTADO:s.resultType}))};if(original==='promotionPrizeLinksList')return{ok:true,items:(j.prizeLinks||[]).map(x=>({...x,ID_PREMIO:x.prizeId,PESO:x.weight,PORCENTAJE:x.percentage,ACTIVO:x.active?'Sí':'No'}))};if(original==='promotionPlay')return{...j,won:!!j.hasPrize,canRedeem:!!j.hasPrize,promotionName:j.promotion?.name||j.promotionName||'',wheelTargetIndex:Math.max(0,(Number(j.segmentOrder)||1)-1),ticketTemplate:renameTemplate(j.ticketTemplate)};if(original==='promotionValidate')return{...j,canRedeem:j.canRedeem??(j.redeemable&&j.state==='GANADO')};if(original==='promotionHistory')return{...j,items:(j.items||[]).map(x=>({...x,date:x.createdAt||x.date||''}))};return j;}
async function networkRequest(rewritten,options,attempt=0){const isRead=READ_ACTIONS.has(rewritten.original);const controller=new AbortController();const timeout=isRead?(attempt?14000:8000):45000;const timer=setTimeout(()=>controller.abort(),timeout);const opts={...options,method:'POST',cache:'no-store',redirect:'follow',signal:controller.signal,headers:{...(options.headers||{}),'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(rewritten.body||{})};try{const r=await RAW_FETCH(ENDPOINT,opts);const text=await r.text();const j=safeJson(text);if(!j){const e=new Error('Apps Script devolvió HTML o una respuesta inválida.');e.retryable=true;throw e;}const out=rewriteResponse(rewritten.original,j);if(!r.ok||out?.ok===false){const e=new Error(out?.error||`HTTP ${r.status}`);e.retryable=r.status>=500;throw e;}return out;}catch(e){if((e.name==='AbortError'||e.retryable)&&attempt===0&&isRead)return networkRequest(rewritten,options,1);throw e;}finally{clearTimeout(timer);}}
function refreshRead(rewritten,options,action,body,key){if(inFlight.has(key))return inFlight.get(key);const p=enqueue(()=>networkRequest(rewritten,options).then(data=>{writeCache(action,body,data);return data;})).finally(()=>inFlight.delete(key));inFlight.set(key,p);return p;}
async function perform(body,options){const rewritten=rewriteRequest(body);const action=rewritten.original;const isRead=READ_ACTIONS.has(action);const key=cacheKey(action,body);if(isRead){const cached=readCache(action,body);const age=cached?now()-cached.at:Infinity;const forced=now()<forceUntil||forceActions.has(action);if(cached&&!forced&&age<STALE_MAX){refreshRead(rewritten,options,action,body,key).catch(()=>null);return cached.data;}if(inFlight.has(key))return inFlight.get(key);const job=refreshRead(rewritten,options,action,body,key).catch(err=>{if(cached)return{...cached.data,_stale:true,_warning:err.message};throw err;});if(forceActions.has(action))forceActions.delete(action);return job;}
const recent=recentWrites.get(key);if(recent&&now()-recent.at<WRITE_DEDUPE_MS)return recent.data;if(writeInFlight.has(key))return writeInFlight.get(key);const job=enqueue(()=>networkRequest(rewritten,options).then(data=>{recentWrites.set(key,{at:now(),data});clearCache();return data;})).finally(()=>writeInFlight.delete(key));writeInFlight.set(key,job);return job;}
window.fetch=async function(input,options={}){if(!isAppsScript(input,options))return RAW_FETCH(input,options);const body=safeJson(typeof options.body==='string'?options.body:'')||{};try{return jsonResponse(await perform(body,options),200);}catch(e){const msg=e.name==='AbortError'?'La conexión está tardando demasiado.':(e.message||String(e));return jsonResponse({ok:false,error:msg},200);}};
async function post(action,payload={}){const key=localStorage.getItem('ofaro_gestion_key')||'';const terminal=localStorage.getItem('ofaro_gestion_terminal')||'iPhone O Faro';const r=await window.fetch(ENDPOINT,{method:'POST',body:JSON.stringify({action,key,terminal,appVersion:'api-v3',...payload})});const j=await r.json();if(!j||j.ok===false)throw new Error(j?.error||'Error de API');return j;}
document.addEventListener('click',e=>{if(e.target.closest('#promoRefresh')){forceActions.add('promotionList');return;}if(e.target.closest('#syncButton,[data-force-refresh]')){forceUntil=now()+3500;}},true);
window.addEventListener('online',()=>{forceActions.add('promotionList');});
window.OFaroApi={endpoint:ENDPOINT,post,clearCache,forceRefresh:(action)=>{if(action)forceActions.add(action);else forceUntil=now()+3500;}};
})();