package com.ofaro.participaciones;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.app.DatePickerDialog;
import android.app.TimePickerDialog;
import android.content.ClipboardManager;
import android.content.ClipData;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import org.json.JSONArray;
import org.json.JSONObject;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * O Faro Gestión v5 · shell de una sola Activity.
 * La barra superior e inferior permanecen fijas y solo cambia el contenido central.
 */
public class HomeActivityV2 extends Activity {
    private static final int HOME=0,RESERVATIONS=1,PROMOTIONS=2,STATS=3,MANAGEMENT=4,SETTINGS=5;
    private static final String[] SECTION_NAMES={"Inicio","Reservas","Promociones","Estadísticas","Gestión","Configuración"};

    private AppCore core;
    private FrameLayout contentHost,navHost;
    private TextView printerState,headerSection;
    private View fab;
    private int currentSection=HOME;
    private boolean inSubpage=false;
    private String reservationMode="HOY",promoMode="RESUMEN",statsPeriod="Hoy";
    private JSONArray reservations=new JSONArray(),campaigns=new JSONArray(),prizes=new JSONArray(),templates=new JSONArray(),history=new JSONArray();
    private EditText redeemInput;
    private TextView redeemResult,redeemConfirm;
    private String validatedCode="";

    private final Handler ui=new Handler(Looper.getMainLooper());
    private final ExecutorService io=Executors.newFixedThreadPool(3);
    private final Runnable tick=new Runnable(){@Override public void run(){refreshPrinter();ui.postDelayed(this,2500);}};

    @Override protected void onCreate(Bundle state){
        super.onCreate(state);
        V5Ui.applySystemBars(this);
        core=new AppCore(this);
        reservations=core.cachedArray("reservations_all_v5");
        campaigns=core.cachedArray("promo_campaigns");
        prizes=core.cachedArray("promo_prizes");
        templates=core.cachedArray("templates_v5");
        history=core.cachedArray("history_v5");
        setContentView(buildShell());
        core.startPrinterWatchdog();
        requestNotificationOnce();
        showSection(HOME,false);
        refreshAll();
    }

    @Override protected void onStart(){super.onStart();ui.removeCallbacks(tick);ui.post(tick);}
    @Override protected void onResume(){super.onResume();if(core!=null){core.startPrinterWatchdog();refreshPrinter();}}
    @Override protected void onStop(){ui.removeCallbacks(tick);super.onStop();}
    @Override protected void onDestroy(){ui.removeCallbacksAndMessages(null);io.shutdownNow();super.onDestroy();}

    @Override public void onBackPressed(){
        if(inSubpage){showSection(currentSection,true);return;}
        if(currentSection!=HOME){showSection(HOME,true);return;}
        super.onBackPressed();
    }

    private View buildShell(){
        FrameLayout root=new FrameLayout(this);root.setBackgroundColor(V5Ui.BG);
        LinearLayout shell=V5Ui.column(this);
        V5Ui.Header header=V5Ui.header(this,core,"Inicio");printerState=header.printer;headerSection=header.section;
        printerState.setOnClickListener(v->{showSection(SETTINGS,false);showPrinterSettingsPage();});
        shell.addView(header.view);
        contentHost=new FrameLayout(this);contentHost.setClipToPadding(false);shell.addView(contentHost,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));
        navHost=new FrameLayout(this);shell.addView(navHost,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));
        root.addView(shell,new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));
        fab=V5Ui.floatingPlus(this,this::quickActions);FrameLayout.LayoutParams fp=new FrameLayout.LayoutParams(V5Ui.dp(this,46),V5Ui.dp(this,46),Gravity.RIGHT|Gravity.BOTTOM);fp.rightMargin=V5Ui.dp(this,22);fp.bottomMargin=V5Ui.dp(this,67);root.addView(fab,fp);
        return root;
    }

    private void showSection(int section,boolean animate){
        currentSection=section;inSubpage=false;redeemInput=null;redeemResult=null;redeemConfirm=null;validatedCode="";
        if(headerSection!=null)headerSection.setText(SECTION_NAMES[section]);
        rebuildNav();
        View next=buildSection(section);
        swapContent(next,animate);
    }

    private View buildSection(int section){
        if(section==RESERVATIONS)return buildReservations();
        if(section==PROMOTIONS)return buildPromotions();
        if(section==STATS)return buildStats();
        if(section==MANAGEMENT)return buildManagement();
        if(section==SETTINGS)return buildSettings();
        return buildHome();
    }

    private void rebuildNav(){
        navHost.removeAllViews();navHost.addView(V5Ui.bottomNav(this,currentSection,index->showSection(index,true)),new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));
    }

    private void swapContent(View next,boolean animate){
        if(!animate||contentHost.getChildCount()==0){contentHost.removeAllViews();contentHost.addView(next,new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));return;}
        View old=contentHost.getChildAt(0);old.animate().cancel();old.animate().alpha(0f).setDuration(70).withEndAction(()->{contentHost.removeAllViews();next.setAlpha(0f);contentHost.addView(next,new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));next.animate().alpha(1f).setDuration(120).start();}).start();
    }

    private ScrollView scrollPage(LinearLayout page){ScrollView s=new ScrollView(this);s.setFillViewport(true);s.setClipToPadding(false);s.addView(page);return s;}
    private LinearLayout page(){LinearLayout p=V5Ui.column(this);p.setPadding(V5Ui.dp(this,18),V5Ui.dp(this,8),V5Ui.dp(this,18),V5Ui.dp(this,24));return p;}

    // INICIO
    private View buildHome(){
        LinearLayout p=page();p.addView(V5Ui.kicker(this,currentDate().toUpperCase(new Locale("es","ES"))));TextView greet=V5Ui.title(this,greeting());greet.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,3));p.addView(greet);p.addView(V5Ui.subtitle(this,"Lo necesario para el servicio, sin ruido."));
        p.addView(homeTodayCard(),top(V5Ui.dp(this,14)));p.addView(sectionLabel("ACTIVIDAD"));
        LinearLayout row=V5Ui.row(this);row.addView(metricCard("PROMOCIONES",String.valueOf(activeCampaignCount()),"activas",()->showSection(PROMOTIONS,true)),weightGap());row.addView(metricCard("WEB","—","analítica pendiente",()->showSection(STATS,true)),weightGap());p.addView(row);
        p.addView(sectionLabel("ACCIONES"));LinearLayout q1=V5Ui.row(this);q1.addView(V5Ui.quickAction(this,R.drawable.ic_plus_v5,"Reserva",this::showNewReservation),weightGap());q1.addView(V5Ui.quickAction(this,R.drawable.ic_qr_v5,"Generar QR",this::showQrGenerator),weightGap());p.addView(q1);LinearLayout q2=V5Ui.row(this);q2.addView(V5Ui.quickAction(this,R.drawable.ic_check_v5,"Canjear",this::showRedeemPage),weightGap());q2.addView(V5Ui.quickAction(this,R.drawable.ic_print_v5,"Imprimir",this::showFreePrintPage),weightGap());p.addView(q2,top(V5Ui.dp(this,7)));
        LinearLayout server=V5Ui.card(this);server.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,16));String s=core.configured()?(core.internetAvailable()?"Servidor preparado":"Sin Internet · usando caché"):"Falta configurar acceso al servidor";server.addView(V5Ui.text(this,s,10.5f,core.configured()?V5Ui.MUTED:V5Ui.ERROR,false));server.addView(V5Ui.text(this,"O Faro Gestión · v"+BuildConfig.VERSION_NAME,9.5f,V5Ui.FAINT,false));p.addView(server,top(V5Ui.dp(this,13)));return scrollPage(p);
    }

    private View homeTodayCard(){
        JSONArray today=filterReservations(reservations,"HOY");int people=0;JSONObject next=null;String best="99:99";for(int i=0;i<today.length();i++){JSONObject r=today.optJSONObject(i);if(r==null)continue;people+=Math.max(0,r.optInt("people",0));String t=r.optString("time","99:99");if(t.compareTo(best)<0){best=t;next=r;}}
        LinearLayout c=V5Ui.darkCard(this);c.setOnClickListener(v->showSection(RESERVATIONS,true));TextView k=V5Ui.kicker(this,"HOY");k.setTextColor(Color.rgb(193,205,195));c.addView(k);LinearLayout nums=V5Ui.row(this);nums.setPadding(0,V5Ui.dp(this,10),0,0);nums.addView(darkMetric(String.valueOf(today.length()),"reservas"),new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));nums.addView(darkMetric(String.valueOf(people),"personas"),new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));c.addView(nums);View line=new View(this);line.setBackgroundColor(V5Ui.LIME);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(V5Ui.dp(this,46),V5Ui.dp(this,2));lp.topMargin=V5Ui.dp(this,13);lp.bottomMargin=V5Ui.dp(this,11);c.addView(line,lp);TextView kl=V5Ui.kicker(this,"PRÓXIMA");kl.setTextColor(Color.rgb(193,205,195));c.addView(kl);String txt=next==null?"No hay reservas guardadas para hoy":next.optString("time","--:--")+" · "+next.optString("name","Reserva")+" · "+next.optInt("people",0)+" pers."+(next.optString("zone","").isEmpty()?"":" · "+next.optString("zone"));c.addView(V5Ui.text(this,txt,12.5f,Color.WHITE,true));return c;
    }

    private LinearLayout darkMetric(String value,String note){LinearLayout c=V5Ui.column(this);c.addView(V5Ui.text(this,value,31,Color.WHITE,true));c.addView(V5Ui.text(this,note,10.5f,Color.rgb(197,207,198),false));return c;}
    private View metricCard(String label,String value,String note,Runnable action){LinearLayout c=V5Ui.metric(this,label,value,note);if(action!=null)c.setOnClickListener(v->action.run());return c;}

    // RESERVAS
    private View buildReservations(){
        LinearLayout p=page();p.addView(V5Ui.kicker(this,"RESERVAS"));TextView title=V5Ui.title(this,titleForReservationMode());title.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,12));p.addView(title);p.addView(reservationTabs());JSONArray list=filterReservations(reservations,reservationMode);TextView count=V5Ui.text(this,list.length()+" reservas",10.5f,V5Ui.MUTED,false);count.setPadding(0,V5Ui.dp(this,12),0,V5Ui.dp(this,8));p.addView(count);if(list.length()==0){LinearLayout empty=V5Ui.softCard(this);empty.addView(V5Ui.text(this,"No hay reservas en este apartado.",12.5f,V5Ui.MUTED,false));p.addView(empty);}for(int i=0;i<list.length();i++){JSONObject r=list.optJSONObject(i);if(r!=null)p.addView(reservationCard(r),bottom(V5Ui.dp(this,7)));}return scrollPage(p);
    }

    private View reservationTabs(){LinearLayout row=V5Ui.row(this);String[] modes={"HOY","PRÓXIMAS","PENDIENTES","HISTÓRICO"};for(String m:modes){boolean on=m.equals(reservationMode);TextView chip=chip(labelMode(m),on);chip.setOnClickListener(v->{reservationMode=m;showSection(RESERVATIONS,false);});row.addView(chip,chipWeight());}return row;}
    private String titleForReservationMode(){if("PRÓXIMAS".equals(reservationMode))return"Próximas reservas";if("PENDIENTES".equals(reservationMode))return"Por confirmar";if("HISTÓRICO".equals(reservationMode))return"Histórico";return"Reservas de hoy";}

    private JSONArray filterReservations(JSONArray raw,String mode){List<JSONObject> list=new ArrayList<>();String today=LocalDate.now().toString();for(int i=0;i<raw.length();i++){JSONObject r=raw.optJSONObject(i);if(r==null)continue;String date=r.optString("date","");String state=r.optString("state","");String service=r.optString("serviceState","");boolean closed="Cancelada".equalsIgnoreCase(state)||"Denegada".equalsIgnoreCase(state)||"Completada".equalsIgnoreCase(service)||"No se presentó".equalsIgnoreCase(service);boolean keep;if("HOY".equals(mode))keep=today.equals(date)&&!closed;else if("PRÓXIMAS".equals(mode))keep=date.compareTo(today)>0&&!closed;else if("PENDIENTES".equals(mode))keep="Pendiente".equalsIgnoreCase(state)&&!closed;else keep=date.compareTo(today)<0||closed;if(keep)list.add(r);}list.sort(Comparator.comparing(x->x.optString("date","")+" "+x.optString("time","")));JSONArray out=new JSONArray();for(JSONObject r:list)out.put(r);return out;}

    private View reservationCard(JSONObject r){LinearLayout c=V5Ui.card(this);c.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,18));c.setOnClickListener(v->showReservationDetail(r));LinearLayout top=V5Ui.row(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(V5Ui.text(this,r.optString("time","--:--"),20,V5Ui.INK,true),new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));top.addView(statePill(r.optString("state","Pendiente")));c.addView(top);TextView name=V5Ui.text(this,r.optString("name","Reserva"),14.5f,V5Ui.INK,true);name.setPadding(0,V5Ui.dp(this,6),0,0);c.addView(name);String meta=r.optInt("people",0)+" personas"+(r.optString("zone","").isEmpty()?"":" · "+r.optString("zone"))+(r.optString("table","").isEmpty()?"":" · Mesa "+r.optString("table"));c.addView(V5Ui.text(this,meta,10.5f,V5Ui.MUTED,false));return c;}

    private TextView statePill(String state){int fill=V5Ui.LIME_SOFT,color=V5Ui.GREEN;if("Pendiente".equalsIgnoreCase(state)){fill=Color.rgb(235,236,232);color=V5Ui.MUTED;}if("Cancelada".equalsIgnoreCase(state)||"Denegada".equalsIgnoreCase(state)){fill=Color.rgb(248,229,225);color=V5Ui.ERROR;}return V5Ui.pill(this,state,fill,color);}

    private void showReservationDetail(JSONObject r){
        currentSection=RESERVATIONS;inSubpage=true;headerSection.setText("Reservas");rebuildNav();LinearLayout p=page();p.addView(backLink("Reservas",()->showSection(RESERVATIONS,true)));LinearLayout h=V5Ui.row(this);h.setGravity(Gravity.CENTER_VERTICAL);LinearLayout copy=V5Ui.column(this);copy.addView(V5Ui.kicker(this,"RESERVA"));copy.addView(V5Ui.title(this,r.optString("name","Reserva")));h.addView(copy,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));h.addView(statePill(r.optString("state","Pendiente")));p.addView(h);TextView meta=V5Ui.subtitle(this,r.optString("date","")+" · "+r.optString("time","")+" · "+r.optInt("people",0)+" personas");meta.setPadding(0,V5Ui.dp(this,8),0,V5Ui.dp(this,13));p.addView(meta);
        LinearLayout location=V5Ui.softCard(this);location.addView(V5Ui.kicker(this,"UBICACIÓN"));location.addView(V5Ui.text(this,"Mesa "+dash(r.optString("table",""))+" · "+dash(r.optString("zone","")),14,V5Ui.INK,true));p.addView(location);LinearLayout notes=V5Ui.card(this);notes.addView(V5Ui.kicker(this,"OBSERVACIONES"));TextView n=V5Ui.text(this,dash(r.optString("notes","")),12,V5Ui.INK,false);n.setPadding(0,V5Ui.dp(this,6),0,0);notes.addView(n);p.addView(notes,top(V5Ui.dp(this,8)));
        LinearLayout a=V5Ui.row(this);a.addView(action("Llamar",false,()->dial(r.optString("phone",""))),weightGap());a.addView(action("WhatsApp",false,()->whatsapp(r.optString("phone",""))),weightGap());p.addView(a,top(V5Ui.dp(this,12)));LinearLayout b=V5Ui.row(this);b.addView(action("Editar",false,()->showReservationForm(r)),weightGap());b.addView(action("Imprimir",true,()->printReservation(r)),weightGap());p.addView(b,top(V5Ui.dp(this,7)));LinearLayout states=V5Ui.row(this);states.addView(action("Confirmar",false,()->updateReservation(r,"Confirmada",null)),weightGap());states.addView(action("Llegó",false,()->updateReservation(r,null,"Llegó")),weightGap());states.addView(action("Completar",false,()->updateReservation(r,null,"Completada")),weightGap());p.addView(sectionLabel("ESTADO"));p.addView(states);swapContent(scrollPage(p),true);
    }

    private void showNewReservation(){currentSection=RESERVATIONS;rebuildNav();headerSection.setText("Reservas");showReservationForm(null);}
    private void showReservationForm(JSONObject existing){
        inSubpage=true;boolean edit=existing!=null;LinearLayout p=page();p.addView(backLink(edit?"Reserva":"Reservas",()->{if(edit)showReservationDetail(existing);else showSection(RESERVATIONS,true);}));p.addView(V5Ui.kicker(this,edit?"EDITAR RESERVA":"NUEVA RESERVA"));TextView title=V5Ui.title(this,edit?"Actualizar datos":"Añadir reserva");title.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,10));p.addView(title);
        EditText name=field(p,"Nombre",edit?existing.optString("name",""):"",InputType.TYPE_CLASS_TEXT);EditText phone=field(p,"Teléfono",edit?existing.optString("phone",""):"",InputType.TYPE_CLASS_PHONE);EditText email=field(p,"Correo",edit?existing.optString("email",""):"",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);EditText date=picker(p,"Fecha",edit?existing.optString("date",LocalDate.now().toString()):LocalDate.now().toString(),true);EditText time=picker(p,"Hora",edit?existing.optString("time","14:00"):"14:00",false);EditText people=field(p,"Personas",edit?String.valueOf(existing.optInt("people",2)):"2",InputType.TYPE_CLASS_NUMBER);EditText table=field(p,"Mesa",edit?existing.optString("table",""):"",InputType.TYPE_CLASS_TEXT);Spinner zone=zoneSpinner(p,edit?existing.optString("zone","Interior"):"Interior");EditText notes=multi(p,"Observaciones",edit?existing.optString("notes",""):"");TextView save=action(edit?"Guardar cambios":"Guardar reserva",true,()->saveReservation(existing,value(date),value(time),value(name),value(phone),value(email),parse(value(people),2),value(table),String.valueOf(zone.getSelectedItem()),value(notes)));p.addView(save,top(V5Ui.dp(this,13)));swapContent(scrollPage(p),true);
    }

    private void saveReservation(JSONObject existing,String date,String time,String name,String phone,String email,int people,String table,String zone,String notes){String error=ReservationRules.validate(name,phone,date,time,people);if(!error.isEmpty()){alert("Revisa la reserva",error);return;}if(!core.configured()){alert("Servidor sin configurar","Configura la clave de acceso en Configuración → Conexión.");return;}io.execute(()->{try{JSONObject q=core.action(existing==null?"reservationCreate":"reservationFullUpdate");if(existing!=null)q.put("id",existing.optString("id",""));q.put("fecha",date).put("hora",time).put("nombre",name).put("telefono",phone).put("correo",email).put("personas",people).put("mesa",table).put("zona",zone).put("observaciones",notes);core.post(q);refreshReservations(true);runOnUiThread(()->{toast(existing==null?"Reserva guardada":"Cambios guardados");showSection(RESERVATIONS,true);});}catch(Exception e){runOnUiThread(()->alert("No se pudo guardar",msg(e)));}});}
    private void updateReservation(JSONObject r,String state,String service){if(!core.configured()){alert("Servidor sin configurar","Configura el acceso primero.");return;}io.execute(()->{try{JSONObject q=core.action("reservationUpdate").put("id",r.optString("id",""));if(state!=null)q.put("state",state);if(service!=null)q.put("serviceState",service);core.post(q);refreshReservations(true);runOnUiThread(()->{toast("Reserva actualizada");showSection(RESERVATIONS,true);});}catch(Exception e){runOnUiThread(()->alert("No se pudo actualizar",msg(e)));}});}
    private void printReservation(JSONObject r){if(core.printerIp().isEmpty()){alert("Impresora sin configurar","Configura la IP en Configuración → Impresora.");return;}io.execute(()->{try{core.printReservation(r);runOnUiThread(()->toast("Ticket enviado a impresora"));}catch(Exception e){runOnUiThread(()->alert("No se pudo imprimir",msg(e)));}});}

    // PROMOCIONES
    private View buildPromotions(){
        LinearLayout p=page();p.addView(V5Ui.kicker(this,"PROMOCIONES"));TextView title=V5Ui.title(this,"Campañas y resultados");title.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,11));p.addView(title);p.addView(promoTabs());if("CAMPAÑAS".equals(promoMode))paintCampaigns(p);else if("PREMIOS".equals(promoMode))paintPrizes(p);else if("CANJES".equals(promoMode))paintRedeem(p);else paintPromoSummary(p);return scrollPage(p);
    }
    private View promoTabs(){LinearLayout row=V5Ui.row(this);String[] values={"RESUMEN","CAMPAÑAS","PREMIOS","CANJES"};for(String m:values){TextView c=chip(labelMode(m),m.equals(promoMode));c.setOnClickListener(v->{promoMode=m;showSection(PROMOTIONS,false);});row.addView(c,chipWeight());}return row;}
    private void paintPromoSummary(LinearLayout p){int plays=0,winners=0;for(int i=0;i<campaigns.length();i++){JSONObject s=campaigns.optJSONObject(i)==null?null:campaigns.optJSONObject(i).optJSONObject("stats");if(s!=null){plays+=s.optInt("plays",0);winners+=s.optInt("winners",0);}}LinearLayout metrics=V5Ui.row(this);metrics.addView(metricCard("ACTIVAS",String.valueOf(activeCampaignCount()),"campañas",null),weightGap());metrics.addView(metricCard("JUGADAS",String.valueOf(plays),"registradas",null),weightGap());metrics.addView(metricCard("PREMIOS",String.valueOf(winners),"ganadores",null),weightGap());p.addView(metrics,top(V5Ui.dp(this,12)));LinearLayout actions=V5Ui.row(this);actions.addView(V5Ui.quickAction(this,R.drawable.ic_qr_v5,"Generar QR",this::showQrGenerator),weightGap());actions.addView(V5Ui.quickAction(this,R.drawable.ic_check_v5,"Canjear",this::showRedeemPage),weightGap());p.addView(actions,top(V5Ui.dp(this,9)));p.addView(sectionLabel("CAMPAÑAS ACTIVAS"));int shown=0;for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c!=null&&c.optBoolean("active",false)){p.addView(campaignCard(c),bottom(V5Ui.dp(this,7)));if(++shown>=3)break;}}if(shown==0){LinearLayout e=V5Ui.softCard(this);e.addView(V5Ui.text(this,"No hay campañas activas.",12,V5Ui.MUTED,false));p.addView(e);}}
    private void paintCampaigns(LinearLayout p){TextView count=V5Ui.text(this,campaigns.length()+" campañas",10.5f,V5Ui.MUTED,false);count.setPadding(0,V5Ui.dp(this,12),0,V5Ui.dp(this,7));p.addView(count);p.addView(action("Nueva campaña",true,this::newCampaignDialog));for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c!=null)p.addView(campaignCard(c),top(V5Ui.dp(this,7)));}}
    private View campaignCard(JSONObject c){LinearLayout card=V5Ui.card(this);card.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,18));card.setOnClickListener(v->showCampaignDetail(c));LinearLayout top=V5Ui.row(this);top.setGravity(Gravity.CENTER_VERTICAL);LinearLayout copy=V5Ui.column(this);copy.addView(V5Ui.kicker(this,c.optString("type","PROMOCIÓN").toUpperCase(Locale.ROOT)));copy.addView(V5Ui.text(this,c.optString("name","Promoción"),14.5f,V5Ui.INK,true));top.addView(copy,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));boolean active=c.optBoolean("active",false);top.addView(V5Ui.pill(this,active?"Activa":"Pausada",active?V5Ui.LIME_SOFT:Color.rgb(235,236,232),active?V5Ui.GREEN:V5Ui.MUTED));card.addView(top);JSONObject s=c.optJSONObject("stats");card.addView(V5Ui.text(this,s==null?"Sin estadísticas":s.optInt("plays",0)+" jugadas · "+s.optInt("winners",0)+" premios",10.5f,V5Ui.MUTED,false));return card;}
    private void showCampaignDetail(JSONObject c){currentSection=PROMOTIONS;inSubpage=true;headerSection.setText("Promociones");rebuildNav();LinearLayout p=page();p.addView(backLink("Campañas",()->{promoMode="CAMPAÑAS";showSection(PROMOTIONS,true);}));p.addView(V5Ui.kicker(this,c.optString("type","PROMOCIÓN").toUpperCase(Locale.ROOT)));TextView t=V5Ui.title(this,c.optString("name","Promoción"));t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,11));p.addView(t);LinearLayout s=V5Ui.darkCard(this);TextView state=V5Ui.text(this,c.optBoolean("active",false)?"● ACTIVA":"● PAUSADA",10,V5Ui.LIME,true);s.addView(state);TextView schedule=V5Ui.text(this,scheduleSummary(c),11.5f,Color.WHITE,false);schedule.setPadding(0,V5Ui.dp(this,8),0,0);s.addView(schedule);JSONObject st=c.optJSONObject("stats");if(st!=null){TextView m=V5Ui.text(this,st.optInt("plays",0)+" jugadas · "+st.optInt("winners",0)+" premios",13,Color.WHITE,true);m.setPadding(0,V5Ui.dp(this,10),0,0);s.addView(m);}p.addView(s);if(c.optBoolean("active",false))p.addView(action("Generar QR real",true,()->issueQr(c)),top(V5Ui.dp(this,10)));p.addView(action("Editar datos",false,()->editCampaignDialog(c)),top(V5Ui.dp(this,7)));p.addView(action(c.optBoolean("active",false)?"Pausar campaña":"Activar campaña",false,()->toggleCampaign(c)),top(V5Ui.dp(this,7)));swapContent(scrollPage(p),true);}
    private void newCampaignDialog(){editCampaignDialog(null);}
    private void editCampaignDialog(JSONObject old){boolean isNew=old==null;LinearLayout box=V5Ui.column(this);box.setPadding(V5Ui.dp(this,16),V5Ui.dp(this,4),V5Ui.dp(this,16),V5Ui.dp(this,5));EditText name=dialogField(box,"Nombre",isNew?"":old.optString("name",""));Spinner type=new Spinner(this);String[] types={"Ruleta","Rasca","Premio directo","Código premiado"};ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,types);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);type.setAdapter(a);if(!isNew){for(int i=0;i<types.length;i++)if(types[i].equals(old.optString("type","")))type.setSelection(i);}box.addView(dialogLabel("Tipo"));box.addView(type,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,V5Ui.dp(this,48)));EditText start=dialogField(box,"Fecha inicio · YYYY-MM-DD",isNew?"":old.optString("startDate",""));EditText end=dialogField(box,"Fecha fin · YYYY-MM-DD",isNew?"":old.optString("endDate",""));EditText startTime=dialogField(box,"Hora inicio",isNew?"00:00":old.optString("startTime","00:00"));EditText endTime=dialogField(box,"Hora fin",isNew?"23:59":old.optString("endTime","23:59"));new AlertDialog.Builder(this).setTitle(isNew?"Nueva campaña":"Editar campaña").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",(d,w)->saveCampaign(old,value(name),String.valueOf(type.getSelectedItem()),value(start),value(end),value(startTime),value(endTime))).show();}
    private void saveCampaign(JSONObject old,String name,String type,String start,String end,String startTime,String endTime){if(name.trim().length()<2){toast("Escribe un nombre");return;}if(!core.configured()){alert("Servidor sin configurar","Configura el acceso primero.");return;}JSONObject c=new JSONObject();try{if(old!=null){String[] keys={"id","description","state","activeDays","winProbability","winMessage","loseMessage","ticketTemplate","totalLimit","clientLimit","dailyLimit","allowedTerminals","order"};for(String k:keys)if(old.has(k))c.put(k,old.opt(k));c.put("active",old.optBoolean("active",false));}else{c.put("state","Pausada").put("active",false).put("activeDays","Lun,Mar,Mié,Jue,Vie,Sáb,Dom").put("winProbability",20).put("winMessage","¡Enhorabuena! Te ha tocado {{premio}}.").put("loseMessage","Esta vez no ha habido premio.").put("clientLimit",1).put("dailyLimit",500).put("order",999);}c.put("name",name).put("type",type).put("startDate",start).put("endDate",end).put("startTime",startTime).put("endTime",endTime).put("requiresCode","Código premiado".equals(type));}catch(Exception ignored){}io.execute(()->{try{core.post(core.action("promotionSave").put("campaign",c));refreshPromotions(true);runOnUiThread(()->{toast("Campaña guardada");promoMode="CAMPAÑAS";showSection(PROMOTIONS,true);});}catch(Exception e){runOnUiThread(()->alert("No se pudo guardar",msg(e)));}});}
    private void toggleCampaign(JSONObject c){if(!core.configured()){alert("Servidor sin configurar","Configura el acceso primero.");return;}boolean active=c.optBoolean("active",false);io.execute(()->{try{core.post(core.action("promotionSetState").put("id",c.optString("id","")).put("state",active?"Pausada":"Activa"));refreshPromotions(true);runOnUiThread(()->{toast(active?"Campaña pausada":"Campaña activada");promoMode="CAMPAÑAS";showSection(PROMOTIONS,true);});}catch(Exception e){runOnUiThread(()->alert("No se pudo cambiar el estado",msg(e)));}});}

    private void paintPrizes(LinearLayout p){TextView count=V5Ui.text(this,prizeCount()+" premios",10.5f,V5Ui.MUTED,false);count.setPadding(0,V5Ui.dp(this,12),0,V5Ui.dp(this,7));p.addView(count);p.addView(action("Nuevo premio",true,()->editPrizeDialog(null)));for(int i=0;i<prizes.length();i++){JSONObject prize=prizes.optJSONObject(i);if(prize==null||"P000".equals(prize.optString("id")))continue;LinearLayout c=V5Ui.card(this);c.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,18));LinearLayout top=V5Ui.row(this);top.addView(V5Ui.text(this,prize.optString("name","Premio"),14.5f,V5Ui.INK,true),new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));top.addView(V5Ui.pill(this,prize.optBoolean("active",true)?"Activo":"Pausado",prize.optBoolean("active",true)?V5Ui.LIME_SOFT:Color.rgb(235,236,232),prize.optBoolean("active",true)?V5Ui.GREEN:V5Ui.MUTED));c.addView(top);c.addView(V5Ui.text(this,"Restante: "+remaining(prize)+" · canjeados: "+prize.optInt("redeemed",0),10.5f,V5Ui.MUTED,false));c.setOnClickListener(v->editPrizeDialog(prize));p.addView(c,top(V5Ui.dp(this,7)));}}
    private void editPrizeDialog(JSONObject old){boolean isNew=old==null;LinearLayout box=V5Ui.column(this);box.setPadding(V5Ui.dp(this,16),V5Ui.dp(this,4),V5Ui.dp(this,16),V5Ui.dp(this,5));EditText name=dialogField(box,"Nombre",isNew?"":old.optString("name",""));EditText stock=dialogField(box,"Stock · vacío = ilimitado",isNew?"":String.valueOf(old.opt("stock")));EditText type=dialogField(box,"Tipo",isNew?"Consumición":old.optString("type","Consumición"));EditText conditions=dialogField(box,"Condiciones",isNew?"":old.optString("conditions",""));new AlertDialog.Builder(this).setTitle(isNew?"Nuevo premio":"Editar premio").setView(box).setNegativeButton("Cancelar",null).setPositiveButton("Guardar",(d,w)->savePrize(old,value(name),value(stock),value(type),value(conditions))).show();}
    private void savePrize(JSONObject old,String name,String stock,String type,String conditions){if(name.isEmpty()){toast("Escribe el nombre");return;}JSONObject p=new JSONObject();try{if(old!=null)p.put("id",old.optString("id","")).put("active",old.optBoolean("active",true)).put("weight",old.optDouble("weight",1)).put("order",old.optInt("order",999)).put("ticketText",old.optString("ticketText","")).put("imageUrl",old.optString("imageUrl","")).put("value",old.optString("value",""));else p.put("id","").put("active",true).put("weight",1).put("order",999).put("ticketText","");p.put("name",name).put("stock",stock.isEmpty()?"":parse(stock,0)).put("type",type).put("conditions",conditions);}catch(Exception ignored){}io.execute(()->{try{core.post(core.action("promotionPrizeSave").put("prize",p));refreshPromotions(true);runOnUiThread(()->{toast("Premio guardado");promoMode="PREMIOS";showSection(PROMOTIONS,true);});}catch(Exception e){runOnUiThread(()->alert("No se pudo guardar",msg(e)));}});}

    private void paintRedeem(LinearLayout p){TextView title=V5Ui.text(this,"Validar y canjear",19,V5Ui.INK,true);title.setPadding(0,V5Ui.dp(this,12),0,V5Ui.dp(this,4));p.addView(title);p.addView(V5Ui.subtitle(this,"Escanea el QR o introduce el código ganador."));p.addView(action("Escanear QR",true,this::scanQr),top(V5Ui.dp(this,10)));redeemInput=input("");redeemInput.setHint("OF-XXXXX-XXXXX");p.addView(redeemInput,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,V5Ui.dp(this,48)));p.addView(action("Validar código",false,()->validateCode(value(redeemInput))),top(V5Ui.dp(this,7)));redeemResult=V5Ui.text(this,"Todavía no hay ningún código validado.",11.5f,V5Ui.MUTED,false);redeemResult.setPadding(V5Ui.dp(this,13),V5Ui.dp(this,12),V5Ui.dp(this,13),V5Ui.dp(this,12));redeemResult.setBackground(V5Ui.bg(this,V5Ui.SURFACE_SOFT,16));p.addView(redeemResult,top(V5Ui.dp(this,9)));redeemConfirm=action("Confirmar canje",true,this::confirmRedeem);redeemConfirm.setVisibility(View.GONE);p.addView(redeemConfirm,top(V5Ui.dp(this,8)));}
    private void showRedeemPage(){currentSection=PROMOTIONS;promoMode="CANJES";showSection(PROMOTIONS,true);}
    private void scanQr(){IntentIntegrator i=new IntentIntegrator(this);i.setDesiredBarcodeFormats(java.util.Collections.singletonList("QR_CODE"));i.setPrompt("Escanea el premio");i.setBeepEnabled(false);i.setOrientationLocked(true);i.initiateScan();}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){IntentResult r=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(r!=null){if(r.getContents()!=null){currentSection=PROMOTIONS;promoMode="CANJES";showSection(PROMOTIONS,false);String code=PromoRules.cleanCode(r.getContents());if(redeemInput!=null){redeemInput.setText(code);validateCode(code);}}return;}super.onActivityResult(requestCode,resultCode,data);}
    private void validateCode(String raw){String code=PromoRules.cleanCode(raw);validatedCode="";if(code.isEmpty()){toast("Código vacío");return;}if(!core.configured()){alert("Servidor sin configurar","Configura el acceso primero.");return;}if(redeemResult!=null)redeemResult.setText("Validando…");io.execute(()->{try{JSONObject r=core.post(core.action("promotionValidate").put("code",code));boolean can=r.optBoolean("canRedeem",false);String finalCode=r.optString("code",code);runOnUiThread(()->{validatedCode=can?finalCode:"";if(redeemResult!=null){redeemResult.setText("Premio: "+dash(r.optString("prize",""))+"\nEstado: "+dash(r.optString("state",""))+"\nPromoción: "+dash(r.optString("promotionName",""))+"\nCódigo: "+finalCode+(can?"\n\nLISTO PARA CANJEAR":"\n\nNo se puede canjear"));redeemResult.setTextColor(can?V5Ui.GREEN:V5Ui.ERROR);}if(redeemConfirm!=null)redeemConfirm.setVisibility(can?View.VISIBLE:View.GONE);});}catch(Exception e){runOnUiThread(()->alert("No se pudo validar",msg(e)));}});}
    private void confirmRedeem(){if(validatedCode.isEmpty())return;String code=validatedCode;new AlertDialog.Builder(this).setTitle("Confirmar canje").setMessage("El código quedará inutilizado después del canje.").setNegativeButton("Cancelar",null).setPositiveButton("Canjear",(d,w)->io.execute(()->{try{JSONObject r=core.post(core.action("promotionRedeem").put("code",code));runOnUiThread(()->{validatedCode="";if(redeemResult!=null)redeemResult.setText("CANJEADO\n"+r.optString("prize","Premio")+"\n"+r.optString("code",code));if(redeemConfirm!=null)redeemConfirm.setVisibility(View.GONE);toast("Canje registrado");});}catch(Exception e){runOnUiThread(()->alert("No se pudo canjear",msg(e)));}})).show();}

    private void showQrGenerator(){currentSection=PROMOTIONS;inSubpage=true;headerSection.setText("Promociones · QR");rebuildNav();LinearLayout p=page();p.addView(backLink("Promociones",()->showSection(PROMOTIONS,true)));p.addView(V5Ui.kicker(this,"QR REAL"));TextView t=V5Ui.title(this,"Generar invitación");t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,5));p.addView(t);p.addView(V5Ui.subtitle(this,"Cada QR se registra en el servidor y permite una sola jugada."));int n=0;for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c==null||!c.optBoolean("active",false))continue;n++;LinearLayout card=V5Ui.card(this);card.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,18));card.addView(V5Ui.text(this,c.optString("name","Promoción"),14.5f,V5Ui.INK,true));card.addView(V5Ui.text(this,scheduleSummary(c),10.5f,V5Ui.MUTED,false));card.addView(action("Generar QR",true,()->issueQr(c)),top(V5Ui.dp(this,8)));p.addView(card,top(V5Ui.dp(this,8)));}if(n==0){LinearLayout e=V5Ui.softCard(this);e.addView(V5Ui.text(this,"No hay promociones activas.",12,V5Ui.MUTED,false));p.addView(e,top(V5Ui.dp(this,10)));}swapContent(scrollPage(p),true);}
    private void issueQr(JSONObject c){if(!core.configured()){alert("Servidor sin configurar","Configura el acceso primero.");return;}io.execute(()->{try{JSONObject r=core.post(core.action("promoPublicIssue").put("id",c.optString("id","")).put("expiresHours",48));String url=r.optString("url","").trim(),token=r.optString("token","").trim();if(!url.startsWith("https://")||token.isEmpty())throw new Exception("Invitación no válida");runOnUiThread(()->showIssuedQr(c,url,token));}catch(Exception e){runOnUiThread(()->alert("No se pudo generar el QR",msg(e)));}});}
    private void showIssuedQr(JSONObject c,String url,String token){inSubpage=true;LinearLayout p=page();p.addView(backLink("QR",this::showQrGenerator));p.addView(V5Ui.kicker(this,"INVITACIÓN CREADA"));TextView t=V5Ui.title(this,c.optString("name","Promoción"));t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,10));p.addView(t);LinearLayout card=V5Ui.darkCard(this);card.addView(V5Ui.text(this,"QR REAL · 48 H · UN SOLO USO",10,V5Ui.LIME,true));TextView link=V5Ui.text(this,url,11.5f,Color.WHITE,false);link.setPadding(0,V5Ui.dp(this,8),0,0);card.addView(link);card.addView(V5Ui.text(this,"Token: "+token,9.5f,Color.rgb(190,201,191),false));p.addView(card);p.addView(action("Imprimir QR",true,()->printQr(c,url)),top(V5Ui.dp(this,10)));p.addView(action("Copiar enlace",false,()->copy(url)),top(V5Ui.dp(this,7)));swapContent(scrollPage(p),true);}
    private void printQr(JSONObject c,String url){io.execute(()->{try{core.printQrTicket(c.optString("name","Promoción"),"ESCANEA PARA JUGAR\nQR REAL · UN SOLO USO · 48 H",url);runOnUiThread(()->toast("QR enviado a impresora"));}catch(Exception e){runOnUiThread(()->alert("No se pudo imprimir",msg(e)));}});}

    // ESTADÍSTICAS
    private View buildStats(){LinearLayout p=page();p.addView(V5Ui.kicker(this,"ESTADÍSTICAS"));TextView t=V5Ui.title(this,"Datos del negocio");t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,4));p.addView(t);p.addView(V5Ui.subtitle(this,"Lectura rápida de reservas, promociones y actividad."));p.addView(periodTabs(),top(V5Ui.dp(this,13)));boolean today="Hoy".equals(statsPeriod);JSONArray rs=today?filterReservations(reservations,"HOY"):new JSONArray();int people=0;for(int i=0;i<rs.length();i++){JSONObject r=rs.optJSONObject(i);if(r!=null)people+=r.optInt("people",0);}LinearLayout r1=V5Ui.row(this);r1.addView(metricCard("RESERVAS",today?String.valueOf(rs.length()):"—",statsPeriod,null),weightGap());r1.addView(metricCard("PERSONAS",today?String.valueOf(people):"—",statsPeriod,null),weightGap());p.addView(r1,top(V5Ui.dp(this,10)));LinearLayout r2=V5Ui.row(this);r2.addView(metricCard("PROMOCIONES",today?String.valueOf(activeCampaignCount()):"—",today?"activas":"histórico pendiente",null),weightGap());r2.addView(metricCard("WEB","—","analítica pendiente",null),weightGap());p.addView(r2,top(V5Ui.dp(this,7)));p.addView(sectionLabel("MÓDULOS"));p.addView(V5Ui.linkCard(this,R.drawable.ic_calendar_v5,"Reservas","Personas, zonas y estados",()->showStatsDetail("Reservas")));p.addView(V5Ui.linkCard(this,R.drawable.ic_gift_v5,"Promociones","QR, jugadas, ganadores y canjes",()->showStatsDetail("Promociones")),top(V5Ui.dp(this,7)));p.addView(V5Ui.linkCard(this,R.drawable.ic_chart_v5,"Web","Visitas, acciones y embudos",()->showStatsDetail("Web")),top(V5Ui.dp(this,7)));p.addView(V5Ui.linkCard(this,R.drawable.ic_print_v5,"Impresión","Tickets y actividad del terminal",()->showStatsDetail("Impresión")),top(V5Ui.dp(this,7)));return scrollPage(p);}
    private View periodTabs(){LinearLayout row=V5Ui.row(this);String[] vals={"Hoy","7 días","30 días","Mes"};for(String v:vals){TextView c=chip(v,v.equals(statsPeriod));c.setOnClickListener(x->{statsPeriod=v;showSection(STATS,false);});row.addView(c,chipWeight());}return row;}
    private void showStatsDetail(String type){currentSection=STATS;inSubpage=true;headerSection.setText("Estadísticas · "+type);rebuildNav();LinearLayout p=page();p.addView(backLink("Estadísticas",()->showSection(STATS,true)));p.addView(V5Ui.kicker(this,type.toUpperCase(Locale.ROOT)));TextView t=V5Ui.title(this,type);t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,12));p.addView(t);if("Reservas".equals(type)){JSONArray a=filterReservations(reservations,"HOY");int interior=0,terrace=0,people=0;for(int i=0;i<a.length();i++){JSONObject r=a.optJSONObject(i);if(r==null)continue;people+=r.optInt("people",0);if("Terraza".equalsIgnoreCase(r.optString("zone","")))terrace++;else interior++;}p.addView(bigStat("Reservas hoy",String.valueOf(a.length()),"Personas · "+people));p.addView(bigStat("Distribución","Interior "+interior+" · Terraza "+terrace,"Datos disponibles actualmente"),top(V5Ui.dp(this,8)));}else if("Promociones".equals(type)){int plays=0,winners=0;for(int i=0;i<campaigns.length();i++){JSONObject s=campaigns.optJSONObject(i)==null?null:campaigns.optJSONObject(i).optJSONObject("stats");if(s!=null){plays+=s.optInt("plays",0);winners+=s.optInt("winners",0);}}p.addView(bigStat("Campañas activas",String.valueOf(activeCampaignCount()),plays+" jugadas · "+winners+" ganadores"));}else{p.addView(bigStat(type,"—","La recogida de esta analítica se activará en la fase correspondiente."));}swapContent(scrollPage(p),true);}
    private View bigStat(String label,String value,String note){LinearLayout c=V5Ui.darkCard(this);TextView k=V5Ui.kicker(this,label.toUpperCase(Locale.ROOT));k.setTextColor(Color.rgb(192,204,194));c.addView(k);c.addView(V5Ui.text(this,value,31,Color.WHITE,true));c.addView(V5Ui.text(this,note,11,Color.rgb(197,207,198),false));return c;}

    // GESTIÓN
    private View buildManagement(){LinearLayout p=page();p.addView(V5Ui.kicker(this,"GESTIÓN"));TextView t=V5Ui.title(this,"Contenido y recursos");t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,4));p.addView(t);p.addView(V5Ui.subtitle(this,"Herramientas del mesón agrupadas por trabajo."));p.addView(sectionLabel("CONTENIDO"));p.addView(V5Ui.linkCard(this,R.drawable.ic_grid_v5,"Web","Carta, menú, avisos, popup y horarios",this::showWebManagementPage));p.addView(sectionLabel("IMPRESIÓN"));p.addView(V5Ui.linkCard(this,R.drawable.ic_print_v5,"Crear ticket","Impresión libre directa desde la APK",this::showFreePrintPage));p.addView(V5Ui.linkCard(this,R.drawable.ic_qr_v5,"Recursos","QR, plantillas e historial",this::showResourcesPage),top(V5Ui.dp(this,7)));return scrollPage(p);}
    private void showWebManagementPage(){currentSection=MANAGEMENT;inSubpage=true;headerSection.setText("Gestión · Web");rebuildNav();LinearLayout p=page();p.addView(backLink("Gestión",()->showSection(MANAGEMENT,true)));p.addView(V5Ui.kicker(this,"WEB"));TextView t=V5Ui.title(this,"Contenido público");t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,5));p.addView(t);p.addView(V5Ui.subtitle(this,"La navegación v5 ya es interna. Los editores de contenido se migrarán sin volver a la interfaz antigua."));String[] names={"Carta","Menú del día","Avisos","Popup","Horarios","Redes sociales","Textos legales"};for(String n:names)p.addView(V5Ui.linkCard(this,R.drawable.ic_grid_v5,n,"Disponible en la siguiente migración del editor",()->showInfoSubpage("Web · "+n,"Este editor se integrará aquí manteniendo la misma navegación y sin abrir la interfaz antigua.")),top(V5Ui.dp(this,7)));swapContent(scrollPage(p),true);}
    private void showResourcesPage(){currentSection=MANAGEMENT;inSubpage=true;headerSection.setText("Gestión · Recursos");rebuildNav();LinearLayout p=page();p.addView(backLink("Gestión",()->showSection(MANAGEMENT,true)));p.addView(V5Ui.kicker(this,"RECURSOS"));TextView t=V5Ui.title(this,"QR y plantillas");t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,12));p.addView(t);p.addView(V5Ui.linkCard(this,R.drawable.ic_qr_v5,"QR","Generar e imprimir QR",this::showGenericQrPage));p.addView(V5Ui.linkCard(this,R.drawable.ic_grid_v5,"Plantillas",templates.length()+" guardadas",this::showTemplatesPage),top(V5Ui.dp(this,7)));p.addView(V5Ui.linkCard(this,R.drawable.ic_calendar_v5,"Historial",history.length()+" registros locales",this::showHistoryPage),top(V5Ui.dp(this,7)));swapContent(scrollPage(p),true);}
    private void showGenericQrPage(){currentSection=MANAGEMENT;inSubpage=true;headerSection.setText("Gestión · QR");rebuildNav();LinearLayout p=page();p.addView(backLink("Recursos",this::showResourcesPage));p.addView(V5Ui.kicker(this,"QR"));p.addView(V5Ui.title(this,"Crear QR"));EditText title=field(p,"Título","MESÓN O FARO",InputType.TYPE_CLASS_TEXT);EditText text=field(p,"Texto","ESCANEA EL CÓDIGO",InputType.TYPE_CLASS_TEXT);EditText data=field(p,"Contenido del QR","https://mesonofaro.es",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);p.addView(action("Imprimir QR",true,()->io.execute(()->{try{core.printQrTicket(value(title),value(text),value(data));runOnUiThread(()->toast("QR enviado a impresora"));}catch(Exception e){runOnUiThread(()->alert("No se pudo imprimir",msg(e)));}})),top(V5Ui.dp(this,12)));swapContent(scrollPage(p),true);}
    private void showTemplatesPage(){currentSection=MANAGEMENT;inSubpage=true;headerSection.setText("Gestión · Plantillas");rebuildNav();LinearLayout p=page();p.addView(backLink("Recursos",this::showResourcesPage));p.addView(V5Ui.kicker(this,"PLANTILLAS"));TextView t=V5Ui.title(this,"Biblioteca de tickets");t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,4));p.addView(t);p.addView(V5Ui.subtitle(this,"Sistema y personalizadas. Crear, eliminar, exportar y predeterminadas se implementarán sobre esta biblioteca."));if(templates.length()==0){LinearLayout e=V5Ui.softCard(this);e.addView(V5Ui.text(this,"No hay plantillas cargadas todavía.",12,V5Ui.MUTED,false));p.addView(e,top(V5Ui.dp(this,10)));}for(int i=0;i<templates.length();i++){JSONObject x=templates.optJSONObject(i);if(x==null)continue;String name=x.optString("name",x.optString("templateId","Plantilla"));LinearLayout c=V5Ui.card(this);c.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,18));c.addView(V5Ui.text(this,name,14,V5Ui.INK,true));c.addView(V5Ui.text(this,x.optString("type","Plantilla guardada"),10.5f,V5Ui.MUTED,false));p.addView(c,top(V5Ui.dp(this,7)));}swapContent(scrollPage(p),true);refreshTemplates();}
    private void showHistoryPage(){currentSection=MANAGEMENT;inSubpage=true;headerSection.setText("Gestión · Historial");rebuildNav();LinearLayout p=page();p.addView(backLink("Recursos",this::showResourcesPage));p.addView(V5Ui.kicker(this,"HISTORIAL"));p.addView(V5Ui.title(this,"Últimas impresiones"));if(history.length()==0){LinearLayout e=V5Ui.softCard(this);e.addView(V5Ui.text(this,"No hay historial cargado.",12,V5Ui.MUTED,false));p.addView(e,top(V5Ui.dp(this,10)));}for(int i=0;i<history.length()&&i<50;i++){JSONObject h=history.optJSONObject(i);if(h==null)continue;LinearLayout c=V5Ui.card(this);c.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,18));c.addView(V5Ui.text(this,h.optString("type",h.optString("tipo","Impresión")),13.5f,V5Ui.INK,true));c.addView(V5Ui.text(this,h.optString("createdAt",h.optString("fecha",""))+" · "+h.optString("detail",h.optString("detalle","")),10.5f,V5Ui.MUTED,false));p.addView(c,top(V5Ui.dp(this,7)));}swapContent(scrollPage(p),true);refreshHistory();}
    private void showFreePrintPage(){currentSection=MANAGEMENT;inSubpage=true;headerSection.setText("Gestión · Imprimir");rebuildNav();LinearLayout p=page();p.addView(backLink("Gestión",()->showSection(MANAGEMENT,true)));p.addView(V5Ui.kicker(this,"IMPRESIÓN"));TextView t=V5Ui.title(this,"Ticket libre");t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,10));p.addView(t);EditText title=field(p,"Título","MESÓN O FARO",InputType.TYPE_CLASS_TEXT);EditText body=multi(p,"Texto","");EditText qr=field(p,"QR · opcional","",InputType.TYPE_CLASS_TEXT);p.addView(action("Imprimir",true,()->io.execute(()->{try{core.printFreeText(value(title),value(body),value(qr));runOnUiThread(()->toast("Ticket enviado a impresora"));}catch(Exception e){runOnUiThread(()->alert("No se pudo imprimir",msg(e)));}})),top(V5Ui.dp(this,12)));swapContent(scrollPage(p),true);}

    // CONFIGURACIÓN
    private View buildSettings(){LinearLayout p=page();p.addView(V5Ui.kicker(this,"CONFIGURACIÓN"));TextView t=V5Ui.title(this,"Sistema y dispositivo");t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,4));p.addView(t);p.addView(V5Ui.subtitle(this,"Todo lo técnico, separado del trabajo diario."));p.addView(sectionLabel("SISTEMA"));p.addView(V5Ui.linkCard(this,R.drawable.ic_print_v5,"Impresora",printerSummary(),this::showPrinterSettingsPage));p.addView(V5Ui.linkCard(this,R.drawable.ic_settings_v5,"Terminal",core.terminal(),this::showTerminalPage),top(V5Ui.dp(this,7)));p.addView(V5Ui.linkCard(this,R.drawable.ic_chart_v5,"Conexión",core.configured()?"Acceso configurado":"Falta clave de acceso",this::showConnectionPage),top(V5Ui.dp(this,7)));p.addView(V5Ui.linkCard(this,R.drawable.ic_settings_v5,"Diagnóstico","Estado de backend, caché e impresora",this::showDiagnosticsPage),top(V5Ui.dp(this,7)));p.addView(sectionLabel("APLICACIÓN"));p.addView(V5Ui.linkCard(this,R.drawable.ic_settings_v5,"Preferencias","Sonidos, vibración y confirmaciones",this::showPreferencesPage));p.addView(V5Ui.linkCard(this,R.drawable.ic_grid_v5,"Información","O Faro Gestión · v"+BuildConfig.VERSION_NAME,this::showInfoPage),top(V5Ui.dp(this,7)));return scrollPage(p);}
    private void showPrinterSettingsPage(){currentSection=SETTINGS;inSubpage=true;headerSection.setText("Configuración · Impresora");rebuildNav();LinearLayout p=page();p.addView(backLink("Configuración",()->showSection(SETTINGS,true)));p.addView(V5Ui.kicker(this,"IMPRESORA"));p.addView(V5Ui.title(this,"Conexión ESC/POS"));EditText ip=field(p,"IP",core.printerIp(),InputType.TYPE_CLASS_PHONE);EditText port=field(p,"Puerto",String.valueOf(core.printerPort()),InputType.TYPE_CLASS_NUMBER);Spinner paper=spinner(p,"Papel",new String[]{"58 mm","80 mm"},core.printerPaper()<=58?0:1);Spinner cut=spinner(p,"Corte",new String[]{"Completo","Parcial","Sin corte"},"partial".equals(core.printerCut())?1:"none".equals(core.printerCut())?2:0);EditText feed=field(p,"Avance de papel",String.valueOf(core.printerFeed()),InputType.TYPE_CLASS_NUMBER);EditText dark=field(p,"Oscuridad",String.valueOf(core.printerDarkness()),InputType.TYPE_CLASS_NUMBER);p.addView(action("Guardar y reconectar",true,()->{core.prefs().edit().putString("printerIp",value(ip)).putInt("printerPort",parse(value(port),9100)).putInt("printerPaper",paper.getSelectedItemPosition()==0?58:80).putString("printerCut",cut.getSelectedItemPosition()==1?"partial":cut.getSelectedItemPosition()==2?"none":"full").putInt("printerFeed",parse(value(feed),3)).putInt("printerDarkness",parse(value(dark),180)).apply();core.reconnectPrinter();refreshPrinter();toast("Impresora guardada");}),top(V5Ui.dp(this,12)));p.addView(action("Imprimir prueba",false,()->io.execute(()->{try{core.printTest(value(ip),parse(value(port),9100));runOnUiThread(()->toast("Prueba enviada"));}catch(Exception e){runOnUiThread(()->alert("Error de impresión",msg(e)));}})),top(V5Ui.dp(this,7)));swapContent(scrollPage(p),true);}
    private void showTerminalPage(){currentSection=SETTINGS;inSubpage=true;headerSection.setText("Configuración · Terminal");rebuildNav();LinearLayout p=page();p.addView(backLink("Configuración",()->showSection(SETTINGS,true)));p.addView(V5Ui.kicker(this,"TERMINAL"));p.addView(V5Ui.title(this,"Identidad del dispositivo"));EditText name=field(p,"Nombre",core.terminal(),InputType.TYPE_CLASS_TEXT);EditText location=field(p,"Ubicación",core.prefs().getString("terminalLocation","Barra"),InputType.TYPE_CLASS_TEXT);EditText id=field(p,"ID",core.prefs().getString("terminalId","OFARO-01"),InputType.TYPE_CLASS_TEXT);p.addView(action("Guardar terminal",true,()->{core.prefs().edit().putString("terminal",value(name)).putString("terminalLocation",value(location)).putString("terminalId",value(id)).apply();toast("Terminal actualizado");}),top(V5Ui.dp(this,12)));swapContent(scrollPage(p),true);}
    private void showConnectionPage(){currentSection=SETTINGS;inSubpage=true;headerSection.setText("Configuración · Conexión");rebuildNav();LinearLayout p=page();p.addView(backLink("Configuración",()->showSection(SETTINGS,true)));p.addView(V5Ui.kicker(this,"CONEXIÓN"));p.addView(V5Ui.title(this,"Servidor"));LinearLayout endpoint=V5Ui.darkCard(this);endpoint.addView(V5Ui.text(this,"ENDPOINT PRODUCCIÓN",9.5f,V5Ui.LIME,true));endpoint.addView(V5Ui.text(this,core.api(),10.5f,Color.WHITE,false));p.addView(endpoint,top(V5Ui.dp(this,10)));EditText key=field(p,"Clave de acceso",core.key(),InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);p.addView(action("Guardar acceso",true,()->{core.prefs().edit().putString("key",value(key)).apply();toast("Acceso guardado");}),top(V5Ui.dp(this,10)));p.addView(action("Probar servidor",false,this::pingServer),top(V5Ui.dp(this,7)));swapContent(scrollPage(p),true);}
    private void showDiagnosticsPage(){currentSection=SETTINGS;inSubpage=true;headerSection.setText("Configuración · Diagnóstico");rebuildNav();LinearLayout p=page();p.addView(backLink("Configuración",()->showSection(SETTINGS,true)));p.addView(V5Ui.kicker(this,"DIAGNÓSTICO"));p.addView(V5Ui.title(this,"Estado del sistema"));p.addView(bigStat("Internet",core.internetAvailable()?"OK":"Sin conexión","Servidor "+(core.configured()?"configurado":"sin clave")),top(V5Ui.dp(this,10)));p.addView(V5Ui.linkCard(this,R.drawable.ic_print_v5,"Impresora",printerSummary(),()->{core.reconnectPrinter();toast("Reconexión solicitada");}),top(V5Ui.dp(this,8)));p.addView(V5Ui.linkCard(this,R.drawable.ic_grid_v5,"Caché",reservations.length()+" reservas · "+campaigns.length()+" campañas · "+templates.length()+" plantillas",this::refreshAll),top(V5Ui.dp(this,7)));p.addView(action("Probar backend",true,this::pingServer),top(V5Ui.dp(this,10)));swapContent(scrollPage(p),true);}
    private void showPreferencesPage(){currentSection=SETTINGS;inSubpage=true;headerSection.setText("Configuración · Preferencias");rebuildNav();LinearLayout p=page();p.addView(backLink("Configuración",()->showSection(SETTINGS,true)));p.addView(V5Ui.kicker(this,"APLICACIÓN"));p.addView(V5Ui.title(this,"Preferencias"));CheckBox sounds=check("Sonidos",core.prefs().getBoolean("sounds",true));CheckBox vibration=check("Vibración",core.prefs().getBoolean("vibration",true));CheckBox redeem=check("Confirmar antes de canjear",core.prefs().getBoolean("confirmRedeem",true));CheckBox delete=check("Confirmar antes de eliminar",core.prefs().getBoolean("confirmDelete",true));p.addView(sounds,top(V5Ui.dp(this,12)));p.addView(vibration);p.addView(redeem);p.addView(delete);p.addView(action("Guardar preferencias",true,()->{core.prefs().edit().putBoolean("sounds",sounds.isChecked()).putBoolean("vibration",vibration.isChecked()).putBoolean("confirmRedeem",redeem.isChecked()).putBoolean("confirmDelete",delete.isChecked()).apply();toast("Preferencias guardadas");}),top(V5Ui.dp(this,10)));swapContent(scrollPage(p),true);}
    private void showInfoPage(){showInfoSubpage("O Faro Gestión","Versión "+BuildConfig.VERSION_NAME+"\nPackage: com.ofaro.participaciones\nTerminal: "+core.terminal()+"\nAndroid: "+Build.VERSION.RELEASE+"\n\nRediseño v5 · shell de navegación única.");}
    private void showInfoSubpage(String title,String text){inSubpage=true;LinearLayout p=page();p.addView(backLink(SECTION_NAMES[currentSection],()->showSection(currentSection,true)));p.addView(V5Ui.kicker(this,"INFORMACIÓN"));TextView t=V5Ui.title(this,title);t.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,10));p.addView(t);LinearLayout c=V5Ui.softCard(this);c.addView(V5Ui.text(this,text,12,V5Ui.INK,false));p.addView(c);swapContent(scrollPage(p),true);}

    // RED / CACHÉ
    private void refreshAll(){refreshReservations(false);refreshPromotions(false);refreshTemplates();refreshHistory();}
    private void refreshReservations(boolean quiet){if(!core.configured())return;io.execute(()->{try{JSONObject r=core.post(core.action("reservationList").put("limit",500).put("includeClosed",true));JSONArray a=r.optJSONArray("items");if(a==null)a=new JSONArray();reservations=a;core.saveArray("reservations_all_v5",a);core.saveArray("reservations_HOY",filterReservations(a,"HOY"));if(!quiet)runOnUiThread(()->{if(currentSection==HOME&&!inSubpage)showSection(HOME,false);else if(currentSection==RESERVATIONS&&!inSubpage)showSection(RESERVATIONS,false);});}catch(Exception ignored){}});}
    private void refreshPromotions(boolean quiet){if(!core.configured())return;io.execute(()->{try{JSONObject r=core.post(core.action("promotionList"));JSONArray a=r.optJSONArray("items");if(a==null)a=r.optJSONArray("campaigns");if(a==null)a=new JSONArray();campaigns=a;core.saveArray("promo_campaigns",a);JSONObject pr=core.post(core.action("promotionPrizeList"));JSONArray pp=pr.optJSONArray("items");if(pp==null)pp=new JSONArray();prizes=pp;core.saveArray("promo_prizes",pp);if(!quiet)runOnUiThread(()->{if(currentSection==HOME&&!inSubpage)showSection(HOME,false);else if(currentSection==PROMOTIONS&&!inSubpage)showSection(PROMOTIONS,false);});}catch(Exception ignored){}});}
    private void refreshTemplates(){if(!core.configured())return;io.execute(()->{try{JSONObject r=core.post(core.action("templateList"));JSONArray a=r.optJSONArray("items");if(a==null)a=new JSONArray();templates=a;core.saveArray("templates_v5",a);}catch(Exception ignored){}});}
    private void refreshHistory(){if(!core.configured())return;io.execute(()->{try{JSONObject r=core.post(core.action("historyList").put("limit",100));JSONArray a=r.optJSONArray("items");if(a==null)a=new JSONArray();history=a;core.saveArray("history_v5",a);}catch(Exception ignored){}});}
    private void pingServer(){if(!core.configured()){alert("Falta clave","Introduce la clave de acceso antes de probar.");return;}io.execute(()->{try{core.post(core.action("appPing"));runOnUiThread(()->toast("Servidor online"));}catch(Exception e){runOnUiThread(()->alert("Servidor no disponible",msg(e)));}});}

    // HELPERS
    private void quickActions(){String[] items={"Nueva reserva","Generar QR promocional","Canjear premio","Imprimir ticket"};new AlertDialog.Builder(this).setTitle("Acción rápida").setItems(items,(d,w)->{if(w==0)showNewReservation();else if(w==1)showQrGenerator();else if(w==2)showRedeemPage();else showFreePrintPage();}).show();}
    private void refreshPrinter(){V5Ui.updatePrinter(printerState,core);}
    private int activeCampaignCount(){int n=0;for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c!=null&&c.optBoolean("active",false))n++;}return n;}
    private int prizeCount(){int n=0;for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p!=null&&!"P000".equals(p.optString("id")))n++;}return n;}
    private String remaining(JSONObject p){Object x=p.opt("remaining");if(x==null||x==JSONObject.NULL||String.valueOf(x).trim().isEmpty())return"sin límite";return String.valueOf(x);}
    private String scheduleSummary(JSONObject c){String sd=c.optString("startDate","").trim(),ed=c.optString("endDate","").trim(),st=c.optString("startTime","00:00"),et=c.optString("endTime","23:59");String date=sd.isEmpty()&&ed.isEmpty()?"Sin límite de fechas":sd.isEmpty()?"Hasta "+ed:ed.isEmpty()?"Desde "+sd:sd+" → "+ed;return date+" · "+st+"–"+et;}
    private String printerSummary(){if(core.printerIp().isEmpty())return"Sin IP configurada";return(core.printerConnected()?"Conectada · ":"Reconectando · ")+core.printerIp()+":"+core.printerPort();}
    private TextView chip(String text,boolean on){TextView c=V5Ui.text(this,text,9,on?Color.WHITE:V5Ui.MUTED,true);c.setGravity(Gravity.CENTER);c.setBackground(V5Ui.bg(this,on?V5Ui.GREEN:V5Ui.SURFACE_ALT,15));return c;}
    private LinearLayout.LayoutParams chipWeight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,V5Ui.dp(this,36),1);p.setMargins(V5Ui.dp(this,3),0,V5Ui.dp(this,3),0);return p;}
    private TextView sectionLabel(String v){TextView t=V5Ui.kicker(this,v);t.setPadding(V5Ui.dp(this,1),V5Ui.dp(this,17),0,V5Ui.dp(this,8));return t;}
    private TextView backLink(String label,Runnable r){TextView t=V5Ui.text(this,"‹  "+label,11.5f,V5Ui.GREEN,true);t.setPadding(0,V5Ui.dp(this,3),0,V5Ui.dp(this,13));t.setOnClickListener(v->r.run());return t;}
    private TextView action(String label,boolean primary,Runnable r){TextView t=V5Ui.text(this,label,12,primary?Color.WHITE:V5Ui.GREEN,true);t.setGravity(Gravity.CENTER);t.setPadding(V5Ui.dp(this,10),0,V5Ui.dp(this,10),0);t.setBackground(V5Ui.bg(this,primary?V5Ui.GREEN:V5Ui.SURFACE_ALT,16));if(r!=null)t.setOnClickListener(v->r.run());t.setMinHeight(V5Ui.dp(this,44));return t;}
    private View bigStat(String label,String value,String note,boolean unused){return bigStat(label,value,note);}
    private EditText field(LinearLayout parent,String label,String value,int type){parent.addView(fieldLabel(label));EditText e=input(value);e.setInputType(type);e.setSingleLine(true);parent.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,V5Ui.dp(this,47)));return e;}
    private EditText multi(LinearLayout parent,String label,String value){parent.addView(fieldLabel(label));EditText e=input(value);e.setSingleLine(false);e.setMinLines(3);e.setGravity(Gravity.TOP);e.setPadding(V5Ui.dp(this,12),V5Ui.dp(this,10),V5Ui.dp(this,12),V5Ui.dp(this,10));parent.addView(e);return e;}
    private EditText picker(LinearLayout parent,String label,String value,boolean date){parent.addView(fieldLabel(label));EditText e=input(value);e.setFocusable(false);e.setClickable(true);e.setOnClickListener(v->{if(date)showDatePicker(e);else showTimePicker(e);});parent.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,V5Ui.dp(this,47)));return e;}
    private Spinner zoneSpinner(LinearLayout parent,String current){return spinner(parent,"Zona",new String[]{"Interior","Terraza"},"Terraza".equalsIgnoreCase(current)?1:0);}
    private Spinner spinner(LinearLayout parent,String label,String[] items,int selected){parent.addView(fieldLabel(label));Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,items);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(a);s.setSelection(Math.max(0,Math.min(selected,items.length-1)));s.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,14));parent.addView(s,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,V5Ui.dp(this,47)));return s;}
    private TextView fieldLabel(String value){TextView t=V5Ui.text(this,value,10.5f,V5Ui.MUTED,true);t.setPadding(V5Ui.dp(this,1),V5Ui.dp(this,10),0,V5Ui.dp(this,5));return t;}
    private EditText input(String value){EditText e=new EditText(this);e.setText(value);e.setTextSize(13.5f);e.setTextColor(V5Ui.INK);e.setHintTextColor(V5Ui.FAINT);e.setPadding(V5Ui.dp(this,12),0,V5Ui.dp(this,12),0);e.setBackground(V5Ui.bg(this,V5Ui.SURFACE_ALT,14));return e;}
    private EditText dialogField(LinearLayout parent,String label,String value){parent.addView(dialogLabel(label));EditText e=input(value);parent.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,V5Ui.dp(this,46)));return e;}
    private TextView dialogLabel(String value){TextView t=V5Ui.text(this,value,10.5f,V5Ui.MUTED,true);t.setPadding(0,V5Ui.dp(this,8),0,V5Ui.dp(this,4));return t;}
    private CheckBox check(String text,boolean value){CheckBox c=new CheckBox(this);c.setText(text);c.setTextSize(13);c.setTextColor(V5Ui.INK);c.setChecked(value);c.setMinHeight(V5Ui.dp(this,44));return c;}
    private void showDatePicker(EditText target){LocalDate initial;try{initial=LocalDate.parse(value(target));}catch(Exception e){initial=LocalDate.now();}new DatePickerDialog(this,(v,y,m,d)->target.setText(String.format(Locale.ROOT,"%04d-%02d-%02d",y,m+1,d)),initial.getYear(),initial.getMonthValue()-1,initial.getDayOfMonth()).show();}
    private void showTimePicker(EditText target){int h=14,m=0;try{String[] p=value(target).split(":");h=Integer.parseInt(p[0]);m=Integer.parseInt(p[1]);}catch(Exception ignored){}new TimePickerDialog(this,(v,hh,mm)->target.setText(String.format(Locale.ROOT,"%02d:%02d",hh,mm)),h,m,true).show();}
    private void dial(String p){if(p==null||p.trim().isEmpty()){toast("No hay teléfono");return;}startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+p.trim())));overridePendingTransition(0,0);}
    private void whatsapp(String p){if(p==null||p.trim().isEmpty()){toast("No hay teléfono");return;}String c=p.replaceAll("[^0-9]","");if(c.length()==9)c="34"+c;try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+c)));}catch(Exception e){alert("WhatsApp",msg(e));}}
    private void copy(String value){ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm!=null){cm.setPrimaryClip(ClipData.newPlainText("O Faro",value));toast("Copiado");}}
    private void requestNotificationOnce(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED&&!core.prefs().getBoolean("askedNotifications",false)){core.prefs().edit().putBoolean("askedNotifications",true).apply();requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},501);}}
    private String currentDate(){String raw=LocalDate.now().format(DateTimeFormatter.ofPattern("EEEE, d 'de' MMMM",new Locale("es","ES")));return raw.isEmpty()?raw:Character.toUpperCase(raw.charAt(0))+raw.substring(1);}
    private String greeting(){int h=LocalTime.now().getHour();return h<13?"Buenos días":h<20?"Buenas tardes":"Buenas noches";}
    private String labelMode(String s){if("PRÓXIMAS".equals(s))return"Próximas";if("PENDIENTES".equals(s))return"Pendientes";if("HISTÓRICO".equals(s))return"Histórico";if("RESUMEN".equals(s))return"Resumen";if("CAMPAÑAS".equals(s))return"Campañas";if("PREMIOS".equals(s))return"Premios";if("CANJES".equals(s))return"Canjes";return"Hoy";}
    private LinearLayout.LayoutParams weightGap(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1);p.setMargins(V5Ui.dp(this,3),0,V5Ui.dp(this,3),0);return p;}
    private LinearLayout.LayoutParams top(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=v;return p;}
    private LinearLayout.LayoutParams bottom(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=v;return p;}
    private String value(EditText e){return e==null?"":e.getText().toString().trim();}
    private int parse(String s,int fallback){try{return Integer.parseInt(s.trim());}catch(Exception e){return fallback;}}
    private String dash(String s){return s==null||s.trim().isEmpty()?"—":s.trim();}
    private String msg(Throwable t){String m=t==null?"Error desconocido":t.getMessage();return m==null||m.trim().isEmpty()?String.valueOf(t):m;}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void alert(String t,String m){if(!isFinishing())new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Aceptar",null).show();}
}
