package com.ofaro.participaciones;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.time.LocalDate;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ManagementActivityV3 extends Activity {
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private AppCore core;
    private LinearLayout page;
    private TextView subtitle;

    @Override protected void onCreate(Bundle b){super.onCreate(b);core=new AppCore(this);setContentView(buildRoot());showHome();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}

    private View buildRoot(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(246,246,246));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(20),dp(18),dp(20),dp(16));head.setBackgroundColor(Color.rgb(17,17,17));head.addView(text("MESÓN O FARO",23,Color.WHITE,true));subtitle=text("Gestión e impresión",14,Color.rgb(210,210,210),false);head.addView(subtitle);root.addView(head);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(18),dp(20),dp(18),dp(30));scroll.addView(page);root.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));return root;
    }

    private void showHome(){
        clear("Gestión e impresión");page.addView(sectionTitle("¿Qué quieres hacer?"));page.addView(paragraph("Previsualiza todos los tickets antes de imprimir y gestiona la web y las reservas desde el mismo sitio."));
        Button reservations=bigButton("RESERVAS","Confirmar, denegar, editar, servicio e impresión");reservations.setOnClickListener(v->showReservations("HOY"));page.addView(reservations);
        LinearLayout r1=row();Button part=tileButton("PARTICIPACIONES");part.setOnClickListener(v->startActivity(new Intent(this,ParticipationActivityV3.class)));Button qr=tileButton("QR RÁPIDOS");qr.setOnClickListener(v->showQr());r1.addView(part,weight());r1.addView(qr,weight());page.addView(r1,marginTopWrap(dp(10)));
        LinearLayout r2=row();Button templates=tileButton("PLANTILLAS");templates.setOnClickListener(v->showTemplates());Button free=tileButton("IMPRESIÓN LIBRE");free.setOnClickListener(v->showFreePrint());r2.addView(templates,weight());r2.addView(free,weight());page.addView(r2,marginTopWrap(dp(10)));
        LinearLayout r3=row();Button web=tileButton("GESTIÓN WEB");web.setOnClickListener(v->startActivity(new Intent(this,WebManagementActivity.class)));Button image=tileButton("IMPRIMIR IMAGEN");image.setOnClickListener(v->openTicket("","","","","Imagen","","Imagen libre","",""));r3.addView(web,weight());r3.addView(image,weight());page.addView(r3,marginTopWrap(dp(10)));
        LinearLayout r4=row();Button history=tileButton("HISTORIAL");history.setOnClickListener(v->showHistory());Button settings=tileButton("AJUSTES");settings.setOnClickListener(v->showSettings());r4.addView(history,weight());r4.addView(settings,weight());page.addView(r4,marginTopWrap(dp(10)));
        TextView status=text(core.configured()?"API configurada · "+core.terminal():"Falta configurar la API interna",13,Color.DKGRAY,false);status.setPadding(dp(4),dp(20),dp(4),0);page.addView(status);
    }

    private void showReservations(String mode){
        clear("Reservas");addBack("Reservas");
        LinearLayout filters=row();String[] modes={"HOY","PENDIENTES","ACTIVAS","HISTÓRICO"};for(String m:modes){Button b=miniButton(m);b.setEnabled(!m.equals(mode));b.setOnClickListener(v->showReservations(m));filters.addView(b,weight());}page.addView(filters);
        TextView summary=text("Cargando reservas…",15,Color.DKGRAY,false);summary.setPadding(0,dp(12),0,dp(8));page.addView(summary);
        Button create=primaryButton("NUEVA RESERVA");create.setOnClickListener(v->showNewReservation());page.addView(create);
        LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);page.addView(list,marginTopWrap(dp(14)));
        if(!requireApi())return;
        io.execute(()->{
            try{
                JSONObject req=core.action("reservationList").put("limit",250);if("HOY".equals(mode))req.put("date",LocalDate.now().toString());if("HISTÓRICO".equals(mode))req.put("includeClosed",true);
                JSONObject res=core.post(req);core.ensureOk(res);JSONArray raw=res.optJSONArray("items");JSONArray items=new JSONArray();int people=0;
                if(raw!=null)for(int i=0;i<raw.length();i++){JSONObject x=raw.optJSONObject(i);if(x==null)continue;if("PENDIENTES".equals(mode)&&!"Pendiente".equalsIgnoreCase(x.optString("state","")))continue;items.put(x);people+=x.optInt("people",0);}
                int totalPeople=people;runOnUiThread(()->{int n=items.length();summary.setText(mode+" · "+n+(n==1?" reserva":" reservas")+" · "+totalPeople+" personas");list.removeAllViews();if(n==0)list.addView(emptyText("No hay reservas en este filtro."));else for(int i=0;i<n;i++)addReservationCard(list,items.optJSONObject(i));});
            }catch(Exception e){runOnUiThread(()->summary.setText("Error: "+cleanError(e)));}
        });
    }

    private void addReservationCard(LinearLayout list,JSONObject r){
        LinearLayout card=cardBox();card.addView(text(r.optString("date","")+" · "+r.optString("time","--:--")+" · "+r.optString("name",""),18,Color.rgb(20,20,20),true));
        String line=r.optInt("people",0)+" personas";if(!r.optString("table","").isEmpty())line+=" · Mesa "+r.optString("table");if(!r.optString("zone","").isEmpty()&&!"Sin asignar".equalsIgnoreCase(r.optString("zone")))line+=" · "+r.optString("zone");card.addView(text(line,14,Color.DKGRAY,false));
        TextView state=text("Reserva: "+value(r.optString("state","Pendiente"))+" · Servicio: "+value(r.optString("serviceState","Pendiente")),13,Color.DKGRAY,false);state.setPadding(0,dp(6),0,dp(9));card.addView(state);
        LinearLayout a=row();Button preview=miniButton("PREVISUALIZAR");preview.setOnClickListener(v->openReservationPreview(r));Button more=miniButton("GESTIONAR");more.setOnClickListener(v->showReservationDetails(r));a.addView(preview,weight());a.addView(more,weight());card.addView(a);list.addView(card,marginBottomWrap(dp(10)));
    }

    private void showReservationDetails(JSONObject r){
        clear("Reserva");addBackTo("Reserva · "+r.optString("name",""),()->showReservations("HOY"));
        page.addView(info("Fecha / hora",r.optString("date","")+" · "+r.optString("time","")));page.addView(info("Personas",String.valueOf(r.optInt("people",0))));page.addView(info("Teléfono",r.optString("phone","—")));page.addView(info("Correo",r.optString("email","—")));page.addView(info("Mesa / zona",value(r.optString("table","—"))+" · "+value(r.optString("zone","Sin asignar"))));page.addView(info("Observaciones",value(r.optString("notes","—"))));page.addView(info("Estado reserva",value(r.optString("state","Pendiente"))));page.addView(info("Estado servicio",value(r.optString("serviceState","Pendiente"))));page.addView(info("Correo cliente",value(r.optString("customerEmailState","Pendiente"))));
        Button preview=primaryButton("PREVISUALIZAR / IMPRIMIR");preview.setOnClickListener(v->openReservationPreview(r));page.addView(preview,marginTop(dp(14)));
        Button edit=secondaryButton("EDITAR DATOS, MESA Y ZONA");edit.setOnClickListener(v->showEditReservation(r));page.addView(edit,marginTop(dp(10)));
        LinearLayout contact=row();Button call=miniButton("LLAMAR");call.setOnClickListener(v->dial(r.optString("phone","")));Button wa=miniButton("WHATSAPP");wa.setOnClickListener(v->whatsapp(r.optString("phone","")));contact.addView(call,weight());contact.addView(wa,weight());page.addView(contact,marginTopWrap(dp(10)));
        page.addView(label("ESTADO DE LA RESERVA"));
        LinearLayout d1=row();Button confirm=miniButton("CONFIRMAR");confirm.setOnClickListener(v->askDecision(r,"Confirmada"));Button deny=miniButton("DENEGAR");deny.setOnClickListener(v->askDecision(r,"Denegada"));d1.addView(confirm,weight());d1.addView(deny,weight());page.addView(d1);
        LinearLayout d2=row();Button pending=miniButton("PENDIENTE");pending.setOnClickListener(v->reservationAction(r,"Pendiente","",false,false));Button cancel=miniButton("CANCELAR");cancel.setOnClickListener(v->reservationAction(r,"Cancelada","",false,false));d2.addView(pending,weight());d2.addView(cancel,weight());page.addView(d2,marginTopWrap(dp(8)));
        String state=r.optString("state","");if(("Confirmada".equalsIgnoreCase(state)||"Denegada".equalsIgnoreCase(state))&&!r.optString("email","").isEmpty()){Button resend=secondaryButton("REENVIAR CORREO AL CLIENTE");resend.setOnClickListener(v->reservationAction(r,"Confirmada".equalsIgnoreCase(state)?"Confirmada":"Denegada","",true,true));page.addView(resend,marginTop(dp(10)));}
        page.addView(label("ESTADO DEL SERVICIO"));String[] service={"Pendiente","Llegó","Sentada","En servicio","Completada","No se presentó"};for(int i=0;i<service.length;i+=2){LinearLayout rr=row();for(int j=i;j<Math.min(i+2,service.length);j++){String s=service[j];Button b=miniButton(s.toUpperCase());b.setOnClickListener(v->reservationAction(r,"",s,false,false));rr.addView(b,weight());}page.addView(rr,marginTopWrap(dp(8)));}
    }

    private void askDecision(JSONObject r,String state){
        if(r.optString("email","").isEmpty()){new AlertDialog.Builder(this).setTitle(state).setMessage("Esta reserva no tiene correo. Se cambiará el estado sin enviar email.").setNegativeButton("Cancelar",null).setPositiveButton("CONTINUAR",(d,w)->reservationAction(r,state,"",false,false)).show();return;}
        new AlertDialog.Builder(this).setTitle(state).setMessage("¿Quieres enviar también el correo correspondiente al cliente?").setNegativeButton("Cancelar",null).setNeutralButton("SIN CORREO",(d,w)->reservationAction(r,state,"",false,false)).setPositiveButton("ENVIAR CORREO",(d,w)->reservationAction(r,state,"",true,false)).show();
    }

    private void reservationAction(JSONObject r,String state,String service,boolean sendEmail,boolean forceEmail){
        if(!requireApi())return;io.execute(()->{try{JSONObject req=core.action("reservationAction").put("id",r.optString("id","")).put("sendEmail",sendEmail).put("forceEmail",forceEmail);if(!state.isEmpty())req.put("state",state);if(!service.isEmpty())req.put("serviceState",service);JSONObject res=core.post(req);core.ensureOk(res);runOnUiThread(()->{toast("Reserva actualizada");showReservations("HOY");});}catch(Exception e){runOnUiThread(()->alert("No se pudo actualizar",cleanError(e)));}});
    }

    private void showEditReservation(JSONObject r){
        clear("Editar reserva");addBackTo("Editar reserva",()->showReservationDetails(r));
        EditText date=field("Fecha",r.optString("date",""),InputType.TYPE_CLASS_DATETIME);EditText time=field("Hora",r.optString("time",""),InputType.TYPE_CLASS_DATETIME);EditText name=field("Nombre",r.optString("name",""),InputType.TYPE_CLASS_TEXT);EditText phone=field("Teléfono",r.optString("phone",""),InputType.TYPE_CLASS_PHONE);EditText email=field("Correo",r.optString("email",""),InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);EditText people=field("Personas",String.valueOf(r.optInt("people",2)),InputType.TYPE_CLASS_NUMBER);EditText table=field("Mesa",r.optString("table",""),InputType.TYPE_CLASS_TEXT);EditText zone=field("Zona",r.optString("zone","Sin asignar"),InputType.TYPE_CLASS_TEXT);EditText notes=fieldMulti("Observaciones",r.optString("notes",""),4);
        Button save=primaryButton("GUARDAR CAMBIOS");page.addView(save,marginTop(dp(16)));save.setOnClickListener(v->{save.setEnabled(false);io.execute(()->{try{JSONObject req=core.action("reservationFullUpdate").put("id",r.optString("id","")).put("date",date.getText().toString().trim()).put("time",time.getText().toString().trim()).put("name",name.getText().toString().trim()).put("phone",phone.getText().toString().trim()).put("email",email.getText().toString().trim()).put("people",safeInt(people.getText().toString(),2,1,30)).put("table",table.getText().toString().trim()).put("zone",zone.getText().toString().trim()).put("notes",notes.getText().toString().trim());JSONObject res=core.post(req);core.ensureOk(res);runOnUiThread(()->{toast("Reserva actualizada");showReservations("HOY");});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);alert("Error",cleanError(e));});}});});
    }

    private void showNewReservation(){
        clear("Nueva reserva");addBackTo("Nueva reserva",()->showReservations("HOY"));EditText name=field("Nombre","",InputType.TYPE_CLASS_TEXT);EditText phone=field("Teléfono","",InputType.TYPE_CLASS_PHONE);EditText email=field("Correo (opcional)","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);EditText date=field("Fecha",LocalDate.now().toString(),InputType.TYPE_CLASS_DATETIME);EditText time=field("Hora","14:00",InputType.TYPE_CLASS_DATETIME);EditText people=field("Personas","2",InputType.TYPE_CLASS_NUMBER);EditText table=field("Mesa (opcional)","",InputType.TYPE_CLASS_TEXT);EditText zone=field("Zona","Sin asignar",InputType.TYPE_CLASS_TEXT);EditText notes=fieldMulti("Observaciones","",4);Button save=primaryButton("GUARDAR Y PREVISUALIZAR");page.addView(save,marginTop(dp(16)));Button saveOnly=secondaryButton("GUARDAR SIN PREVISUALIZAR");page.addView(saveOnly,marginTop(dp(10)));View.OnClickListener click=v->createReservation(name,phone,email,date,time,people,table,zone,notes,v==save,(Button)v);save.setOnClickListener(click);saveOnly.setOnClickListener(click);
    }

    private void createReservation(EditText name,EditText phone,EditText email,EditText date,EditText time,EditText people,EditText table,EditText zone,EditText notes,boolean preview,Button button){
        if(!requireApi())return;if(name.getText().toString().trim().isEmpty()||phone.getText().toString().trim().isEmpty()){alert("Faltan datos","Nombre y teléfono son obligatorios.");return;}button.setEnabled(false);io.execute(()->{try{JSONObject req=core.action("reservationCreate").put("nombre",name.getText().toString().trim()).put("telefono",phone.getText().toString().trim()).put("correo",email.getText().toString().trim()).put("fecha",date.getText().toString().trim()).put("hora",time.getText().toString().trim()).put("personas",safeInt(people.getText().toString(),2,1,30)).put("mesa",table.getText().toString().trim()).put("zona",zone.getText().toString().trim()).put("observaciones",notes.getText().toString().trim());JSONObject res=core.post(req);core.ensureOk(res);JSONObject r=new JSONObject().put("id",res.optString("id","")).put("date",date.getText().toString().trim()).put("time",time.getText().toString().trim()).put("name",name.getText().toString().trim()).put("phone",phone.getText().toString().trim()).put("email",email.getText().toString().trim()).put("people",safeInt(people.getText().toString(),2,1,30)).put("table",table.getText().toString().trim()).put("zone",zone.getText().toString().trim()).put("notes",notes.getText().toString().trim());runOnUiThread(()->{button.setEnabled(true);toast("Reserva guardada");if(preview)openReservationPreview(r);else showReservations("HOY");});}catch(Exception e){runOnUiThread(()->{button.setEnabled(true);alert("No se pudo guardar",cleanError(e));});}});
    }

    private void openReservationPreview(JSONObject r){StringBuilder b=new StringBuilder();b.append(r.optString("date","")).append("   ").append(r.optString("time","")).append("\n\n").append(r.optString("name","").toUpperCase()).append("\n").append(r.optInt("people",0)).append(" PERSONAS\n");if(!r.optString("table","").isEmpty())b.append("Mesa: ").append(r.optString("table")).append("\n");if(!r.optString("zone","").isEmpty()&&!"Sin asignar".equalsIgnoreCase(r.optString("zone")))b.append("Zona: ").append(r.optString("zone")).append("\n");if(!r.optString("phone","").isEmpty())b.append("Tel: ").append(r.optString("phone")).append("\n");if(!r.optString("notes","").isEmpty())b.append("\nOBSERVACIONES\n").append(r.optString("notes")).append("\n");b.append("\n").append(r.optString("id",""));openTicket("MESON O FARO","RESERVA",b.toString(),"","Reserva",r.optString("id",""),r.optString("name",""),r.optString("id",""),"");}

    private void showQr(){clear("QR rápidos");addBack("QR rápidos");TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);page.addView(list,marginTopWrap(dp(10)));loadList("qrList",status,items->{status.setText(items.length()+" accesos");list.removeAllViews();for(int i=0;i<items.length();i++){JSONObject q=items.optJSONObject(i);if(q==null)continue;LinearLayout c=cardBox();c.addView(text(q.optString("name","QR"),18,Color.rgb(20,20,20),true));c.addView(text(q.optString("ticketText",""),13,Color.DKGRAY,false));Button p=primaryButton("PREVISUALIZAR / IMPRIMIR");p.setOnClickListener(v->openTicket("MESON O FARO","",q.optString("ticketText",q.optString("name","")),q.optString("content",""),"QR",q.optString("id",""),q.optString("name",""),"",""));c.addView(p,marginTop(dp(8)));list.addView(c,marginBottomWrap(dp(10)));}});}
    private void showTemplates(){clear("Plantillas");addBack("Plantillas");TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);page.addView(list,marginTopWrap(dp(10)));loadList("templateList",status,items->{status.setText(items.length()+" plantillas");list.removeAllViews();for(int i=0;i<items.length();i++){JSONObject t=items.optJSONObject(i);if(t==null)continue;LinearLayout c=cardBox();c.addView(text(t.optString("name","Plantilla"),18,Color.rgb(20,20,20),true));JSONObject q=t.optJSONObject("qr");Button p=primaryButton("PREVISUALIZAR / IMPRIMIR");if(q!=null)p.setOnClickListener(v->openTicket(t.optString("title","MESON O FARO"),"",t.optString("text",q.optString("ticketText","")),q.optString("content",""),"Plantilla",t.optString("id",""),t.optString("name",""),"",""));else{p.setEnabled(false);p.setText("PLANTILLA EN SU MÓDULO");}c.addView(p,marginTop(dp(8)));list.addView(c,marginBottomWrap(dp(10)));}});}
    private void showFreePrint(){clear("Impresión libre");addBack("Impresión libre");EditText title=field("Título","",InputType.TYPE_CLASS_TEXT);EditText body=fieldMulti("Texto","",7);EditText qr=field("QR opcional (URL o texto)","",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);Button p=primaryButton("PREVISUALIZAR TICKET");page.addView(p,marginTop(dp(16)));p.setOnClickListener(v->{if(title.getText().toString().trim().isEmpty()&&body.getText().toString().trim().isEmpty()){alert("Sin contenido","Escribe un título o texto.");return;}openTicket(title.getText().toString(),"",body.getText().toString(),qr.getText().toString(),"Libre","",title.getText().toString(),"","");});}

    private void showHistory(){clear("Historial");addBack("Historial");TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);page.addView(list,marginTopWrap(dp(10)));loadList("historyList",status,items->{status.setText(items.length()+" movimientos");list.removeAllViews();for(int i=0;i<items.length();i++){JSONObject h=items.optJSONObject(i);if(h==null)continue;LinearLayout c=cardBox();c.addView(text(h.optString("type","Acción")+" · "+h.optString("event",h.optString("action","")),16,Color.rgb(20,20,20),true));c.addView(text(h.optString("date","")+" · "+h.optString("reference",""),13,Color.DKGRAY,false));list.addView(c,marginBottomWrap(dp(8)));}});}

    private void showSettings(){clear("Ajustes");addBack("Ajustes");SharedPreferences p=core.prefs();EditText api=field("Endpoint Apps Script",p.getString("api",AppCore.DEFAULT_API),InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);EditText key=field("Clave API",p.getString("key",""),InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);EditText ip=field("IP impresora ESC/POS",p.getString("printerIp",""),InputType.TYPE_CLASS_PHONE);EditText port=field("Puerto",String.valueOf(p.getInt("printerPort",9100)),InputType.TYPE_CLASS_NUMBER);EditText terminal=field("Nombre del terminal",p.getString("terminal","Caja O Faro"),InputType.TYPE_CLASS_TEXT);Button save=primaryButton("GUARDAR AJUSTES");page.addView(save,marginTop(dp(16)));Button testApi=secondaryButton("PROBAR CONEXIÓN CON GOOGLE");page.addView(testApi,marginTop(dp(10)));Button testPrinter=secondaryButton("IMPRIMIR PRUEBA DIRECTA");page.addView(testPrinter,marginTop(dp(10)));save.setOnClickListener(v->{savePrefs(p,api,key,ip,port,terminal);toast("Ajustes guardados");});testApi.setOnClickListener(v->{savePrefs(p,api,key,ip,port,terminal);testApi.setEnabled(false);io.execute(()->{try{JSONObject res=core.post(core.action("appPing"));core.ensureOk(res);runOnUiThread(()->{testApi.setEnabled(true);toast("Conexión correcta");});}catch(Exception e){runOnUiThread(()->{testApi.setEnabled(true);alert("Error de conexión",cleanError(e));});}});});testPrinter.setOnClickListener(v->{savePrefs(p,api,key,ip,port,terminal);testPrinter.setEnabled(false);io.execute(()->{try{core.printTest(core.printerIp(),core.printerPort());runOnUiThread(()->{testPrinter.setEnabled(true);toast("Prueba enviada");});}catch(Exception e){runOnUiThread(()->{testPrinter.setEnabled(true);alert("Error",cleanError(e));});}});});}
    private void savePrefs(SharedPreferences p,EditText api,EditText key,EditText ip,EditText port,EditText terminal){p.edit().putString("api",api.getText().toString().trim()).putString("key",key.getText().toString().trim()).putString("printerIp",ip.getText().toString().trim()).putInt("printerPort",safeInt(port.getText().toString(),9100,1,65535)).putString("terminal",terminal.getText().toString().trim()).apply();}

    private interface ListUi{void accept(JSONArray items);}private void loadList(String action,TextView status,ListUi ui){if(!requireApi())return;io.execute(()->{try{JSONObject req=core.action(action);if("historyList".equals(action))req.put("limit",80);JSONObject res=core.post(req);core.ensureOk(res);JSONArray a=res.optJSONArray("items");if(a==null)a=new JSONArray();JSONArray fin=a;runOnUiThread(()->ui.accept(fin));}catch(Exception e){runOnUiThread(()->status.setText("Error: "+cleanError(e)));}});}
    private void openTicket(String title,String sub,String body,String qr,String type,String ref,String detail,String reservationId,String participationCode){Intent i=new Intent(this,TicketPreviewActivity.class);i.putExtra("title",title);i.putExtra("subtitle",sub);i.putExtra("body",body);i.putExtra("qr",qr);i.putExtra("type",type);i.putExtra("reference",ref);i.putExtra("detail",detail);i.putExtra("reservationId",reservationId);i.putExtra("participationCode",participationCode);startActivity(i);}
    private void dial(String phone){if(phone==null||phone.trim().isEmpty()){toast("No hay teléfono");return;}startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+phone.trim())));}
    private void whatsapp(String phone){if(phone==null||phone.trim().isEmpty()){toast("No hay teléfono");return;}String clean=phone.replaceAll("[^0-9]","");if(clean.length()==9)clean="34"+clean;try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+clean)));}catch(Exception e){alert("WhatsApp",cleanError(e));}}

    private boolean requireApi(){if(core.configured())return true;alert("Falta configurar la API","Entra en Ajustes e introduce el endpoint y la clave de la app.");return false;}
    private void clear(String s){page.removeAllViews();subtitle.setText(s);}private void addBack(String t){addBackTo(t,this::showHome);}private void addBackTo(String title,Runnable action){LinearLayout bar=row();Button back=secondaryButton("‹ INICIO");back.setOnClickListener(v->action.run());bar.addView(back,new LinearLayout.LayoutParams(dp(105),dp(48)));TextView t=text(title,21,Color.rgb(20,20,20),true);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(12),0,0,0);bar.addView(t,new LinearLayout.LayoutParams(0,dp(48),1));page.addView(bar);page.addView(space(dp(12)));}
    private TextView info(String label,String val){TextView t=text(label.toUpperCase()+"\n"+val,15,Color.rgb(30,30,30),false);t.setPadding(dp(14),dp(12),dp(14),dp(12));t.setBackground(roundRect(Color.WHITE,12,Color.rgb(225,225,225),1));LinearLayout.LayoutParams p=marginBottomWrap(dp(8));t.setLayoutParams(p);return t;}private TextView label(String s){TextView t=text(s,13,Color.DKGRAY,true);t.setPadding(0,dp(18),0,dp(8));return t;}
    private Button bigButton(String title,String sub){Button b=primaryButton(title+"\n"+sub);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setPadding(dp(18),0,dp(18),0);b.setMinHeight(dp(76));return b;}private Button tileButton(String s){Button b=secondaryButton(s);b.setMinHeight(dp(68));return b;}private Button miniButton(String s){Button b=secondaryButton(s);b.setTextSize(10);b.setMinHeight(dp(44));return b;}private Button primaryButton(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(roundRect(Color.rgb(17,17,17),12,Color.TRANSPARENT,0));b.setMinHeight(dp(54));return b;}private Button secondaryButton(String s){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(Color.rgb(20,20,20));b.setAllCaps(false);b.setBackground(roundRect(Color.WHITE,12,Color.rgb(190,190,190),1));b.setMinHeight(dp(52));return b;}
    private LinearLayout cardBox(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(roundRect(Color.WHITE,14,Color.rgb(225,225,225),1));return c;}private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}private LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1);p.setMargins(dp(3),0,dp(3),0);return p;}private TextView sectionTitle(String s){TextView t=text(s,26,Color.rgb(20,20,20),true);t.setPadding(0,0,0,dp(8));return t;}private TextView paragraph(String s){TextView t=text(s,15,Color.DKGRAY,false);t.setLineSpacing(0,1.15f);t.setPadding(0,0,0,dp(18));return t;}private TextView emptyText(String s){TextView t=text(s,15,Color.DKGRAY,false);t.setPadding(dp(4),dp(12),dp(4),dp(12));return t;}private TextView text(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private EditText field(String label,String value,int type){TextView l=text(label,14,Color.DKGRAY,true);l.setPadding(dp(2),dp(12),dp(2),dp(6));page.addView(l);EditText e=input(value);e.setInputType(type);e.setSingleLine(true);page.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(54)));return e;}private EditText fieldMulti(String label,String value,int lines){TextView l=text(label,14,Color.DKGRAY,true);l.setPadding(dp(2),dp(12),dp(2),dp(6));page.addView(l);EditText e=input(value);e.setSingleLine(false);e.setMinLines(lines);e.setGravity(Gravity.TOP);e.setPadding(dp(14),dp(12),dp(14),dp(12));page.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));return e;}private EditText input(String value){EditText e=new EditText(this);e.setText(value);e.setTextSize(16);e.setTextColor(Color.rgb(20,20,20));e.setHintTextColor(Color.GRAY);e.setPadding(dp(14),0,dp(14),0);e.setBackground(roundRect(Color.WHITE,12,Color.rgb(205,205,205),1));return e;}
    private View space(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,h));return v;}private GradientDrawable roundRect(int fill,int radius,int stroke,int sw){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(sw>0)d.setStroke(dp(sw),stroke);return d;}private LinearLayout.LayoutParams marginTop(int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(54));p.topMargin=top;return p;}private LinearLayout.LayoutParams marginTopWrap(int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=top;return p;}private LinearLayout.LayoutParams marginBottomWrap(int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=bottom;return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private int safeInt(String v,int f,int min,int max){try{int n=Integer.parseInt(v.trim());return Math.max(min,Math.min(max,n));}catch(Exception e){return f;}}private String value(String s){return s==null||s.trim().isEmpty()?"—":s.trim();}private String cleanError(Throwable t){String m=t==null?"Error desconocido":t.getMessage();if(m==null||m.trim().isEmpty())m=String.valueOf(t);return m.length()>420?m.substring(0,420):m;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void alert(String t,String m){if(!isFinishing())new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Aceptar",null).show();}
}
