package com.ofaro.participaciones;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class PromotionsActivity extends Activity {
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private AppCore core;
    private LinearLayout page;
    private TextView subtitle;
    private JSONArray campaigns=new JSONArray(),prizes=new JSONArray();
    private EditText redeemCode;
    private String validatedCode="";

    @Override protected void onCreate(Bundle b){super.onCreate(b);core=new AppCore(this);setContentView(buildRoot());showCampaigns();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}

    private View buildRoot(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(246,245,242));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(18),dp(15),dp(18),dp(13));head.setBackgroundColor(Color.rgb(15,15,15));head.addView(text("O FARO",23,Color.WHITE,true));subtitle=text("Promociones",13,Color.LTGRAY,false);head.addView(subtitle);root.addView(head);
        LinearLayout nav=row();nav.setPadding(dp(7),dp(7),dp(7),dp(7));nav.setBackgroundColor(Color.WHITE);
        Button back=nav("‹ INICIO");back.setOnClickListener(v->finish());Button camp=nav("CAMPAÑAS");camp.setOnClickListener(v->showCampaigns());Button pri=nav("PREMIOS");pri.setOnClickListener(v->showPrizes());Button red=nav("CANJEAR");red.setOnClickListener(v->showRedeem());
        nav.addView(back,weight48());nav.addView(camp,weight48());nav.addView(pri,weight48());nav.addView(red,weight48());root.addView(nav);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(14),dp(15),dp(14),dp(30));scroll.addView(page);root.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));return root;
    }

    private void showCampaigns(){
        clear("Promociones");LinearLayout top=row();TextView h=title("Campañas y sorteos");top.addView(h,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));Button add=primary("+ NUEVA");add.setOnClickListener(v->editCampaign(null));top.addView(add,new LinearLayout.LayoutParams(dp(110),dp(48)));page.addView(top);page.addView(paragraph("El cliente juega escaneando un QR único de un solo uso. Todo se resuelve en servidor."));
        TextView status=text("Cargando campañas…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=column();page.addView(list,topWrap(dp(10)));
        loadPromotions(status,()->{status.setText(campaigns.length()+" configuradas");list.removeAllViews();for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c!=null)addCampaignCard(list,c);}if(campaigns.length()==0)list.addView(empty("No hay campañas."));});
        Button hist=secondary("HISTORIAL Y ESTADÍSTICAS");hist.setOnClickListener(v->showHistory());page.addView(hist,top(dp(14)));
    }

    private void addCampaignCard(LinearLayout list,JSONObject c){
        LinearLayout card=card();String type=s(c,"type","TIPO_PROMOCION","Promoción"),name=s(c,"name","NOMBRE","Promoción"),desc=s(c,"description","DESCRIPCION","Sin descripción");boolean active=b(c,"active","ACTIVA");
        LinearLayout line=row();LinearLayout left=column();left.addView(text(type.toUpperCase(Locale.ROOT),11,Color.GRAY,true));left.addView(text(name,20,Color.rgb(20,20,20),true));left.addView(text(desc,14,Color.DKGRAY,false));line.addView(left,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));TextView st=text(active?"ACTIVA":"PAUSADA",12,active?Color.rgb(30,105,55):Color.rgb(145,100,15),true);st.setPadding(dp(9),dp(6),dp(9),dp(6));line.addView(st);card.addView(line);
        String prob=number(c,"winProbability","PROB_GANAR")+"% prob. ganar · "+s(c,"ticketTemplate","PLANTILLA_TICKET","Estándar");TextView info=text(prob,13,Color.DKGRAY,false);info.setPadding(0,dp(8),0,dp(10));card.addView(info);
        LinearLayout r1=row();Button edit=small("EDITAR");edit.setOnClickListener(v->editCampaign(c));Button toggle=small(active?"PAUSAR":"ACTIVAR");toggle.setOnClickListener(v->toggleCampaign(c,toggle));r1.addView(edit,weight());r1.addView(toggle,weight());card.addView(r1);
        LinearLayout r2=row();Button cfg=small(type.equalsIgnoreCase("Ruleta")?"SEGMENTOS":"PREMIOS");cfg.setOnClickListener(v->{if(type.equalsIgnoreCase("Ruleta"))showWheelEditor(c);else showPrizeLinks(c);});Button qr=small("QR CLIENTE");qr.setEnabled(active);qr.setOnClickListener(v->issueQr(c,qr));r2.addView(cfg,weight());r2.addView(qr,weight());card.addView(r2,topWrap(dp(7)));
        Button test=secondary("PROBAR RESULTADO (INTERNO)");test.setEnabled(active);test.setOnClickListener(v->testPlay(c,test));card.addView(test,top(dp(8)));
        list.addView(card,bottom(dp(10)));
    }

    private void loadPromotions(TextView status,Runnable done){
        if(!requireApi())return;io.execute(()->{try{JSONObject cr=core.post(core.action("promotionList"));core.ensureOk(cr);JSONObject pr=core.post(core.action("prizeList").put("includeNoPrize",true));core.ensureOk(pr);campaigns=array(cr,"items");prizes=array(pr,"items");cache("promo_campaigns",campaigns);cache("promo_prizes",prizes);runOnUiThread(done);}catch(Exception e){JSONArray cc=cacheArray("promo_campaigns"),pp=cacheArray("promo_prizes");if(cc.length()>0){campaigns=cc;prizes=pp;runOnUiThread(()->{status.setText("Sin conexión · mostrando última copia guardada");done.run();});}else runOnUiThread(()->status.setText("Error: "+msg(e)));}});}

    private void toggleCampaign(JSONObject c,Button button){button.setEnabled(false);boolean active=b(c,"active","ACTIVA");io.execute(()->{try{JSONObject r=core.post(core.action("promotionToggle").put("id",id(c)).put("active",!active));core.ensureOk(r);runOnUiThread(()->{toast(active?"Campaña pausada":"Campaña activada");showCampaigns();});}catch(Exception e){runOnUiThread(()->{button.setEnabled(true);alert("No se pudo cambiar el estado",msg(e));});}});}

    private void editCampaign(JSONObject c){
        final boolean isNew=c==null;if(c==null)c=new JSONObject();final JSONObject x=c;
        ScrollView sv=new ScrollView(this);LinearLayout box=column();box.setPadding(dp(16),dp(8),dp(16),dp(10));sv.addView(box);
        EditText name=field(box,"Nombre",s(x,"name","NOMBRE",""));EditText desc=multi(box,"Descripción",s(x,"description","DESCRIPCION",""),3);Spinner type=spinner(box,"Tipo",new String[]{"Ruleta","Premio directo","Rasca","Código premiado"},s(x,"type","TIPO_PROMOCION","Ruleta"));EditText prob=field(box,"Probabilidad general de ganar",String.valueOf(number(x,"winProbability","PROB_GANAR")));prob.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);EditText start=field(box,"Fecha inicio (AAAA-MM-DD)",s(x,"startDate","FECHA_INICIO",""));EditText end=field(box,"Fecha fin (AAAA-MM-DD)",s(x,"endDate","FECHA_FIN",""));EditText startTime=field(box,"Hora inicio",s(x,"startTime","HORA_INICIO","12:00"));EditText endTime=field(box,"Hora fin",s(x,"endTime","HORA_FIN","23:59"));EditText days=field(box,"Días activos",s(x,"activeDays","DIAS_ACTIVOS","Lun,Mar,Mié,Jue,Vie,Sáb,Dom"));EditText client=field(box,"Límite por cliente",s(x,"clientLimit","LIMITE_POR_CLIENTE","1"));EditText daily=field(box,"Límite diario",s(x,"dailyLimit","LIMITE_POR_DIA","500"));EditText win=multi(box,"Mensaje ganador",s(x,"winnerMessage","MENSAJE_GANA","¡Enhorabuena! Te ha tocado {{premio}}."),2);EditText lose=multi(box,"Mensaje sin premio",s(x,"loserMessage","MENSAJE_NO_GANA","Esta vez no ha habido premio."),2);Spinner tpl=spinner(box,"Plantilla ticket",new String[]{"Promoción Premium","Promoción Clásica","Entrada QR","Ruleta QR","Rasca QR","Premio Canjeable","Cupón Descuento","Minimal Premium"},s(x,"ticketTemplate","PLANTILLA_TICKET","Promoción Premium"));Spinner state=spinner(box,"Estado",new String[]{"Pausada","Activa"},b(x,"active","ACTIVA")?"Activa":"Pausada");
        new AlertDialog.Builder(this).setTitle(isNew?"Nueva promoción":"Editar promoción").setView(sv).setNegativeButton("Cancelar",null).setPositiveButton("GUARDAR",null).create().setOnShowListener(d->{AlertDialog dialog=(AlertDialog)d;dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){toast("Escribe un nombre");return;}dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);JSONObject p=new JSONObject();try{p.put("ID_PROMOCION",isNew?"":id(x));p.put("NOMBRE",name.getText().toString().trim());p.put("DESCRIPCION",desc.getText().toString().trim());p.put("TIPO_PROMOCION",selected(type));boolean active="Activa".equals(selected(state));p.put("ESTADO",active?"Activa":"Pausada");p.put("ACTIVA",active?"Sí":"No");p.put("FECHA_INICIO",start.getText().toString().trim());p.put("FECHA_FIN",end.getText().toString().trim());p.put("HORA_INICIO",startTime.getText().toString().trim());p.put("HORA_FIN",endTime.getText().toString().trim());p.put("DIAS_ACTIVOS",days.getText().toString().trim());p.put("PROB_GANAR",parseDouble(prob.getText().toString(),0));p.put("MENSAJE_GANA",win.getText().toString().trim());p.put("MENSAJE_NO_GANA",lose.getText().toString().trim());p.put("PLANTILLA_TICKET",selected(tpl));p.put("LIMITE_POR_CLIENTE",client.getText().toString().trim());p.put("LIMITE_POR_DIA",daily.getText().toString().trim());p.put("REQUIERE_CODIGO",selected(type).equals("Código premiado")?"Sí":"No");}catch(Exception ignored){}io.execute(()->{try{JSONObject r=core.post(core.action("promotionSave").put("promotion",p));core.ensureOk(r);runOnUiThread(()->{dialog.dismiss();toast("Promoción guardada");showCampaigns();});}catch(Exception e){runOnUiThread(()->{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(true);alert("No se pudo guardar",msg(e));});}});});});
        AlertDialog dlg=new AlertDialog.Builder(this).create(); // no-op to satisfy older lint
    }

    private void showWheelEditor(JSONObject c){
        clear("Ruleta");back("Segmentos · "+s(c,"name","NOMBRE","Ruleta"),this::showCampaigns);TextView info=text("Cargando segmentos…",14,Color.DKGRAY,false);page.addView(info);LinearLayout rows=column();page.addView(rows,topWrap(dp(8)));Button add=secondary("+ AÑADIR SEGMENTO");page.addView(add,top(dp(8)));Button save=primary("GUARDAR RULETA");page.addView(save,top(dp(8)));List<SegmentViews> views=new ArrayList<>();
        io.execute(()->{try{JSONObject r=core.post(core.action("wheelSegmentsList").put("promotionId",id(c)));core.ensureOk(r);JSONArray arr=array(r,"items");runOnUiThread(()->{info.setText("La suma de probabilidades debe ser exactamente 100%.");for(int i=0;i<arr.length();i++)addSegmentRow(rows,views,arr.optJSONObject(i));if(arr.length()==0){addSegmentRow(rows,views,new JSONObject());}});}catch(Exception e){runOnUiThread(()->info.setText("Error: "+msg(e)));}});
        add.setOnClickListener(v->addSegmentRow(rows,views,new JSONObject()));save.setOnClickListener(v->{double total=0;JSONArray items=new JSONArray();for(int i=0;i<views.size();i++){SegmentViews s=views.get(i);if(s.root.getParent()==null)continue;double pct=parseDouble(s.percent.getText().toString(),0);total+=pct;JSONObject o=new JSONObject();try{o.put("label",s.label.getText().toString().trim());String pid=prizeId(selected(s.prize));o.put("prizeId",pid);o.put("percent",pct);o.put("active",true);o.put("order",i+1);o.put("resultType","P000".equals(pid)?"SIN_PREMIO":"PREMIO");o.put("style","premium");}catch(Exception ignored){}items.put(o);}if(Math.abs(total-100d)>.001){alert("Probabilidades","Ahora suman "+total+"%. Deben sumar 100%.");return;}save.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("wheelSegmentsSave").put("promotionId",id(c)).put("items",items));core.ensureOk(r);runOnUiThread(()->{toast("Ruleta guardada");showCampaigns();});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);alert("No se pudo guardar",msg(e));});}});});
    }

    private static class SegmentViews{LinearLayout root;EditText label,percent;Spinner prize;}
    private void addSegmentRow(LinearLayout host,List<SegmentViews> all,JSONObject x){SegmentViews v=new SegmentViews();v.root=card();v.label=field(v.root,"Texto del sector",s(x,"label","ETIQUETA","NUEVO"));v.prize=spinner(v.root,"Premio",prizeNames(),prizeNameById(s(x,"prizeId","ID_PREMIO","P000")));v.percent=field(v.root,"Probabilidad %",String.valueOf(number(x,"percentage","PORCENTAJE","percent")));v.percent.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);Button del=secondary("ELIMINAR SECTOR");del.setOnClickListener(z->{host.removeView(v.root);});v.root.addView(del,top(dp(7)));host.addView(v.root,bottom(dp(9)));all.add(v);}

    private void showPrizeLinks(JSONObject c){
        clear("Premios");back("Premios · "+s(c,"name","NOMBRE","Promoción"),this::showCampaigns);TextView info=text("Cargando…",14,Color.DKGRAY,false);page.addView(info);LinearLayout list=column();page.addView(list,topWrap(dp(8)));List<LinkViews> views=new ArrayList<>();Button save=primary("GUARDAR PREMIOS");page.addView(save,top(dp(10)));
        io.execute(()->{try{JSONObject r=core.post(core.action("promotionPrizeLinksList").put("promotionId",id(c)));core.ensureOk(r);JSONArray current=array(r,"items");runOnUiThread(()->{info.setText("Si la promoción gana, el peso decide qué premio se entrega.");for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p==null||"P000".equals(id(p)))continue;JSONObject link=findLink(current,id(p));LinkViews lv=new LinkViews();lv.prizeId=id(p);lv.check=new CheckBox(this);lv.check.setText(s(p,"name","NOMBRE","Premio"));lv.check.setChecked(link!=null);lv.weight=input(link==null?"1":s(link,"PESO","weight","1"));lv.weight.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);LinearLayout rr=row();rr.setPadding(dp(4),dp(5),dp(4),dp(5));rr.addView(lv.check,new LinearLayout.LayoutParams(0,dp(52),1));rr.addView(lv.weight,new LinearLayout.LayoutParams(dp(92),dp(52)));list.addView(rr);views.add(lv);}});}catch(Exception e){runOnUiThread(()->info.setText("Error: "+msg(e)));}});
        save.setOnClickListener(v->{JSONArray items=new JSONArray();int order=1;for(LinkViews lv:views)if(lv.check.isChecked()){JSONObject o=new JSONObject();try{o.put("prizeId",lv.prizeId);o.put("weight",parseDouble(lv.weight.getText().toString(),1));o.put("active",true);o.put("order",order++);}catch(Exception ignored){}items.put(o);}if(items.length()==0){alert("Premios","Selecciona al menos un premio.");return;}save.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("promotionPrizeLinksSave").put("promotionId",id(c)).put("items",items));core.ensureOk(r);runOnUiThread(()->{toast("Premios guardados");showCampaigns();});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);alert("Error",msg(e));});}});});
    }
    private static class LinkViews{String prizeId;CheckBox check;EditText weight;}

    private void issueQr(JSONObject c,Button b){b.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("promoPublicIssue").put("id",id(c)).put("expiresHours",48));core.ensureOk(r);String url=r.optString("url","");String name=s(c,"name","NOMBRE","Promoción"),type=s(c,"type","TIPO_PROMOCION","Promoción");runOnUiThread(()->{b.setEnabled(true);Intent i=new Intent(this,TicketPreviewActivity.class);i.putExtra("title",name);i.putExtra("subtitle",type.toUpperCase(Locale.ROOT));i.putExtra("body","ESCANEA PARA JUGAR\nQR único de un solo uso.");i.putExtra("qr",url);i.putExtra("type","Promoción QR");i.putExtra("reference",r.optString("token",""));i.putExtra("detail","QR cliente · "+name);i.putExtra("template",type.equalsIgnoreCase("Ruleta")?"Ruleta QR":type.equalsIgnoreCase("Rasca")?"Rasca QR":"Entrada QR");startActivity(i);});}catch(Exception e){runOnUiThread(()->{b.setEnabled(true);alert("No se pudo generar el QR",msg(e));});}});}

    private void testPlay(JSONObject c,Button b){b.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("promotionPlay").put("promotionId",id(c)));core.ensureOk(r);runOnUiThread(()->{b.setEnabled(true);String prize=r.optBoolean("won",false)?r.optString("prize","Premio"):"SIN PREMIO";new AlertDialog.Builder(this).setTitle(prize).setMessage(r.optString("message","")+"\n\nCódigo: "+r.optString("code","")).setNegativeButton("Cerrar",null).setPositiveButton("TICKET",(d,w)->{Intent i=new Intent(this,TicketPreviewActivity.class);i.putExtra("title",r.optString("promotionName",s(c,"name","NOMBRE","Promoción")));i.putExtra("subtitle",prize);i.putExtra("body",r.optString("message","")+"\n\nCódigo: "+r.optString("code",""));i.putExtra("qr",r.optString("qrPayload",r.optString("code","")));i.putExtra("type","Promoción");startActivity(i);}).show();});}catch(Exception e){runOnUiThread(()->{b.setEnabled(true);alert("Error",msg(e));});}});}

    private void showPrizes(){
        clear("Premios");LinearLayout top=row();top.addView(title("Premios"),new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));Button add=primary("+ NUEVO");add.setOnClickListener(v->editPrize(null));top.addView(add,new LinearLayout.LayoutParams(dp(110),dp(48)));page.addView(top);TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=column();page.addView(list,topWrap(dp(8)));
        io.execute(()->{try{JSONObject r=core.post(core.action("prizeList").put("includeNoPrize",true));core.ensureOk(r);prizes=array(r,"items");cache("promo_prizes",prizes);runOnUiThread(()->{status.setText((prizes.length()-1)+" premios configurados");for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p==null||"P000".equals(id(p)))continue;LinearLayout card=card();card.addView(text(s(p,"name","NOMBRE","Premio"),19,Color.rgb(20,20,20),true));card.addView(text(s(p,"type","TIPO","Premio")+" · Stock: "+s(p,"stockRemaining","STOCK_RESTANTE","stock","∞"),13,Color.DKGRAY,false));Button e=secondary("EDITAR PREMIO");e.setOnClickListener(v->editPrize(p));card.addView(e,top(dp(8)));list.addView(card,bottom(dp(9)));}});}catch(Exception e){runOnUiThread(()->status.setText("Error: "+msg(e)));}});
    }

    private void editPrize(JSONObject p){boolean isNew=p==null;if(p==null)p=new JSONObject();JSONObject x=p;LinearLayout box=column();box.setPadding(dp(16),dp(4),dp(16),dp(8));EditText name=field(box,"Nombre",s(x,"name","NOMBRE",""));Spinner type=spinner(box,"Tipo",new String[]{"Producto gratis","Descuento","Vale","Premio físico","Otro"},s(x,"type","TIPO","Producto gratis"));EditText stock=field(box,"Stock",s(x,"stock","STOCK",""));EditText text=multi(box,"Texto del ticket",s(x,"ticketDescription","DESCRIPCION_TICKET",""),3);EditText cond=multi(box,"Condiciones",s(x,"conditions","CONDICIONES",""),3);EditText value=field(box,"Valor",s(x,"value","VALOR",""));Spinner active=spinner(box,"Activo",new String[]{"Sí","No"},b(x,"active","ACTIVO")?"Sí":"No");ScrollView sv=new ScrollView(this);sv.addView(box);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(isNew?"Nuevo premio":"Editar premio").setView(sv).setNegativeButton("Cancelar",null).setPositiveButton("GUARDAR",null).create();dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){toast("Escribe el nombre");return;}dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);JSONObject prize=new JSONObject();try{prize.put("id",isNew?"":id(x));prize.put("name",name.getText().toString().trim());prize.put("type",selected(type));prize.put("stock",stock.getText().toString().trim());prize.put("ticketDescription",text.getText().toString().trim());prize.put("conditions",cond.getText().toString().trim());prize.put("value",value.getText().toString().trim());prize.put("active",selected(active));prize.put("weight",number(x,"weight","PESO"));prize.put("order",number(x,"order","ORDEN"));}catch(Exception ignored){}io.execute(()->{try{JSONObject r=core.post(core.action("prizeSave").put("prize",prize));core.ensureOk(r);runOnUiThread(()->{dialog.dismiss();toast("Premio guardado");showPrizes();});}catch(Exception e){runOnUiThread(()->{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(true);alert("Error",msg(e));});}});}));dialog.show();}

    private void showRedeem(){clear("Canjear");page.addView(title("Validar y canjear"));page.addView(paragraph("Escanea el QR/código de premio o introdúcelo manualmente."));Button scan=primary("ESCANEAR QR");scan.setOnClickListener(v->scanner());page.addView(scan);redeemCode=input("");redeemCode.setHint("PR-XXXXX-XXXXX");page.addView(redeemCode,top(dp(12)));Button validate=secondary("VALIDAR CÓDIGO");page.addView(validate,top(dp(8)));TextView result=text("Sin código validado",15,Color.DKGRAY,false);result.setPadding(dp(12),dp(12),dp(12),dp(12));page.addView(result,topWrap(dp(10)));validate.setOnClickListener(v->validate(redeemCode.getText().toString(),result));}
    private void scanner(){IntentIntegrator i=new IntentIntegrator(this);i.setDesiredBarcodeFormats(java.util.Collections.singletonList("QR_CODE"));i.setPrompt("Escanea el código del premio");i.setBeepEnabled(false);i.setOrientationLocked(true);i.initiateScan();}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){IntentResult r=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(r!=null){if(r.getContents()!=null){String raw=r.getContents().trim();if(raw.startsWith("OFARO:PROMO:"))raw=raw.substring("OFARO:PROMO:".length());if(redeemCode!=null){redeemCode.setText(raw);showRedeem();redeemCode.setText(raw);TextView out=text("Pulsa VALIDAR CÓDIGO",15,Color.DKGRAY,false);}}return;}super.onActivityResult(requestCode,resultCode,data);}
    private void validate(String code,TextView result){code=code==null?"":code.trim();if(code.startsWith("OFARO:PROMO:"))code=code.substring("OFARO:PROMO:".length());if(code.isEmpty()){toast("Código vacío");return;}String finalCode=code;result.setText("Validando…");io.execute(()->{try{JSONObject r=core.post(core.action("promotionValidate").put("code",finalCode));core.ensureOk(r);validatedCode=r.optString("code",finalCode);runOnUiThread(()->{result.setText("Estado: "+r.optString("state","")+"\nPremio: "+r.optString("prize","Sin premio")+"\nPromoción: "+r.optString("promotionName","")+"\nCódigo: "+validatedCode);if(r.optBoolean("canRedeem",false)){Button redeem=primary("CANJEAR PREMIO");redeem.setOnClickListener(v->confirmRedeem(redeem,result));page.addView(redeem,top(dp(10)));}});}catch(Exception e){runOnUiThread(()->result.setText("No válido: "+msg(e)));}});}
    private void confirmRedeem(Button b,TextView out){new AlertDialog.Builder(this).setTitle("Confirmar canje").setMessage("El código quedará inutilizado. ¿Entregar el premio?").setNegativeButton("Cancelar",null).setPositiveButton("CANJEAR",(d,w)->{b.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("promotionRedeem").put("code",validatedCode));core.ensureOk(r);runOnUiThread(()->{out.setText("CANJEADO\n"+r.optString("prize","Premio")+"\n"+r.optString("code",validatedCode));b.setVisibility(View.GONE);});}catch(Exception e){runOnUiThread(()->{b.setEnabled(true);alert("No se pudo canjear",msg(e));});}});}).show();}

    private void showHistory(){clear("Historial");back("Historial de promociones",this::showCampaigns);TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=column();page.addView(list,topWrap(dp(8)));io.execute(()->{try{JSONObject stats=core.post(core.action("promotionStats"));core.ensureOk(stats);JSONObject h=core.post(core.action("promotionHistory").put("limit",100));core.ensureOk(h);JSONArray arr=array(h,"items");runOnUiThread(()->{status.setText("Jugadas: "+stats.optInt("total",0)+" · Premiadas: "+stats.optString("winRate","0")+"% · Canjeadas: "+stats.optInt("redeemed",0));for(int i=0;i<arr.length();i++){JSONObject x=arr.optJSONObject(i);if(x==null)continue;TextView r=text(s(x,"promotionName","PROMOCION","Promoción")+"\n"+s(x,"date","FECHA","")+" · "+s(x,"code","CODIGO","")+"\n"+s(x,"prize","PREMIO",s(x,"state","ESTADO","")),14,Color.rgb(30,30,30),false);r.setPadding(dp(12),dp(10),dp(12),dp(10));r.setBackground(box(Color.WHITE,11,Color.rgb(220,220,220),1));list.addView(r,bottom(dp(7)));}});}catch(Exception e){runOnUiThread(()->status.setText("Error: "+msg(e)));}});}

    private boolean requireApi(){if(core.configured())return true;alert("Falta configurar la API","Ve a Ajustes en la pantalla principal.");return false;}
    private void cache(String k,JSONArray a){try{core.prefs().edit().putString(k,a.toString()).apply();}catch(Exception ignored){}}private JSONArray cacheArray(String k){try{return new JSONArray(core.prefs().getString(k,"[]"));}catch(Exception e){return new JSONArray();}}
    private JSONArray array(JSONObject o,String k){JSONArray a=o==null?null:o.optJSONArray(k);return a==null?new JSONArray():a;}
    private JSONObject findLink(JSONArray a,String pid){for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null&&pid.equals(s(x,"ID_PREMIO","prizeId","")))return x;}return null;}
    private String[] prizeNames(){List<String> n=new ArrayList<>();for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p!=null)n.add(s(p,"name","NOMBRE","Premio")+" ["+id(p)+"]");}if(n.isEmpty())n.add("Sin premio [P000]");return n.toArray(new String[0]);}private String prizeNameById(String pid){for(String n:prizeNames())if(n.endsWith("["+pid+"]"))return n;return prizeNames()[0];}private String prizeId(String label){int a=label.lastIndexOf('['),b=label.lastIndexOf(']');return a>=0&&b>a?label.substring(a+1,b):"P000";}
    private String id(JSONObject o){return s(o,"id","ID_PROMOCION","ID_PREMIO","");}
    private String s(JSONObject o,String a,String b,String def){String v=o==null?"":o.optString(a,"");if(v.isEmpty())v=o==null?"":o.optString(b,"");return v.isEmpty()?def:v;}private String s(JSONObject o,String a,String b,String c,String def){String v=s(o,a,b,"");if(v.isEmpty())v=o==null?"":o.optString(c,"");return v.isEmpty()?def:v;}private boolean b(JSONObject o,String a,String b){if(o==null)return false;if(o.has(a))return o.optBoolean(a,false)||yes(o.optString(a,""));return yes(o.optString(b,""));}private boolean yes(String v){String s=v==null?"":v.trim().toLowerCase(Locale.ROOT);return s.equals("sí")||s.equals("si")||s.equals("true")||s.equals("1")||s.equals("activa");}private double number(JSONObject o,String a,String b){return number(o,a,b,null);}private double number(JSONObject o,String a,String b,String c){if(o==null)return 0;if(o.has(a))return o.optDouble(a,0);if(o.has(b))return o.optDouble(b,0);return c==null?0:o.optDouble(c,0);}private double parseDouble(String s,double f){try{return Double.parseDouble(s.trim().replace(',','.'));}catch(Exception e){return f;}}

    private void clear(String s){page.removeAllViews();subtitle.setText(s);}private void back(String name,Runnable r){LinearLayout line=row();Button b=secondary("‹ ATRÁS");b.setOnClickListener(v->r.run());line.addView(b,new LinearLayout.LayoutParams(dp(105),dp(48)));TextView t=text(name,20,Color.rgb(20,20,20),true);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(10),0,0,0);line.addView(t,new LinearLayout.LayoutParams(0,dp(48),1));page.addView(line);page.addView(space(dp(9)));}
    private TextView title(String s){return text(s,27,Color.rgb(20,20,20),true);}private TextView paragraph(String s){TextView t=text(s,15,Color.DKGRAY,false);t.setPadding(0,dp(5),0,dp(12));t.setLineSpacing(0,1.15f);return t;}private TextView empty(String s){TextView t=text(s,15,Color.DKGRAY,false);t.setPadding(dp(10),dp(20),dp(10),dp(20));return t;}private LinearLayout card(){LinearLayout c=column();c.setPadding(dp(14),dp(14),dp(14),dp(14));c.setBackground(box(Color.WHITE,15,Color.rgb(218,216,212),1));return c;}private LinearLayout column(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);return c;}private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
    private Button nav(String s){Button b=secondary(s);b.setTextSize(10);return b;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextSize(13);b.setAllCaps(false);b.setBackground(box(Color.rgb(15,15,15),12,Color.TRANSPARENT,0));b.setMinHeight(dp(52));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(20,20,20));b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextSize(12);b.setAllCaps(false);b.setBackground(box(Color.WHITE,12,Color.rgb(190,190,190),1));b.setMinHeight(dp(50));return b;}private Button small(String s){Button b=secondary(s);b.setTextSize(11);return b;}private TextView text(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private EditText input(String v){EditText e=new EditText(this);e.setText(v);e.setTextSize(16);e.setTextColor(Color.rgb(20,20,20));e.setPadding(dp(12),0,dp(12),0);e.setBackground(box(Color.WHITE,10,Color.rgb(205,205,205),1));return e;}private EditText field(LinearLayout box,String label,String value){TextView l=text(label,13,Color.DKGRAY,true);l.setPadding(0,dp(8),0,dp(4));box.addView(l);EditText e=input(value);e.setSingleLine(true);box.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(50)));return e;}private EditText multi(LinearLayout box,String label,String value,int lines){TextView l=text(label,13,Color.DKGRAY,true);l.setPadding(0,dp(8),0,dp(4));box.addView(l);EditText e=input(value);e.setSingleLine(false);e.setMinLines(lines);e.setGravity(Gravity.TOP);e.setPadding(dp(12),dp(9),dp(12),dp(9));box.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));return e;}private Spinner spinner(LinearLayout box,String label,String[] items,String selected){TextView l=text(label,13,Color.DKGRAY,true);l.setPadding(0,dp(8),0,dp(4));box.addView(l);Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,items));box.addView(s,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(50)));for(int i=0;i<items.length;i++)if(items[i].equals(selected)){s.setSelection(i);break;}return s;}private String selected(Spinner s){return s.getSelectedItem()==null?"":String.valueOf(s.getSelectedItem());}
    private GradientDrawable box(int fill,int radius,int stroke,int sw){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(sw>0)d.setStroke(dp(sw),stroke);return d;}private LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(50),1);p.setMargins(dp(3),0,dp(3),0);return p;}private LinearLayout.LayoutParams weight48(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(48),1);p.setMargins(dp(2),0,dp(2),0);return p;}private LinearLayout.LayoutParams top(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(52));p.topMargin=v;return p;}private LinearLayout.LayoutParams topWrap(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=v;return p;}private LinearLayout.LayoutParams bottom(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=v;return p;}private View space(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,h));return v;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private String msg(Throwable t){String m=t==null?"Error desconocido":t.getMessage();return m==null||m.trim().isEmpty()?String.valueOf(t):m;}private void alert(String t,String m){if(!isFinishing())new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Aceptar",null).show();}
}
