package com.ofaro.participaciones;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.Collections;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class PromotionsV5Activity extends Activity {
    private static final String CACHE_CAMPAIGNS="promo_campaigns",CACHE_PRIZES="promo_prizes";
    private final ExecutorService io=Executors.newFixedThreadPool(2);
    private AppCore core;private LinearLayout page;private TextView printerState;private JSONArray campaigns=new JSONArray(),prizes=new JSONArray();private EditText redeemInput;private TextView redeemResult;private TextView redeemButton;private String validatedCode="";

    @Override protected void onCreate(Bundle state){super.onCreate(state);V5Ui.applySystemBars(this);core=new AppCore(this);campaigns=core.cachedArray(CACHE_CAMPAIGNS);prizes=core.cachedArray(CACHE_PRIZES);core.startPrinterWatchdog();setContentView(build());String mode=getIntent().getStringExtra("mode");if("redeem".equals(mode))showRedeem();else if("qr".equals(mode))showQrList();else showSummary();refreshData();}
    @Override protected void onResume(){super.onResume();if(core!=null){core.startPrinterWatchdog();V5Ui.updatePrinter(printerState,core);}}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}

    private View build(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(V5Ui.BG);LinearLayout shell=V5Ui.column(this);V5Ui.Header h=V5Ui.header(this,core,"Promociones");printerState=h.printer;shell.addView(h.view);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);page=V5Ui.column(this);page.setPadding(V5Ui.dp(this,18),V5Ui.dp(this,10),V5Ui.dp(this,18),V5Ui.dp(this,24));scroll.addView(page);shell.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));shell.addView(V5Ui.bottomNav(this,2));root.addView(shell,new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));View plus=V5Ui.floatingPlus(this,this::quickActions);FrameLayout.LayoutParams fp=new FrameLayout.LayoutParams(V5Ui.dp(this,50),V5Ui.dp(this,50),Gravity.RIGHT|Gravity.BOTTOM);fp.rightMargin=V5Ui.dp(this,22);fp.bottomMargin=V5Ui.dp(this,73);root.addView(plus,fp);return root;}

    private void base(String tab){page.removeAllViews();page.addView(V5Ui.kicker(this,"PROMOCIONES"));TextView title=V5Ui.title(this,"Campañas y resultados");title.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,12));page.addView(title);page.addView(tabs(tab));}
    private View tabs(String selected){LinearLayout row=V5Ui.row(this);String[] tabs={"RESUMEN","CAMPAÑAS","PREMIOS","CANJES"};for(String t:tabs){boolean on=t.equals(selected);TextView chip=V5Ui.text(this,label(t),9,on?Color.WHITE:V5Ui.MUTED,true);chip.setGravity(Gravity.CENTER);chip.setBackground(V5Ui.bg(this,on?V5Ui.GREEN:V5Ui.SURFACE,15));chip.setOnClickListener(v->{if("RESUMEN".equals(t))showSummary();else if("CAMPAÑAS".equals(t))showCampaigns();else if("PREMIOS".equals(t))showPrizes();else showRedeem();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,V5Ui.dp(this,38),1);p.setMargins(V5Ui.dp(this,3),0,V5Ui.dp(this,3),0);row.addView(chip,p);}return row;}

    private void showSummary(){base("RESUMEN");int active=activeCount(),plays=0,winners=0;for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c==null)continue;JSONObject s=c.optJSONObject("stats");if(s!=null){plays+=s.optInt("plays",0);winners+=s.optInt("winners",0);}}
        LinearLayout metrics=V5Ui.row(this);metrics.addView(V5Ui.metric(this,"ACTIVAS",String.valueOf(active),"campañas"),weightGap());metrics.addView(V5Ui.metric(this,"JUGADAS",String.valueOf(plays),"registradas"),weightGap());metrics.addView(V5Ui.metric(this,"PREMIOS",String.valueOf(winners),"ganadores"),weightGap());page.addView(metrics,top(V5Ui.dp(this,13)));
        LinearLayout quick=V5Ui.row(this);quick.addView(V5Ui.quickAction(this,R.drawable.ic_qr_v5,"Generar QR",this::showQrList),weightGap());quick.addView(V5Ui.quickAction(this,R.drawable.ic_check_v5,"Canjear",this::showRedeem),weightGap());page.addView(quick,top(V5Ui.dp(this,10)));page.addView(section("CAMPAÑAS ACTIVAS"));int shown=0;for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c!=null&&c.optBoolean("active",false)){page.addView(campaignCard(c),bottom(V5Ui.dp(this,8)));shown++;if(shown>=3)break;}}if(shown==0){LinearLayout empty=V5Ui.softCard(this);empty.addView(V5Ui.text(this,"No hay campañas activas.",13,V5Ui.MUTED,false));page.addView(empty);}TextView all=action("Ver todas las campañas",false,this::showCampaigns);page.addView(all,top(V5Ui.dp(this,10)));}

    private void showCampaigns(){base("CAMPAÑAS");TextView status=V5Ui.text(this,campaigns.length()+" campañas",11,V5Ui.MUTED,false);status.setPadding(0,V5Ui.dp(this,12),0,V5Ui.dp(this,8));page.addView(status);if(campaigns.length()==0){LinearLayout empty=V5Ui.softCard(this);empty.addView(V5Ui.text(this,"No hay campañas todavía.",13,V5Ui.MUTED,false));page.addView(empty);}for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c!=null)page.addView(campaignCard(c),bottom(V5Ui.dp(this,8)));}page.addView(action("Crear o configurar campañas",true,()->startActivity(new Intent(this,PromotionsSimpleActivity.class))),top(V5Ui.dp(this,10)));}

    private View campaignCard(JSONObject c){LinearLayout card=V5Ui.card(this);card.setOnClickListener(v->campaignDetail(c));LinearLayout top=V5Ui.row(this);top.setGravity(Gravity.CENTER_VERTICAL);LinearLayout copy=V5Ui.column(this);copy.addView(V5Ui.kicker(this,c.optString("type","PROMOCIÓN").toUpperCase(Locale.ROOT)));TextView name=V5Ui.text(this,c.optString("name","Promoción"),15,V5Ui.INK,true);name.setPadding(0,V5Ui.dp(this,5),0,0);copy.addView(name);top.addView(copy,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));boolean active=c.optBoolean("active",false);top.addView(V5Ui.pill(this,active?"Activa":"Pausada",active?V5Ui.LIME_SOFT:Color.rgb(239,239,235),active?V5Ui.GREEN:V5Ui.MUTED));card.addView(top);JSONObject s=c.optJSONObject("stats");String stats=s==null?"Sin estadísticas":s.optInt("plays",0)+" jugadas · "+s.optInt("winners",0)+" premios";TextView meta=V5Ui.text(this,stats,11.5f,V5Ui.MUTED,false);meta.setPadding(0,V5Ui.dp(this,8),0,0);card.addView(meta);String schedule=scheduleSummary(c);if(!schedule.isEmpty()){TextView sc=V5Ui.text(this,schedule,10,V5Ui.FAINT,false);sc.setPadding(0,V5Ui.dp(this,4),0,0);card.addView(sc);}return card;}

    private void campaignDetail(JSONObject c){page.removeAllViews();TextView back=V5Ui.text(this,"‹  Campañas",12,V5Ui.GREEN,true);back.setPadding(0,V5Ui.dp(this,4),0,V5Ui.dp(this,14));back.setOnClickListener(v->showCampaigns());page.addView(back);page.addView(V5Ui.kicker(this,c.optString("type","PROMOCIÓN").toUpperCase(Locale.ROOT)));TextView title=V5Ui.title(this,c.optString("name","Promoción"));title.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,12));page.addView(title);LinearLayout summary=V5Ui.softCard(this);summary.addView(V5Ui.text(this,c.optBoolean("active",false)?"● Activa":"● Pausada",12,c.optBoolean("active",false)?V5Ui.GREEN:V5Ui.WARNING,true));summary.addView(V5Ui.text(this,scheduleSummary(c),12,V5Ui.MUTED,false));JSONObject s=c.optJSONObject("stats");if(s!=null){TextView st=V5Ui.text(this,s.optInt("plays",0)+" jugadas · "+s.optInt("winners",0)+" premios",13,V5Ui.INK,true);st.setPadding(0,V5Ui.dp(this,8),0,0);summary.addView(st);}page.addView(summary);if(c.optBoolean("active",false))page.addView(action("Generar QR real",true,()->issueRealQr(c)),top(V5Ui.dp(this,10)));page.addView(action("Abrir configuración completa",false,()->startActivity(new Intent(this,PromotionsSimpleActivity.class))),top(V5Ui.dp(this,8)));}

    private void showQrList(){base("CAMPAÑAS");TextView title=V5Ui.text(this,"Generar invitación real",20,V5Ui.INK,true);title.setPadding(0,V5Ui.dp(this,12),0,V5Ui.dp(this,5));page.addView(title);page.addView(V5Ui.text(this,"Cada QR se registra en el servidor, dura 48 h y permite una sola jugada.",12,V5Ui.MUTED,false));int n=0;for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c==null||!c.optBoolean("active",false))continue;n++;LinearLayout card=V5Ui.card(this);card.addView(V5Ui.text(this,c.optString("name","Promoción"),15,V5Ui.INK,true));TextView meta=V5Ui.text(this,scheduleSummary(c),10,V5Ui.MUTED,false);meta.setPadding(0,V5Ui.dp(this,5),0,V5Ui.dp(this,8));card.addView(meta);card.addView(action("Generar QR",true,()->issueRealQr(c)));page.addView(card,top(V5Ui.dp(this,8)));}if(n==0){LinearLayout empty=V5Ui.softCard(this);empty.addView(V5Ui.text(this,"No hay promociones activas.",13,V5Ui.MUTED,false));page.addView(empty,top(V5Ui.dp(this,10)));}}

    private void issueRealQr(JSONObject c){if(!core.configured()){alert("Falta conexión","Configura Apps Script en Ajustes.");return;}io.execute(()->{try{JSONObject r=core.post(core.action("promoPublicIssue").put("id",c.optString("id","")).put("expiresHours",48));String url=r.optString("url","").trim(),token=r.optString("token","").trim();if(!url.startsWith("https://")||token.isEmpty())throw new Exception("El servidor no devolvió una invitación válida.");runOnUiThread(()->{Intent i=new Intent(this,TicketPreviewActivity.class).putExtra("title",c.optString("name","Promoción")).putExtra("subtitle",c.optString("type","").toUpperCase(Locale.ROOT)).putExtra("body","ESCANEA PARA JUGAR\nQR REAL · UN SOLO USO · 48 H").putExtra("qr",url).putExtra("type","Promoción QR").putExtra("reference",token).putExtra("detail","Invitación real · "+c.optString("name","")).putExtra("template",c.optString("ticketTemplate","Promoción Premium"));startActivity(i);});}catch(Exception e){runOnUiThread(()->alert("No se pudo generar el QR real",msg(e)));}});}

    private void showPrizes(){base("PREMIOS");TextView status=V5Ui.text(this,prizeCount()+" premios",11,V5Ui.MUTED,false);status.setPadding(0,V5Ui.dp(this,12),0,V5Ui.dp(this,8));page.addView(status);int n=0;for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p==null||"P000".equals(p.optString("id")))continue;n++;LinearLayout c=V5Ui.card(this);LinearLayout top=V5Ui.row(this);top.addView(V5Ui.text(this,p.optString("name","Premio"),15,V5Ui.INK,true),new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));top.addView(V5Ui.pill(this,p.optBoolean("active",true)?"Activo":"Pausado",p.optBoolean("active",true)?V5Ui.LIME_SOFT:Color.rgb(239,239,235),p.optBoolean("active",true)?V5Ui.GREEN:V5Ui.MUTED));c.addView(top);String remain=String.valueOf(p.opt("remaining"));if(remain.equals("null")||remain.isEmpty())remain="sin límite";TextView m=V5Ui.text(this,"Restante: "+remain+" · canjeados: "+p.optInt("redeemed",0),11,V5Ui.MUTED,false);m.setPadding(0,V5Ui.dp(this,7),0,0);c.addView(m);page.addView(c,bottom(V5Ui.dp(this,8)));}if(n==0){LinearLayout empty=V5Ui.softCard(this);empty.addView(V5Ui.text(this,"No hay premios configurados.",13,V5Ui.MUTED,false));page.addView(empty);}page.addView(action("Gestionar premios",true,()->startActivity(new Intent(this,PromotionsSimpleActivity.class))),top(V5Ui.dp(this,10)));}

    private void showRedeem(){base("CANJES");TextView title=V5Ui.text(this,"Validar y canjear",20,V5Ui.INK,true);title.setPadding(0,V5Ui.dp(this,12),0,V5Ui.dp(this,4));page.addView(title);page.addView(V5Ui.text(this,"Escanea el QR o introduce el código ganador.",12,V5Ui.MUTED,false));page.addView(action("Escanear QR",true,this::scan),top(V5Ui.dp(this,10)));redeemInput=new EditText(this);redeemInput.setHint("OF-XXXXX-XXXXX");redeemInput.setTextSize(15);redeemInput.setTextColor(V5Ui.INK);redeemInput.setHintTextColor(V5Ui.FAINT);redeemInput.setPadding(V5Ui.dp(this,13),0,V5Ui.dp(this,13),0);redeemInput.setBackground(V5Ui.bg(this,V5Ui.SURFACE,14));page.addView(redeemInput,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,V5Ui.dp(this,50)));page.addView(action("Validar código",false,()->validateCode(redeemInput.getText().toString())),top(V5Ui.dp(this,8)));redeemResult=V5Ui.text(this,"Todavía no hay ningún código validado.",12,V5Ui.MUTED,false);redeemResult.setPadding(V5Ui.dp(this,14),V5Ui.dp(this,13),V5Ui.dp(this,14),V5Ui.dp(this,13));redeemResult.setBackground(V5Ui.bg(this,V5Ui.SURFACE_SOFT,16));page.addView(redeemResult,top(V5Ui.dp(this,10)));redeemButton=action("Confirmar canje",true,this::confirmRedeem);redeemButton.setVisibility(View.GONE);page.addView(redeemButton,top(V5Ui.dp(this,9)));}

    private void scan(){IntentIntegrator i=new IntentIntegrator(this);i.setDesiredBarcodeFormats(Collections.singletonList("QR_CODE"));i.setPrompt("Escanea el premio");i.setBeepEnabled(false);i.setOrientationLocked(true);i.initiateScan();}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){IntentResult r=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(r!=null){if(r.getContents()!=null){String code=PromoRules.cleanCode(r.getContents());if(redeemInput==null)showRedeem();redeemInput.setText(code);validateCode(code);}return;}super.onActivityResult(requestCode,resultCode,data);}
    private void validateCode(String raw){String code=PromoRules.cleanCode(raw);validatedCode="";if(code.isEmpty()){toast("Código vacío");return;}redeemResult.setText("Validando…");redeemButton.setVisibility(View.GONE);io.execute(()->{try{JSONObject r=core.post(core.action("promotionValidate").put("code",code));boolean can=r.optBoolean("canRedeem",false);String finalCode=r.optString("code",code);runOnUiThread(()->{validatedCode=can?finalCode:"";redeemResult.setText("Premio: "+dash(r.optString("prize",""))+"\nEstado: "+dash(r.optString("state",""))+"\nPromoción: "+dash(r.optString("promotionName",""))+"\nCódigo: "+finalCode+(can?"\n\nLISTO PARA CANJEAR":"\n\nNo se puede canjear"));redeemResult.setTextColor(can?V5Ui.GREEN:V5Ui.ERROR);redeemButton.setVisibility(can?View.VISIBLE:View.GONE);});}catch(Exception e){runOnUiThread(()->{redeemResult.setText("No válido · "+msg(e));redeemResult.setTextColor(V5Ui.ERROR);});}});}
    private void confirmRedeem(){if(validatedCode.isEmpty())return;String code=validatedCode;new AlertDialog.Builder(this).setTitle("Confirmar canje").setMessage("El código quedará inutilizado después de entregar el premio.").setNegativeButton("Cancelar",null).setPositiveButton("CANJEAR",(d,w)->io.execute(()->{try{JSONObject r=core.post(core.action("promotionRedeem").put("code",code));runOnUiThread(()->{validatedCode="";redeemResult.setText("CANJEADO\n"+r.optString("prize","Premio")+"\nCódigo: "+r.optString("code",code));redeemResult.setTextColor(V5Ui.GREEN);redeemButton.setVisibility(View.GONE);toast("Canje registrado");});}catch(Exception e){runOnUiThread(()->alert("No se pudo canjear",msg(e)));}})).show();}

    private void refreshData(){if(!core.configured())return;io.execute(()->{try{JSONObject r=core.post(core.action("promotionList"));JSONArray a=r.optJSONArray("items");if(a!=null){campaigns=a;core.saveArray(CACHE_CAMPAIGNS,a);}}catch(Exception ignored){}});io.execute(()->{try{JSONObject r=core.post(core.action("promotionPrizeList"));JSONArray a=r.optJSONArray("items");if(a!=null){prizes=a;core.saveArray(CACHE_PRIZES,a);}}catch(Exception ignored){}});}
    private int activeCount(){int n=0;for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c!=null&&c.optBoolean("active",false))n++;}return n;}private int prizeCount(){int n=0;for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p!=null&&!"P000".equals(p.optString("id")))n++;}return n;}
    private String scheduleSummary(JSONObject c){String sd=c.optString("startDate","").trim(),ed=c.optString("endDate","").trim(),st=c.optString("startTime",""),et=c.optString("endTime","");String date=sd.isEmpty()&&ed.isEmpty()?"":sd.isEmpty()?"Hasta "+ed:ed.isEmpty()?"Desde "+sd:sd+" → "+ed;String hours=st.isEmpty()&&et.isEmpty()?"":st+"–"+et;return(date+(date.isEmpty()||hours.isEmpty()?"":" · ")+hours).trim();}
    private TextView action(String label,boolean primary,Runnable run){TextView t=V5Ui.text(this,label,11,primary?Color.WHITE:V5Ui.GREEN,true);t.setGravity(Gravity.CENTER);t.setBackground(V5Ui.bg(this,primary?V5Ui.GREEN:V5Ui.SURFACE,15));t.setOnClickListener(v->run.run());t.setMinHeight(V5Ui.dp(this,44));return t;}private TextView section(String value){TextView t=V5Ui.kicker(this,value);t.setPadding(V5Ui.dp(this,1),V5Ui.dp(this,18),0,V5Ui.dp(this,8));return t;}private String label(String s){return s.substring(0,1)+s.substring(1).toLowerCase(Locale.ROOT);}private String dash(String s){return s==null||s.trim().isEmpty()?"—":s.trim();}private String msg(Throwable t){String m=t==null?"Error desconocido":t.getMessage();return m==null||m.trim().isEmpty()?String.valueOf(t):m;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void alert(String t,String m){if(!isFinishing())new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Aceptar",null).show();}
    private void quickActions(){String[] items={"Nueva reserva","Generar QR promocional","Canjear premio","Imprimir ticket"};new AlertDialog.Builder(this).setTitle("Acción rápida").setItems(items,(d,w)->{if(w==0)startActivity(new Intent(this,ReservationsV5Activity.class).putExtra("openNew",true));else if(w==1)showQrList();else if(w==2)showRedeem();else startActivity(new Intent(this,TicketPreviewActivity.class).putExtra("type","Libre"));}).show();}
    private LinearLayout.LayoutParams weightGap(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1);p.setMargins(V5Ui.dp(this,4),0,V5Ui.dp(this,4),0);return p;}private LinearLayout.LayoutParams top(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=v;return p;}private LinearLayout.LayoutParams bottom(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=v;return p;}
}
