package com.ofaro.participaciones;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class PromotionsActivity extends Activity {
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private AppCore core; private LinearLayout page; private TextView subtitle;
    private JSONArray campaigns=new JSONArray(),prizes=new JSONArray();
    private EditText redeemInput; private TextView redeemResult; private Button redeemAction; private String validatedCode="";

    @Override protected void onCreate(Bundle b){super.onCreate(b);core=new AppCore(this);setContentView(buildRoot());showCampaigns();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}

    private View buildRoot(){
        LinearLayout root=col();root.setBackgroundColor(Color.rgb(246,245,242));
        LinearLayout head=col();head.setPadding(dp(18),dp(15),dp(18),dp(13));head.setBackgroundColor(Color.rgb(15,15,15));head.addView(text("O FARO",23,Color.WHITE,true));subtitle=text("Promociones",13,Color.LTGRAY,false);head.addView(subtitle);root.addView(head);
        LinearLayout nav=row();nav.setPadding(dp(6),dp(6),dp(6),dp(6));nav.setBackgroundColor(Color.WHITE);
        Button home=nav("‹ INICIO"),camp=nav("CAMPAÑAS"),pri=nav("PREMIOS"),red=nav("CANJEAR");home.setOnClickListener(v->finish());camp.setOnClickListener(v->showCampaigns());pri.setOnClickListener(v->showPrizes());red.setOnClickListener(v->showRedeem());nav.addView(home,w48());nav.addView(camp,w48());nav.addView(pri,w48());nav.addView(red,w48());root.addView(nav);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);page=col();page.setPadding(dp(14),dp(15),dp(14),dp(30));scroll.addView(page);root.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));return root;
    }

    private void showCampaigns(){
        clear("Promociones");LinearLayout top=row();top.addView(title("Campañas y sorteos"),new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));Button add=primary("+ NUEVA");add.setOnClickListener(v->editCampaign(null));top.addView(add,new LinearLayout.LayoutParams(dp(108),dp(48)));page.addView(top);page.addView(paragraph("El cliente recibe un QR único, lo escanea y juega en su móvil. La APK gestiona campaña, premio, QR y canje."));
        TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=col();page.addView(list,topWrap(dp(9)));
        loadAll(status,()->{status.setText(campaigns.length()+" campañas configuradas");list.removeAllViews();for(int i=0;i<campaigns.length();i++){JSONObject c=campaigns.optJSONObject(i);if(c!=null)campaignCard(list,c);}if(campaigns.length()==0)list.addView(empty("No hay campañas."));});
        Button hist=secondary("HISTORIAL Y ESTADÍSTICAS");hist.setOnClickListener(v->showHistory());page.addView(hist,top(dp(13)));
    }

    private void campaignCard(LinearLayout host,JSONObject c){
        LinearLayout card=card();String type=str(c,"type","TIPO_PROMOCION","Promoción"),name=str(c,"name","NOMBRE","Promoción"),desc=str(c,"description","DESCRIPCION","Sin descripción");boolean active=bool(c,"active","ACTIVA");
        LinearLayout line=row();LinearLayout l=col();l.addView(text(type.toUpperCase(Locale.ROOT),11,Color.GRAY,true));l.addView(text(name,20,Color.rgb(20,20,20),true));l.addView(text(desc,14,Color.DKGRAY,false));line.addView(l,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));TextView state=text(active?"ACTIVA":"PAUSADA",12,active?Color.rgb(28,110,58):Color.rgb(150,100,18),true);state.setPadding(dp(8),dp(5),dp(8),dp(5));line.addView(state);card.addView(line);
        TextView meta=text(fmtNum(num(c,"winProbability","PROB_GANAR"))+"% ganar · "+str(c,"ticketTemplate","PLANTILLA_TICKET","Estándar"),13,Color.DKGRAY,false);meta.setPadding(0,dp(8),0,dp(9));card.addView(meta);
        LinearLayout r1=row();Button edit=small("EDITAR");edit.setOnClickListener(v->editCampaign(c));Button toggle=small(active?"PAUSAR":"ACTIVAR");toggle.setOnClickListener(v->toggle(c,toggle));r1.addView(edit,w());r1.addView(toggle,w());card.addView(r1);
        LinearLayout r2=row();Button cfg=small(type.equalsIgnoreCase("Ruleta")?"SEGMENTOS":"PREMIOS");cfg.setOnClickListener(v->{if(type.equalsIgnoreCase("Ruleta"))wheelEditor(c);else prizeLinks(c);});Button qr=small("QR CLIENTE");qr.setEnabled(active);qr.setOnClickListener(v->issueQr(c,qr));r2.addView(cfg,w());r2.addView(qr,w());card.addView(r2,topWrap(dp(7)));
        Button test=secondary("PROBAR RESULTADO INTERNO");test.setEnabled(active);test.setOnClickListener(v->testPlay(c,test));card.addView(test,top(dp(8)));host.addView(card,bottom(dp(9)));
    }

    private void loadAll(TextView status,Runnable done){
        if(!requireApi())return;io.execute(()->{try{JSONObject c=core.post(core.action("promotionList"));core.ensureOk(c);JSONObject p=core.post(core.action("prizeList").put("includeNoPrize",true));core.ensureOk(p);campaigns=arr(c);prizes=arr(p);saveCache("promo_campaigns",campaigns);saveCache("promo_prizes",prizes);runOnUiThread(done);}catch(Exception e){JSONArray cc=cache("promo_campaigns"),pp=cache("promo_prizes");if(cc.length()>0){campaigns=cc;prizes=pp;runOnUiThread(()->{status.setText("Sin conexión · datos guardados");done.run();});}else runOnUiThread(()->status.setText("Error: "+msg(e)));}});}

    private void toggle(JSONObject c,Button b){b.setEnabled(false);boolean active=bool(c,"active","ACTIVA");io.execute(()->{try{JSONObject r=core.post(core.action("promotionToggle").put("id",id(c)).put("active",!active));core.ensureOk(r);runOnUiThread(()->{toast(active?"Campaña pausada":"Campaña activada");showCampaigns();});}catch(Exception e){runOnUiThread(()->{b.setEnabled(true);alert("Estado",msg(e));});}});}

    private void editCampaign(JSONObject original){
        boolean isNew=original==null;JSONObject x=isNew?new JSONObject():original;
        ScrollView scroll=new ScrollView(this);LinearLayout box=col();box.setPadding(dp(16),dp(5),dp(16),dp(10));scroll.addView(box);
        EditText name=field(box,"Nombre",str(x,"name","NOMBRE",""));EditText desc=multi(box,"Descripción",str(x,"description","DESCRIPCION",""),3);
        Spinner type=spinner(box,"Tipo",new String[]{"Ruleta","Premio directo","Rasca","Código premiado"},str(x,"type","TIPO_PROMOCION","Ruleta"));
        EditText prob=field(box,"Probabilidad general de ganar (%)",fmtNum(num(x,"winProbability","PROB_GANAR")));prob.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);
        EditText start=field(box,"Fecha inicio · AAAA-MM-DD",str(x,"startDate","FECHA_INICIO",""));EditText end=field(box,"Fecha fin · AAAA-MM-DD",str(x,"endDate","FECHA_FIN",""));EditText startTime=field(box,"Hora inicio",str(x,"startTime","HORA_INICIO","12:00"));EditText endTime=field(box,"Hora fin",str(x,"endTime","HORA_FIN","23:59"));EditText days=field(box,"Días activos",str(x,"activeDays","DIAS_ACTIVOS","Lun,Mar,Mié,Jue,Vie,Sáb,Dom"));EditText client=field(box,"Límite por cliente",str(x,"clientLimit","LIMITE_POR_CLIENTE","1"));EditText daily=field(box,"Límite diario",str(x,"dailyLimit","LIMITE_POR_DIA","500"));EditText win=multi(box,"Mensaje ganador",str(x,"winnerMessage","MENSAJE_GANA","¡Enhorabuena! Te ha tocado {{premio}}."),2);EditText lose=multi(box,"Mensaje sin premio",str(x,"loserMessage","MENSAJE_NO_GANA","Esta vez no ha habido premio."),2);
        Spinner tpl=spinner(box,"Plantilla del ticket",new String[]{"Promoción Premium","Promoción Clásica","Entrada QR","Ruleta QR","Rasca QR","Premio Canjeable","Cupón Descuento","Minimal Premium"},str(x,"ticketTemplate","PLANTILLA_TICKET","Promoción Premium"));Spinner state=spinner(box,"Estado",new String[]{"Pausada","Activa"},bool(x,"active","ACTIVA")?"Activa":"Pausada");
        AlertDialog dialog=new AlertDialog.Builder(this).setTitle(isNew?"Nueva promoción":"Editar promoción").setView(scroll).setNegativeButton("Cancelar",null).setPositiveButton("GUARDAR",null).create();
        dialog.setOnShowListener(di->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{
            if(val(name).isEmpty()){toast("Escribe el nombre");return;}Button save=dialog.getButton(AlertDialog.BUTTON_POSITIVE);save.setEnabled(false);JSONObject p=new JSONObject();try{boolean active="Activa".equals(selected(state));p.put("ID_PROMOCION",isNew?"":id(x));p.put("NOMBRE",val(name));p.put("DESCRIPCION",val(desc));p.put("TIPO_PROMOCION",selected(type));p.put("ESTADO",active?"Activa":"Pausada");p.put("ACTIVA",active?"Sí":"No");p.put("FECHA_INICIO",val(start));p.put("FECHA_FIN",val(end));p.put("HORA_INICIO",val(startTime));p.put("HORA_FIN",val(endTime));p.put("DIAS_ACTIVOS",val(days));p.put("PROB_GANAR",dbl(val(prob),0));p.put("MENSAJE_GANA",val(win));p.put("MENSAJE_NO_GANA",val(lose));p.put("PLANTILLA_TICKET",selected(tpl));p.put("LIMITE_POR_CLIENTE",val(client));p.put("LIMITE_POR_DIA",val(daily));p.put("REQUIERE_CODIGO",selected(type).equals("Código premiado")?"Sí":"No");}catch(Exception ignored){}
            io.execute(()->{try{JSONObject r=core.post(core.action("promotionSave").put("promotion",p));core.ensureOk(r);runOnUiThread(()->{dialog.dismiss();toast("Promoción guardada");showCampaigns();});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);alert("No se pudo guardar",msg(e));});}});
        }));dialog.show();
    }

    private void wheelEditor(JSONObject c){
        clear("Ruleta");back("Segmentos · "+str(c,"name","NOMBRE","Ruleta"),this::showCampaigns);TextView status=text("Cargando segmentos…",14,Color.DKGRAY,false);page.addView(status);LinearLayout rows=col();page.addView(rows,topWrap(dp(8)));List<SegmentRow> views=new ArrayList<>();Button add=secondary("+ AÑADIR SEGMENTO");Button save=primary("GUARDAR RULETA");page.addView(add,top(dp(8)));page.addView(save,top(dp(8)));
        io.execute(()->{try{JSONObject r=core.post(core.action("wheelSegmentsList").put("promotionId",id(c)));core.ensureOk(r);JSONArray a=arr(r);runOnUiThread(()->{status.setText("La suma debe ser exactamente 100%.");for(int i=0;i<a.length();i++)segmentRow(rows,views,a.optJSONObject(i));if(a.length()==0)segmentRow(rows,views,new JSONObject());});}catch(Exception e){runOnUiThread(()->status.setText("Error: "+msg(e)));}});
        add.setOnClickListener(v->segmentRow(rows,views,new JSONObject()));save.setOnClickListener(v->{JSONArray items=new JSONArray();double total=0;int order=1;for(SegmentRow s:views){if(s.root.getParent()==null)continue;double pct=dbl(val(s.pct),0);total+=pct;String pid=prizeId(selected(s.prize));JSONObject o=new JSONObject();try{o.put("label",val(s.label));o.put("prizeId",pid);o.put("percent",pct);o.put("active",true);o.put("order",order++);o.put("resultType","P000".equals(pid)?"SIN_PREMIO":"PREMIO");o.put("style","premium");}catch(Exception ignored){}items.put(o);}if(Math.abs(total-100d)>.001){alert("Probabilidades","Suman "+fmtNum(total)+"%. Deben sumar 100%.");return;}save.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("wheelSegmentsSave").put("promotionId",id(c)).put("items",items));core.ensureOk(r);runOnUiThread(()->{toast("Ruleta guardada");showCampaigns();});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);alert("Ruleta",msg(e));});}});});
    }
    private static class SegmentRow{LinearLayout root;EditText label,pct;Spinner prize;}
    private void segmentRow(LinearLayout host,List<SegmentRow> all,JSONObject x){SegmentRow s=new SegmentRow();s.root=card();s.label=field(s.root,"Texto del sector",str(x,"label","ETIQUETA","NUEVO"));s.prize=spinner(s.root,"Premio",prizeNames(),prizeName(str(x,"prizeId","ID_PREMIO","P000")));s.pct=field(s.root,"Probabilidad %",fmtNum(num3(x,"percentage","PORCENTAJE","percent")));s.pct.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);Button del=secondary("ELIMINAR SECTOR");del.setOnClickListener(v->host.removeView(s.root));s.root.addView(del,top(dp(7)));host.addView(s.root,bottom(dp(8)));all.add(s);}

    private void prizeLinks(JSONObject c){
        clear("Premios");back("Premios · "+str(c,"name","NOMBRE","Promoción"),this::showCampaigns);TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=col();page.addView(list,topWrap(dp(8)));List<LinkRow> links=new ArrayList<>();Button save=primary("GUARDAR PREMIOS");page.addView(save,top(dp(10)));
        io.execute(()->{try{JSONObject r=core.post(core.action("promotionPrizeLinksList").put("promotionId",id(c)));core.ensureOk(r);JSONArray current=arr(r);runOnUiThread(()->{status.setText("Marca los premios y asigna su peso relativo.");for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p==null||"P000".equals(id(p)))continue;JSONObject old=findLink(current,id(p));LinkRow lr=new LinkRow();lr.id=id(p);lr.check=new CheckBox(this);lr.check.setText(str(p,"name","NOMBRE","Premio"));lr.check.setChecked(old!=null);lr.weight=input(old==null?"1":str(old,"PESO","weight","1"));lr.weight.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);LinearLayout rr=row();rr.addView(lr.check,new LinearLayout.LayoutParams(0,dp(52),1));rr.addView(lr.weight,new LinearLayout.LayoutParams(dp(90),dp(52)));list.addView(rr,bottom(dp(5)));links.add(lr);}});}catch(Exception e){runOnUiThread(()->status.setText("Error: "+msg(e)));}});
        save.setOnClickListener(v->{JSONArray items=new JSONArray();int order=1;for(LinkRow l:links)if(l.check.isChecked()){JSONObject o=new JSONObject();try{o.put("prizeId",l.id);o.put("weight",dbl(val(l.weight),1));o.put("active",true);o.put("order",order++);}catch(Exception ignored){}items.put(o);}if(items.length()==0){alert("Premios","Selecciona al menos un premio.");return;}save.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("promotionPrizeLinksSave").put("promotionId",id(c)).put("items",items));core.ensureOk(r);runOnUiThread(()->{toast("Premios guardados");showCampaigns();});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);alert("Premios",msg(e));});}});});
    }
    private static class LinkRow{String id;CheckBox check;EditText weight;}

    private void issueQr(JSONObject c,Button b){
        b.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("promoPublicIssue").put("id",id(c)).put("expiresHours",48));core.ensureOk(r);String url=r.optString("url","");String name=str(c,"name","NOMBRE","Promoción"),type=str(c,"type","TIPO_PROMOCION","Promoción");runOnUiThread(()->{b.setEnabled(true);Intent i=new Intent(this,TicketPreviewActivity.class);i.putExtra("title",name);i.putExtra("subtitle",type.toUpperCase(Locale.ROOT));i.putExtra("body","ESCANEA PARA JUGAR\nQR único de un solo uso.");i.putExtra("qr",url);i.putExtra("type","Promoción QR");i.putExtra("reference",r.optString("token",""));i.putExtra("detail","QR cliente · "+name);i.putExtra("template",type.equalsIgnoreCase("Ruleta")?"Ruleta QR":type.equalsIgnoreCase("Rasca")?"Rasca QR":"Entrada QR");startActivity(i);});}catch(Exception e){runOnUiThread(()->{b.setEnabled(true);alert("QR cliente",msg(e));});}});
    }

    private void testPlay(JSONObject c,Button b){b.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("promotionPlay").put("promotionId",id(c)));core.ensureOk(r);runOnUiThread(()->{b.setEnabled(true);boolean won=r.optBoolean("won",false);String prize=won?r.optString("prize","Premio"):"SIN PREMIO";new AlertDialog.Builder(this).setTitle(prize).setMessage(r.optString("message","")+"\n\nCódigo: "+r.optString("code","")).setNegativeButton("Cerrar",null).setPositiveButton("TICKET",(d,w)->{Intent i=new Intent(this,TicketPreviewActivity.class);i.putExtra("title",r.optString("promotionName",str(c,"name","NOMBRE","Promoción")));i.putExtra("subtitle",prize);i.putExtra("body",r.optString("message","")+"\n\nCódigo: "+r.optString("code",""));i.putExtra("qr",r.optString("qrPayload",r.optString("code","")));i.putExtra("type","Promoción");startActivity(i);}).show();});}catch(Exception e){runOnUiThread(()->{b.setEnabled(true);alert("Prueba",msg(e));});}});}

    private void showPrizes(){
        clear("Premios");LinearLayout top=row();top.addView(title("Premios"),new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));Button add=primary("+ NUEVO");add.setOnClickListener(v->editPrize(null));top.addView(add,new LinearLayout.LayoutParams(dp(108),dp(48)));page.addView(top);TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=col();page.addView(list,topWrap(dp(8)));
        io.execute(()->{try{JSONObject r=core.post(core.action("prizeList").put("includeNoPrize",true));core.ensureOk(r);prizes=arr(r);saveCache("promo_prizes",prizes);runOnUiThread(()->{int n=0;for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p==null||"P000".equals(id(p)))continue;n++;LinearLayout c=card();c.addView(text(str(p,"name","NOMBRE","Premio"),19,Color.rgb(20,20,20),true));c.addView(text(str(p,"type","TIPO","Premio")+" · Stock: "+str3(p,"stockRemaining","STOCK_RESTANTE","stock","∞"),13,Color.DKGRAY,false));Button e=secondary("EDITAR PREMIO");e.setOnClickListener(v->editPrize(p));c.addView(e,top(dp(7)));list.addView(c,bottom(dp(8)));}status.setText(n+" premios configurados");});}catch(Exception e){runOnUiThread(()->status.setText("Error: "+msg(e)));}});
    }

    private void editPrize(JSONObject original){
        boolean isNew=original==null;JSONObject x=isNew?new JSONObject():original;ScrollView scroll=new ScrollView(this);LinearLayout box=col();box.setPadding(dp(16),dp(5),dp(16),dp(10));scroll.addView(box);EditText name=field(box,"Nombre",str(x,"name","NOMBRE",""));Spinner type=spinner(box,"Tipo",new String[]{"Producto gratis","Descuento","Vale","Premio físico","Otro"},str(x,"type","TIPO","Producto gratis"));EditText stock=field(box,"Stock",str(x,"stock","STOCK",""));stock.setInputType(InputType.TYPE_CLASS_NUMBER);EditText ticket=multi(box,"Texto del ticket",str(x,"ticketDescription","DESCRIPCION_TICKET",""),3);EditText conditions=multi(box,"Condiciones",str(x,"conditions","CONDICIONES",""),3);EditText value=field(box,"Valor",str(x,"value","VALOR",""));Spinner active=spinner(box,"Activo",new String[]{"Sí","No"},bool(x,"active","ACTIVO")?"Sí":"No");AlertDialog dialog=new AlertDialog.Builder(this).setTitle(isNew?"Nuevo premio":"Editar premio").setView(scroll).setNegativeButton("Cancelar",null).setPositiveButton("GUARDAR",null).create();dialog.setOnShowListener(di->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{if(val(name).isEmpty()){toast("Escribe el nombre");return;}Button save=dialog.getButton(AlertDialog.BUTTON_POSITIVE);save.setEnabled(false);JSONObject p=new JSONObject();try{p.put("id",isNew?"":id(x));p.put("name",val(name));p.put("type",selected(type));p.put("stock",val(stock));p.put("ticketDescription",val(ticket));p.put("conditions",val(conditions));p.put("value",val(value));p.put("active",selected(active));p.put("weight",num(x,"weight","PESO"));p.put("order",num(x,"order","ORDEN"));}catch(Exception ignored){}io.execute(()->{try{JSONObject r=core.post(core.action("prizeSave").put("prize",p));core.ensureOk(r);runOnUiThread(()->{dialog.dismiss();toast("Premio guardado");showPrizes();});}catch(Exception e){runOnUiThread(()->{save.setEnabled(true);alert("Premio",msg(e));});}});}));dialog.show();
    }

    private void showRedeem(){
        clear("Canjear");page.addView(title("Validar y canjear"));page.addView(paragraph("Escanea un QR/código de premio o escríbelo manualmente."));Button scan=primary("ESCANEAR QR");scan.setOnClickListener(v->scan());page.addView(scan);redeemInput=input("");redeemInput.setHint("PR-XXXXX-XXXXX");page.addView(redeemInput,top(dp(10)));Button validate=secondary("VALIDAR CÓDIGO");validate.setOnClickListener(v->validate(val(redeemInput)));page.addView(validate,top(dp(8)));redeemResult=text("Sin código validado",15,Color.DKGRAY,false);redeemResult.setPadding(dp(12),dp(12),dp(12),dp(12));redeemResult.setBackground(box(Color.WHITE,12,Color.rgb(220,220,220),1));page.addView(redeemResult,topWrap(dp(10)));redeemAction=primary("CANJEAR PREMIO");redeemAction.setVisibility(View.GONE);redeemAction.setOnClickListener(v->confirmRedeem());page.addView(redeemAction,top(dp(9)));
    }
    private void scan(){IntentIntegrator i=new IntentIntegrator(this);i.setDesiredBarcodeFormats(java.util.Collections.singletonList("QR_CODE"));i.setPrompt("Escanea el código del premio");i.setBeepEnabled(false);i.setOrientationLocked(true);i.initiateScan();}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){IntentResult r=IntentIntegrator.parseActivityResult(requestCode,resultCode,data);if(r!=null){if(r.getContents()!=null){String raw=cleanPromoCode(r.getContents());if(redeemInput==null)showRedeem();redeemInput.setText(raw);validate(raw);}return;}super.onActivityResult(requestCode,resultCode,data);}
    private void validate(String code){code=cleanPromoCode(code);if(code.isEmpty()){toast("Código vacío");return;}String finalCode=code;redeemResult.setText("Validando…");redeemAction.setVisibility(View.GONE);io.execute(()->{try{JSONObject r=core.post(core.action("promotionValidate").put("code",finalCode));core.ensureOk(r);validatedCode=r.optString("code",finalCode);runOnUiThread(()->{redeemResult.setText("Estado: "+r.optString("state","")+"\nPremio: "+r.optString("prize","Sin premio")+"\nPromoción: "+r.optString("promotionName","")+"\nCódigo: "+validatedCode);redeemAction.setVisibility(r.optBoolean("canRedeem",false)?View.VISIBLE:View.GONE);});}catch(Exception e){runOnUiThread(()->redeemResult.setText("No válido: "+msg(e)));}});}
    private void confirmRedeem(){if(validatedCode.isEmpty())return;new AlertDialog.Builder(this).setTitle("Confirmar canje").setMessage("El código quedará inutilizado. ¿Entregar el premio ahora?").setNegativeButton("Cancelar",null).setPositiveButton("CANJEAR",(d,w)->{redeemAction.setEnabled(false);io.execute(()->{try{JSONObject r=core.post(core.action("promotionRedeem").put("code",validatedCode));core.ensureOk(r);runOnUiThread(()->{redeemResult.setText("CANJEADO\n"+r.optString("prize","Premio")+"\n"+r.optString("code",validatedCode));redeemAction.setVisibility(View.GONE);redeemAction.setEnabled(true);});}catch(Exception e){runOnUiThread(()->{redeemAction.setEnabled(true);alert("Canje",msg(e));});}});}).show();}

    private void showHistory(){
        clear("Historial");back("Historial de promociones",this::showCampaigns);TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=col();page.addView(list,topWrap(dp(8)));io.execute(()->{try{JSONObject stats=core.post(core.action("promotionStats"));core.ensureOk(stats);JSONObject hist=core.post(core.action("promotionHistory").put("limit",100));core.ensureOk(hist);JSONArray a=arr(hist);runOnUiThread(()->{status.setText("Jugadas: "+stats.optInt("total",0)+" · Premiadas: "+stats.optString("winRate","0")+"% · Canjeadas: "+stats.optInt("redeemed",0));for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;TextView r=text(str(x,"promotionName","PROMOCION","Promoción")+"\n"+str(x,"date","FECHA","")+" · "+str(x,"code","CODIGO","")+"\n"+str3(x,"prize","PREMIO","state",""),14,Color.rgb(30,30,30),false);r.setPadding(dp(12),dp(10),dp(12),dp(10));r.setBackground(box(Color.WHITE,11,Color.rgb(220,220,220),1));list.addView(r,bottom(dp(6)));}});}catch(Exception e){runOnUiThread(()->status.setText("Error: "+msg(e)));}});
    }

    private String cleanPromoCode(String v){String s=v==null?"":v.trim();if(s.startsWith("OFARO:PROMO:"))s=s.substring("OFARO:PROMO:".length());return s;}
    private JSONObject findLink(JSONArray a,String pid){for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null&&pid.equals(str(x,"ID_PREMIO","prizeId","")))return x;}return null;}
    private String[] prizeNames(){List<String> out=new ArrayList<>();for(int i=0;i<prizes.length();i++){JSONObject p=prizes.optJSONObject(i);if(p!=null)out.add(str(p,"name","NOMBRE","Premio")+" ["+id(p)+"]");}if(out.isEmpty())out.add("Sin premio [P000]");return out.toArray(new String[0]);}
    private String prizeName(String id){for(String s:prizeNames())if(s.endsWith("["+id+"]"))return s;return prizeNames()[0];}private String prizeId(String s){int a=s.lastIndexOf('['),b=s.lastIndexOf(']');return a>=0&&b>a?s.substring(a+1,b):"P000";}
    private boolean requireApi(){if(core.configured())return true;alert("Falta configurar la API","Ve a Inicio → Impresora y ajustes.");return false;}
    private JSONArray arr(JSONObject o){JSONArray a=o==null?null:o.optJSONArray("items");return a==null?new JSONArray():a;}private void saveCache(String k,JSONArray a){core.prefs().edit().putString(k,a.toString()).apply();}private JSONArray cache(String k){try{return new JSONArray(core.prefs().getString(k,"[]"));}catch(Exception e){return new JSONArray();}}
    private String id(JSONObject o){return str4(o,"id","ID_PROMOCION","ID_PREMIO","");}private String str(JSONObject o,String a,String b,String def){String v=o==null?"":o.optString(a,"");if(v.isEmpty())v=o==null?"":o.optString(b,"");return v.isEmpty()?def:v;}private String str3(JSONObject o,String a,String b,String c,String def){String v=str(o,a,b,"");if(v.isEmpty())v=o==null?"":o.optString(c,"");return v.isEmpty()?def:v;}private String str4(JSONObject o,String a,String b,String c,String def){return str3(o,a,b,c,def);}private boolean bool(JSONObject o,String a,String b){if(o==null)return false;if(o.has(a)){Object v=o.opt(a);if(v instanceof Boolean)return (Boolean)v;return yes(String.valueOf(v));}return yes(o.optString(b,""));}private boolean yes(String v){String s=v==null?"":v.trim().toLowerCase(Locale.ROOT);return s.equals("sí")||s.equals("si")||s.equals("true")||s.equals("1")||s.equals("activa");}private double num(JSONObject o,String a,String b){if(o==null)return 0;if(o.has(a))return o.optDouble(a,0);return o.optDouble(b,0);}private double num3(JSONObject o,String a,String b,String c){if(o==null)return 0;if(o.has(a))return o.optDouble(a,0);if(o.has(b))return o.optDouble(b,0);return o.optDouble(c,0);}private double dbl(String s,double f){try{return Double.parseDouble(s.trim().replace(',','.'));}catch(Exception e){return f;}}private String fmtNum(double n){return Math.rint(n)==n?String.valueOf((long)n):String.valueOf(n);}

    private void clear(String s){page.removeAllViews();subtitle.setText(s);}private void back(String s,Runnable r){LinearLayout line=row();Button b=secondary("‹ ATRÁS");b.setOnClickListener(v->r.run());line.addView(b,new LinearLayout.LayoutParams(dp(105),dp(48)));TextView t=text(s,20,Color.rgb(20,20,20),true);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(10),0,0,0);line.addView(t,new LinearLayout.LayoutParams(0,dp(48),1));page.addView(line);page.addView(space(dp(8)));}private TextView title(String s){return text(s,27,Color.rgb(20,20,20),true);}private TextView paragraph(String s){TextView t=text(s,15,Color.DKGRAY,false);t.setPadding(0,dp(5),0,dp(12));return t;}private TextView empty(String s){TextView t=text(s,15,Color.DKGRAY,false);t.setPadding(dp(8),dp(20),dp(8),dp(20));return t;}private LinearLayout card(){LinearLayout c=col();c.setPadding(dp(14),dp(13),dp(14),dp(13));c.setBackground(box(Color.WHITE,14,Color.rgb(218,216,212),1));return c;}private LinearLayout col(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);return c;}private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}private Button nav(String s){Button b=secondary(s);b.setTextSize(10);return b;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextSize(13);b.setAllCaps(false);b.setBackground(box(Color.rgb(15,15,15),12,Color.TRANSPARENT,0));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(20,20,20));b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextSize(12);b.setAllCaps(false);b.setBackground(box(Color.WHITE,12,Color.rgb(190,190,190),1));return b;}private Button small(String s){Button b=secondary(s);b.setTextSize(11);return b;}private TextView text(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private EditText input(String v){EditText e=new EditText(this);e.setText(v);e.setTextSize(16);e.setTextColor(Color.rgb(20,20,20));e.setPadding(dp(12),0,dp(12),0);e.setBackground(box(Color.WHITE,10,Color.rgb(205,205,205),1));return e;}private EditText field(LinearLayout p,String l,String v){TextView t=text(l,13,Color.DKGRAY,true);t.setPadding(0,dp(8),0,dp(4));p.addView(t);EditText e=input(v);e.setSingleLine(true);p.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(50)));return e;}private EditText multi(LinearLayout p,String l,String v,int lines){TextView t=text(l,13,Color.DKGRAY,true);t.setPadding(0,dp(8),0,dp(4));p.addView(t);EditText e=input(v);e.setSingleLine(false);e.setMinLines(lines);e.setGravity(Gravity.TOP);e.setPadding(dp(12),dp(9),dp(12),dp(9));p.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));return e;}private Spinner spinner(LinearLayout p,String l,String[] items,String selected){TextView t=text(l,13,Color.DKGRAY,true);t.setPadding(0,dp(8),0,dp(4));p.addView(t);Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,items));p.addView(s,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(50)));for(int i=0;i<items.length;i++)if(items[i].equals(selected)){s.setSelection(i);break;}return s;}private String selected(Spinner s){return s.getSelectedItem()==null?"":String.valueOf(s.getSelectedItem());}private String val(EditText e){return e.getText().toString().trim();}
    private GradientDrawable box(int f,int r,int stroke,int sw){GradientDrawable d=new GradientDrawable();d.setColor(f);d.setCornerRadius(dp(r));if(sw>0)d.setStroke(dp(sw),stroke);return d;}private LinearLayout.LayoutParams w(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(50),1);p.setMargins(dp(3),0,dp(3),0);return p;}private LinearLayout.LayoutParams w48(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(48),1);p.setMargins(dp(2),0,dp(2),0);return p;}private LinearLayout.LayoutParams top(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(52));p.topMargin=v;return p;}private LinearLayout.LayoutParams topWrap(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=v;return p;}private LinearLayout.LayoutParams bottom(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=v;return p;}private View space(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,h));return v;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private String msg(Throwable t){String m=t==null?"Error desconocido":t.getMessage();return m==null||m.trim().isEmpty()?String.valueOf(t):m;}private void alert(String t,String m){if(!isFinishing())new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Aceptar",null).show();}
}
