package com.ofaro.participaciones;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONObject;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class TicketPreviewActivity extends Activity {
    private static final int PICK_IMAGE=4401;
    private static final String[] TEMPLATES={"Reserva Express","Reserva Elegante","Reserva Completa","Reserva Cliente","Promoción Premium","Promoción Clásica","Entrada QR","Ruleta QR","Rasca QR","Premio Canjeable","Vale Regalo","Cupón Descuento","Próxima Visita","QR Carta","QR Menú","QR WiFi","QR Reseñas","QR Instagram","QR Personalizado","Promo del Día","Oferta Flash","Evento Especial","Novedad O Faro","Minimal Premium","Ticket Editorial","Ticket Retro","Texto Libre","Solo Imagen"};
    private static final String[] TYPO={"O Faro","Editorial","Elegante restaurante","Promocional fuerte","Minimal nórdico","Retro ticket"};
    private final ExecutorService io=Executors.newSingleThreadExecutor();private final Handler ui=new Handler(Looper.getMainLooper());
    private AppCore core;private EditText title,subtitle,body,qr,copies;private Spinner template,typography,paper,qrSize,separator,imagePosition,cutMode,feedLines;private SeekBar imageSize,darkness;private TextView imageSizeLabel,darkLabel,printerStatus,status;private ImageView preview;private Bitmap previewBitmap;private String imageData="";private String reference="",detail="",reservationId="",participationCode="",type="Ticket";private int renderGeneration=0;
    private final Runnable previewTask=this::renderNow;

    @Override protected void onCreate(Bundle b){super.onCreate(b);core=new AppCore(this);readIntent();setContentView(build());core.startPrinterWatchdog();refreshPrinterStatus();schedulePreview();}
    @Override protected void onDestroy(){ui.removeCallbacksAndMessages(null);io.shutdownNow();Bitmap old=previewBitmap;previewBitmap=null;if(old!=null&&!old.isRecycled())old.recycle();super.onDestroy();}
    private void readIntent(){Intent i=getIntent();reference=v(i,"reference");detail=v(i,"detail");reservationId=v(i,"reservationId");participationCode=v(i,"participationCode");String t=v(i,"type");if(!t.isEmpty())type=t;}
    private String v(Intent i,String key){String s=i.getStringExtra(key);return s==null?"":s;}

    private View build(){LinearLayout root=col();root.setBackgroundColor(Color.rgb(244,243,239));LinearLayout head=col();head.setPadding(dp(18),dp(16),dp(18),dp(14));head.setBackgroundColor(Color.rgb(15,15,15));head.addView(txt("O FARO",23,Color.WHITE,true));head.addView(txt("Estudio de impresión · ESC/POS local",13,Color.LTGRAY,false));root.addView(head);ScrollView scroll=new ScrollView(this);LinearLayout page=col();page.setPadding(dp(14),dp(14),dp(14),dp(32));scroll.addView(page);root.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));
        printerStatus=cardText("");page.addView(printerStatus);preview=new ImageView(this);preview.setAdjustViewBounds(true);preview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);preview.setBackgroundColor(Color.WHITE);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(390));pp.topMargin=dp(12);page.addView(preview,pp);
        template=spin(page,"Plantilla",TEMPLATES,defaultTemplate());typography=spin(page,"Tipografía",TYPO,"O Faro");
        LinearLayout r1=row();LinearLayout a=col(),b=col();paper=spin(a,"Papel",new String[]{"80 mm","58 mm"},core.printerPaper()==58?"58 mm":"80 mm");qrSize=spin(b,"Tamaño QR",new String[]{"S","M","L","XL"},"L");r1.addView(a,weight());r1.addView(b,weight());page.addView(r1);
        LinearLayout r2=row();LinearLayout c=col(),d=col();separator=spin(c,"Separador",new String[]{"Línea","Puntos","Guiones","Doble","Ninguno"},"Línea");imagePosition=spin(d,"Imagen",new String[]{"No imprimir","Arriba","Abajo"},"No imprimir");r2.addView(c,weight());r2.addView(d,weight());page.addView(r2);
        LinearLayout r3=row();LinearLayout e=col(),f=col();cutMode=spin(e,"Corte",new String[]{"Completo","Parcial","Sin corte"},cutLabel(core.printerCut()));feedLines=spin(f,"Avance",new String[]{"0","1","2","3","4","5","6"},String.valueOf(Math.min(6,core.printerFeed())));r3.addView(e,weight());r3.addView(f,weight());page.addView(r3);
        title=field(page,"Título",v(getIntent(),"title"));subtitle=field(page,"Subtítulo",v(getIntent(),"subtitle"));body=multi(page,"Texto",v(getIntent(),"body"),5);qr=field(page,"Contenido QR",v(getIntent(),"qr"));copies=field(page,"Copias","1");copies.setInputType(InputType.TYPE_CLASS_NUMBER);
        imageSizeLabel=txt("Tamaño imagen · 75%",13,Color.DKGRAY,true);imageSizeLabel.setPadding(0,dp(12),0,0);page.addView(imageSizeLabel);imageSize=new SeekBar(this);imageSize.setMax(75);imageSize.setProgress(50);page.addView(imageSize);
        darkLabel=txt("Oscuridad térmica · "+core.printerDarkness(),13,Color.DKGRAY,true);darkLabel.setPadding(0,dp(12),0,0);page.addView(darkLabel);darkness=new SeekBar(this);darkness.setMax(110);darkness.setProgress(core.printerDarkness()-120);page.addView(darkness);
        Button choose=secondary("ELEGIR / CAMBIAR IMAGEN");choose.setOnClickListener(v->pickImage());page.addView(choose,top(dp(10)));Button remove=secondary("QUITAR IMAGEN");remove.setOnClickListener(v->{imageData="";setSpinner(imagePosition,"No imprimir");schedulePreview();});page.addView(remove,top(dp(8)));
        Button print=primary("IMPRIMIR AHORA");print.setOnClickListener(v->confirmPrint(print));page.addView(print,top(dp(16)));Button saveProfile=secondary("GUARDAR ESTOS AJUSTES DE IMPRESORA");saveProfile.setOnClickListener(v->saveProfile());page.addView(saveProfile,top(dp(8)));Button reconnect=secondary("RECONECTAR IMPRESORA");reconnect.setOnClickListener(v->reconnect(reconnect));page.addView(reconnect,top(dp(8)));Button close=secondary("CERRAR");close.setOnClickListener(v->finish());page.addView(close,top(dp(8)));status=txt("",13,Color.DKGRAY,false);status.setPadding(0,dp(10),0,0);page.addView(status);
        AdapterView.OnItemSelectedListener listener=new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?>p,View v,int pos,long id){schedulePreview();}public void onNothingSelected(AdapterView<?>p){}};for(Spinner s:new Spinner[]{template,typography,paper,qrSize,separator,imagePosition,cutMode,feedLines})s.setOnItemSelectedListener(listener);
        TextWatcher watcher=new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){schedulePreview();}public void afterTextChanged(Editable e){}};title.addTextChangedListener(watcher);subtitle.addTextChangedListener(watcher);body.addTextChangedListener(watcher);qr.addTextChangedListener(watcher);
        imageSize.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean from){imageSizeLabel.setText("Tamaño imagen · "+(25+p)+"%");schedulePreview();}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});darkness.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean from){darkLabel.setText("Oscuridad térmica · "+(120+p));}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});
        return root;}

    private String defaultTemplate(){String explicit=v(getIntent(),"template");if(!explicit.isEmpty())return explicit;String t=type.toLowerCase(Locale.ROOT);if(t.contains("reserva"))return"Reserva Express";if(t.contains("ruleta"))return"Ruleta QR";if(t.contains("rasca"))return"Rasca QR";if(t.contains("promoc"))return"Promoción Premium";if(t.contains("premio"))return"Premio Canjeable";if(t.contains("qr"))return"QR Personalizado";if(t.contains("imagen"))return"Solo Imagen";return"Minimal Premium";}
    private void schedulePreview(){if(preview==null||isFinishing())return;ui.removeCallbacks(previewTask);ui.postDelayed(previewTask,140);}
    private void renderNow(){final int generation=++renderGeneration;final JSONObject job=currentJob();io.execute(()->{Bitmap bm=null;String error="";try{bm=TicketRenderer.render(job);}catch(Exception e){error=msg(e);}Bitmap out=bm;String err=error;runOnUiThread(()->{if(isFinishing()){if(out!=null&&!out.isRecycled())out.recycle();return;}if(generation!=renderGeneration){if(out!=null&&!out.isRecycled())out.recycle();return;}Bitmap old=previewBitmap;if(out!=null){previewBitmap=out;preview.setImageBitmap(out);if(status!=null&&status.getText().toString().startsWith("Vista previa"))status.setText("");}else if(status!=null)status.setText("Vista previa · "+err);if(old!=null&&old!=out&&!old.isRecycled())old.recycle();});});}

    private JSONObject currentJob(){JSONObject j=new JSONObject();try{j.put("type",type).put("templateId",selected(template)).put("typography",selected(typography)).put("paperWidth",selected(paper).startsWith("58")?58:80).put("title",text(title)).put("subtitle",text(subtitle)).put("text",text(body)).put("qr",text(qr)).put("qrSize",selected(qrSize)).put("separator",sepValue()).put("imageData",imageData).put("imagePosition",posValue()).put("imageWidthPercent",25+imageSize.getProgress()).put("copies",clamp(parse(text(copies),1),1,5)).put("cutMode",cutValue(selected(cutMode))).put("feedLines",parse(selected(feedLines),core.printerFeed())).put("darkness",120+darkness.getProgress()).put("origin","APK nativa");}catch(Exception ignored){}return j;}
    private String sepValue(){String s=selected(separator);if(s.startsWith("Puntos"))return"dots";if(s.startsWith("Guiones"))return"dashes";if(s.startsWith("Doble"))return"double";if(s.startsWith("Ninguno"))return"none";return"line";}private String posValue(){String s=selected(imagePosition);if("Arriba".equals(s))return"top";if("Abajo".equals(s))return"bottom";return"none";}private String cutValue(String s){if(s.startsWith("Parcial"))return"partial";if(s.startsWith("Sin"))return"none";return"full";}private String cutLabel(String s){if("partial".equalsIgnoreCase(s))return"Parcial";if("none".equalsIgnoreCase(s))return"Sin corte";return"Completo";}

    private void confirmPrint(Button b){if(core.printerIp().isEmpty()){alert("Impresora sin configurar","Configura la IP en Ajustes.");return;}JSONObject j=currentJob();new AlertDialog.Builder(this).setTitle("Imprimir ticket").setMessage("Destino: "+core.printerIp()+":"+core.printerPort()+"\nPapel: "+j.optInt("paperWidth",80)+" mm\nPlantilla: "+j.optString("templateId")+"\nCopias: "+j.optInt("copies",1)).setNegativeButton("Cancelar",null).setPositiveButton("IMPRIMIR",(d,w)->printNow(b,j)).show();}
    private void printNow(Button b,JSONObject job){b.setEnabled(false);status.setText("Enviando a la impresora…");io.execute(()->{try{RemotePrinter.print(core,job);runOnUiThread(()->{b.setEnabled(true);status.setText("Impresión completada · "+core.printerStatus());toast("Ticket impreso");refreshPrinterStatus();});afterPrint();}catch(Exception e){runOnUiThread(()->{b.setEnabled(true);status.setText("Error de impresión · "+msg(e));refreshPrinterStatus();alert("No se pudo imprimir",msg(e));});}});}
    private void afterPrint(){if(!core.configured())return;try{core.post(core.action("historyAdd").put("type",type).put("reference",reference).put("event","Impreso desde APK").put("printer","IMP001").put("detail",detail).put("state","OK"));}catch(Exception ignored){}if(!reservationId.isEmpty())try{core.post(core.action("reservationMarkPrinted").put("id",reservationId));}catch(Exception ignored){}if(!participationCode.isEmpty())try{core.post(core.action("participationMarkPrinted").put("code",participationCode));}catch(Exception ignored){}}
    private void saveProfile(){JSONObject j=currentJob();core.prefs().edit().putInt("printerPaper",j.optInt("paperWidth",80)).putString("printerCut",j.optString("cutMode","full")).putInt("printerFeed",j.optInt("feedLines",3)).putInt("printerDarkness",j.optInt("darkness",180)).apply();toast("Perfil de impresora guardado");}
    private void reconnect(Button b){b.setEnabled(false);status.setText("Reconectando…");io.execute(()->{core.reconnectPrinter();runOnUiThread(()->{b.setEnabled(true);refreshPrinterStatus();status.setText(core.printerStatus());});});}
    private void refreshPrinterStatus(){if(printerStatus==null)return;boolean ok=core.printerConnected();printerStatus.setText((ok?"● ":"○ ")+"IMPRESORA · "+core.printerStatus());printerStatus.setTextColor(ok?Color.rgb(25,105,55):Color.rgb(150,65,40));}

    private void pickImage(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK_IMAGE);}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==PICK_IMAGE&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){Uri uri=data.getData();try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}try{imageData=ImageUtil.toDataUri(this,uri.toString());setSpinner(imagePosition,"Arriba");schedulePreview();}catch(Exception e){alert("Imagen",msg(e));}}}

    private Spinner spin(LinearLayout page,String label,String[] values,String selected){TextView l=txt(label,13,Color.DKGRAY,true);l.setPadding(0,dp(10),0,dp(4));page.addView(l);Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,values);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(a);s.setBackground(box(Color.WHITE,10,Color.rgb(210,210,210),1));page.addView(s,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(50)));setSpinner(s,selected);return s;}private EditText field(LinearLayout page,String label,String value){TextView l=txt(label,13,Color.DKGRAY,true);l.setPadding(0,dp(10),0,dp(4));page.addView(l);EditText e=input(value);e.setSingleLine(true);page.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(52)));return e;}private EditText multi(LinearLayout page,String label,String value,int lines){TextView l=txt(label,13,Color.DKGRAY,true);l.setPadding(0,dp(10),0,dp(4));page.addView(l);EditText e=input(value);e.setSingleLine(false);e.setMinLines(lines);e.setGravity(Gravity.TOP);e.setPadding(dp(12),dp(10),dp(12),dp(10));page.addView(e,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));return e;}private EditText input(String v){EditText e=new EditText(this);e.setText(v);e.setTextSize(16);e.setTextColor(Color.rgb(20,20,20));e.setPadding(dp(12),0,dp(12),0);e.setBackground(box(Color.WHITE,11,Color.rgb(205,205,205),1));return e;}
    private TextView cardText(String s){TextView t=txt(s,13,Color.DKGRAY,true);t.setPadding(dp(12),dp(10),dp(12),dp(10));t.setBackground(box(Color.WHITE,12,Color.rgb(210,210,210),1));return t;}private Button primary(String s){Button b=button(s);b.setTextColor(Color.WHITE);b.setBackground(box(Color.rgb(15,15,15),12,Color.TRANSPARENT,0));return b;}private Button secondary(String s){Button b=button(s);b.setTextColor(Color.rgb(20,20,20));b.setBackground(box(Color.WHITE,12,Color.rgb(190,190,190),1));return b;}private Button button(String s){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setMinHeight(dp(54));return b;}private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);return r;}private LinearLayout col(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);return c;}private LinearLayout.LayoutParams weight(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1);p.setMargins(dp(3),0,dp(3),0);return p;}private LinearLayout.LayoutParams top(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=v;return p;}private TextView txt(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable box(int fill,int r,int stroke,int sw){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(r));if(sw>0)d.setStroke(dp(sw),stroke);return d;}private String selected(Spinner s){Object x=s.getSelectedItem();return x==null?"":String.valueOf(x);}private void setSpinner(Spinner s,String value){if(s==null||value==null)return;for(int i=0;i<s.getCount();i++)if(String.valueOf(s.getItemAtPosition(i)).equalsIgnoreCase(value)){s.setSelection(i);return;}}private String text(EditText e){return e==null?"":e.getText().toString().trim();}private int parse(String s,int f){try{return Integer.parseInt(s.trim());}catch(Exception e){return f;}}private int clamp(int v,int min,int max){return Math.max(min,Math.min(max,v));}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private void alert(String t,String m){if(!isFinishing())new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("Aceptar",null).show();}private String msg(Throwable t){String m=t==null?"Error desconocido":t.getMessage();return m==null||m.trim().isEmpty()?String.valueOf(t):m;}
}
