package com.ofaro.participaciones;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ToolsActivity extends Activity {
    private final ExecutorService io=Executors.newSingleThreadExecutor(); private AppCore core; private LinearLayout page; private TextView subtitle;
    @Override protected void onCreate(Bundle b){super.onCreate(b);core=new AppCore(this);setContentView(build());showMenu();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
    private View build(){LinearLayout root=col();root.setBackgroundColor(Color.rgb(246,245,242));LinearLayout head=col();head.setPadding(dp(18),dp(15),dp(18),dp(13));head.setBackgroundColor(Color.rgb(15,15,15));head.addView(text("O FARO",23,Color.WHITE,true));subtitle=text("Herramientas",13,Color.LTGRAY,false);head.addView(subtitle);root.addView(head);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);page=col();page.setPadding(dp(14),dp(14),dp(14),dp(30));scroll.addView(page);root.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));return root;}
    private void showMenu(){clear("Herramientas");back("QR, plantillas e historial",this::finish);page.addView(title("Herramientas rápidas"));Button qr=big("QR RÁPIDOS","Carta, menú, Wi‑Fi, reseñas, Instagram y personalizados");qr.setOnClickListener(v->showQr());page.addView(qr,top(dp(10)));Button templates=big("PLANTILLAS GUARDADAS","Plantillas definidas en Google Sheets");templates.setOnClickListener(v->showTemplates());page.addView(templates,top(dp(9)));Button hist=big("HISTORIAL","Últimos movimientos del sistema");hist.setOnClickListener(v->showHistory());page.addView(hist,top(dp(9)));Button free=big("TICKET LIBRE","Abrir el estudio de impresión con todas las opciones");free.setOnClickListener(v->startActivity(new Intent(this,TicketPreviewActivity.class).putExtra("type","Libre")));page.addView(free,top(dp(9)));}
    private void showQr(){clear("QR rápidos");back("QR rápidos",this::showMenu);TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=col();page.addView(list,topWrap(dp(8)));load("qrList",status,a->{status.setText(a.length()+" accesos");for(int i=0;i<a.length();i++){JSONObject q=a.optJSONObject(i);if(q==null)continue;LinearLayout c=card();String name=q.optString("name","QR");c.addView(text(name,19,Color.rgb(20,20,20),true));c.addView(text(q.optString("ticketText",""),13,Color.DKGRAY,false));Button p=secondary("ABRIR EN ESTUDIO DE IMPRESIÓN");p.setOnClickListener(v->{Intent in=new Intent(this,TicketPreviewActivity.class);in.putExtra("title","MESÓN O FARO");in.putExtra("subtitle",name.toUpperCase());in.putExtra("body",q.optString("ticketText",name));in.putExtra("qr",q.optString("content",""));in.putExtra("type","QR");in.putExtra("reference",q.optString("id",""));startActivity(in);});c.addView(p,top(dp(7)));list.addView(c,bottom(dp(8)));}});}
    private void showTemplates(){clear("Plantillas");back("Plantillas guardadas",this::showMenu);TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=col();page.addView(list,topWrap(dp(8)));load("templateList",status,a->{status.setText(a.length()+" plantillas");for(int i=0;i<a.length();i++){JSONObject t=a.optJSONObject(i);if(t==null)continue;LinearLayout c=card();String name=t.optString("name","Plantilla");c.addView(text(name,19,Color.rgb(20,20,20),true));JSONObject q=t.optJSONObject("qr");String body=t.optString("text",q==null?"":q.optString("ticketText",""));String qr=q==null?t.optString("qr",""):q.optString("content","");Button p=secondary("USAR PLANTILLA");p.setOnClickListener(v->{Intent in=new Intent(this,TicketPreviewActivity.class);in.putExtra("title",t.optString("title","MESÓN O FARO"));in.putExtra("subtitle",name);in.putExtra("body",body);in.putExtra("qr",qr);in.putExtra("type","Plantilla");in.putExtra("reference",t.optString("id",""));startActivity(in);});c.addView(p,top(dp(7)));list.addView(c,bottom(dp(8)));}});}
    private void showHistory(){clear("Historial");back("Historial",this::showMenu);TextView status=text("Cargando…",14,Color.DKGRAY,false);page.addView(status);LinearLayout list=col();page.addView(list,topWrap(dp(8)));if(!requireApi())return;io.execute(()->{try{JSONObject r=core.post(core.action("historyList").put("limit",120));core.ensureOk(r);JSONArray a=r.optJSONArray("items");if(a==null)a=new JSONArray();JSONArray out=a;runOnUiThread(()->{status.setText(out.length()+" movimientos");for(int i=0;i<out.length();i++){JSONObject h=out.optJSONObject(i);if(h==null)continue;LinearLayout c=card();c.addView(text(h.optString("type","Acción")+" · "+h.optString("event",h.optString("action","")),16,Color.rgb(20,20,20),true));c.addView(text(h.optString("date","")+" · "+h.optString("reference",""),13,Color.DKGRAY,false));list.addView(c,bottom(dp(7)));}});}catch(Exception e){runOnUiThread(()->status.setText("Error: "+msg(e)));}});}
    private interface Loaded{void done(JSONArray a);}private void load(String action,TextView status,Loaded done){if(!requireApi())return;io.execute(()->{try{JSONObject r=core.post(core.action(action));core.ensureOk(r);JSONArray a=r.optJSONArray("items");if(a==null)a=new JSONArray();JSONArray out=a;runOnUiThread(()->done.done(out));}catch(Exception e){runOnUiThread(()->status.setText("Error: "+msg(e)));}});}
    private boolean requireApi(){if(core.configured())return true;status("Configura la API y la clave desde Ajustes.");return false;}private void status(String s){android.widget.Toast.makeText(this,s,android.widget.Toast.LENGTH_LONG).show();}
    private void clear(String s){page.removeAllViews();subtitle.setText(s);}private void back(String name,Runnable r){LinearLayout line=row();Button b=secondary("‹ ATRÁS");b.setOnClickListener(v->r.run());line.addView(b,new LinearLayout.LayoutParams(dp(105),dp(48)));TextView t=text(name,20,Color.rgb(20,20,20),true);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(10),0,0,0);line.addView(t,new LinearLayout.LayoutParams(0,dp(48),1));page.addView(line);page.addView(space(dp(8)));}private TextView title(String s){return text(s,27,Color.rgb(20,20,20),true);}private Button big(String a,String b){Button x=primary(a+"\n"+b);x.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);x.setPadding(dp(15),0,dp(15),0);return x;}private LinearLayout card(){LinearLayout c=col();c.setPadding(dp(14),dp(13),dp(14),dp(13));c.setBackground(box(Color.WHITE,14,Color.rgb(218,216,212),1));return c;}private LinearLayout col(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);return c;}private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setBackground(box(Color.rgb(15,15,15),12,Color.TRANSPARENT,0));return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(20,20,20));b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setBackground(box(Color.WHITE,12,Color.rgb(190,190,190),1));return b;}private TextView text(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable box(int f,int r,int s,int sw){GradientDrawable d=new GradientDrawable();d.setColor(f);d.setCornerRadius(dp(r));if(sw>0)d.setStroke(dp(sw),s);return d;}private LinearLayout.LayoutParams top(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(72));p.topMargin=v;return p;}private LinearLayout.LayoutParams topWrap(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.topMargin=v;return p;}private LinearLayout.LayoutParams bottom(int v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.bottomMargin=v;return p;}private View space(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,h));return v;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private String msg(Throwable t){String m=t==null?"Error desconocido":t.getMessage();return m==null||m.trim().isEmpty()?String.valueOf(t):m;}
}
